import binpacking

musics = {
    "Once Upon a Time": 873,
    "Start Menu": 355,
    "Your Best Friend": 474,
    "Fallen Down": 889,
    "Ruins": 2001,
    "Uwa!! So Temperate": 653,
    "Anticipation": 310,
    "Unnecessary Tension": 287,
    "Enemy Approaching": 1911,
    "Ghost Fight": 1826,
    "Determination": 878,
    "Home": 1461,
    "Home (Music Box)": 1787,
    "Heartache": 3643,
    "sans": 908,
    "Nyeh Heh Heh": 866,
    "Snowy": 1008,
    "Uwa!! So Holiday": 258,
    "Dogbass": 128,
    "Mysterious Place": 1511,
    "Dogsong": 1135,
    "Snowdin Town": 1121,
    "Shop": 928,
    "Bonetrousle": 1236,
    "Dating Start": 2092,
    "Dating Tense": 660,
    "Dating Fight": 743,
    "Premonition": 258,
    "Danger Mystery": 232,
    "Undyne": 629,
    "Waterfall": 1161,
    "Run": 604,
    "Quiet Water": 386,
    "Memory": 355,
    "Bird That Carries You Over a Disproportionately Small Gap": 551,
    "Dummy": 0,
    "Pathetic House": 298,
    "Spooktune": 221,
    "Spookwave": 750,
    "Ghouliday": 284,
    "Chill": 858,
    "Thundersnail": 0,
    "Temmie Village": 0,
    "Tem Shop": 456,
    "Ngahhh": 523,
    "Spear of Justice": 0,
    "Ooo": 46,
    "Alphys": 0,
    "It's Showtime": 0,
    "Metal Crusher": 0,
    "Another Medium": 0,
    "Uwa!! So Heats": 0,
    "Stronger Monsters": 0,
    "Hotel": 0,
    "Can You Really Call This a Hotel, I Didn't Receive a Mint on My Pillow or Anything": 0,
    "Confession": 0,
    "Live Report": 0,
    "Death Report": 0,
    "Spider Dance": 0,
    "Wrong Enemy": 0,
    "Oh! One True Love": 0,
    "Oh! Dungeon": 0,
    "It's Raining Somewhere Else": 0,
    "Core Approach": 0,
    "Core": 0,
    "Last Episode": 0,
    "Oh My": 0,
    "Death by Glamour": 0,
    "For the Fans": 0,
    "Long Elevator": 0,
    "Undertale": 0,
    "Song That Might Play When You Fight Sans": 0,
    "The Choice": 0,
    "Small Shock": 153,
    "Barrier": 0,
    "Bergentrückung": 0,
    "ASGORE": 0,
    "You Idiot": 0,
    "Your Best Nightmare": 0,
    "Finale": 0,
    "An Ending": 0,
    "She's Playing Piano": 0,
    "Here We Are": 0,
    "Amalgam": 0,
    "Fallen Down (Reprise)": 0,
    "Don't Give Up": 0,
    "Hopes and Dreams": 0,
    "Burn in Despair": 0,
    "Save the World": 0,
    "His Theme": 0,
    "Final Power": 0,
    "Reunited": 0,
    "Menu (Full)": 0,
    "Respite": 0,
    "Bring It In, Guys": 0,
    "Last Goodbye": 0,
    "But the Earth Refused to Die": 144,
    "Battle Against a True Hero": 2549,
    "Power of \"Neo\"": 719,
    "MEGALOVANIA": 3364,
    "Good Night": 0,
    "Gaster Theme": 234,
}

# remove item that have no size
k,v = list(musics.keys()), list(musics.values())
for i in range(len(k)):
    if v[i] <= 0:
        del musics[k[i]]

# find best banks
bins = binpacking.to_constant_volume(musics,(1024*8)-887)

# print
for i, b in enumerate(bins):
    size = sum(b.values())
    print(f"Bank {i}: (size={size})")
    print(list(b.keys()))
    print("\n")
