; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_undertale_ost_11=music_data_undertale_ost_11
.endif

music_data_undertale_ost_11:
	.byte 4
	.word @instruments
	.word @samples-5
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6 ; 00 : Enemy Approching
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,@song1ch5,@song1ch6 ; 01 : It's Raining Somewhere Else
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,@song2ch5,@song2ch6 ; 02 : Here We Are
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,@song3ch5,@song3ch6 ; 03 : Menu (Full)
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_undertale_ost_11
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env25,@env10,@env22,@env0 ; 00 : Echo
	.word @env1,@env28,@env22,@env8 ; 01 : Fade vibrate
	.word @env5,@env10,@env22,@env0 ; 02 : Basic
	.word @env2,@env10,@env22,@env0 ; 03 : Kicks
	.word @env7,@env10,@env22,@env23 ; 04 : Fade
	.word @env4,@env10,@env26,@env0 ; 05 : Lead
	.word @env9,@env10,@env24,@env0 ; 06 : Music box
	.word @env0,@env10,@env22,@env0 ; 07 : NoSound
	.word @env11,@env10,@env22,@env0 ; 08 : Kicks Loud
	.word @env4,@env10,@env24,@env0 ; 09 : Lead 1
	.word @env5,@env10,@env22,@env27 ; 0a : Vibrate

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $04,$cf,$00,$01,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$12
@env2:
	.byte $00,$c8,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$00,$00
@env4:
	.byte $0e,$cf,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$00,$0b,$c3,$05,$c2,$06,$c1,$06,$c1,$00,$14
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $00,$c0,$bf,$be,$bf,$c0,$c1,$c2,$c1,$00,$01
@env7:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env8:
	.byte $00,$c4,$c2,$c0,$00,$03
@env9:
	.byte $00,$c9,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c9,$c8,$c7,$c6,$c5,$c4,$c4,$c3,$c7,$c6,$c5,$c4,$c3,$c3,$c2,$c4,$c3,$c3,$c2,$02,$c1,$00,$1d
@env10:
	.byte $c0,$7f,$00,$01
@env11:
	.byte $00,$cf,$ca,$c8,$c6,$c4,$c2,$c1,$c0,$00,$08
@env12:
	.byte $c0,$b5,$00,$00
@env13:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$00,$00
@env14:
	.byte $c0,$b6,$00,$00
@env15:
	.byte $c0,$b7,$00,$00
@env16:
	.byte $c0,$bd,$00,$00
@env17:
	.byte $c0,$bc,$00,$00
@env18:
	.byte $c0,$b8,$00,$00
@env19:
	.byte $c0,$b9,$00,$00
@env20:
	.byte $c0,$bb,$00,$00
@env21:
	.byte $c0,$ba,$00,$00
@env22:
	.byte $7f,$00,$00
@env23:
	.byte $00,$bd,$be,$bf,$be,$bf,$c0,$00,$06
@env24:
	.byte $c2,$7f,$00,$00
@env25:
	.byte $00,$cf,$06,$c0,$c0,$c8,$05,$c0,$c0,$c4,$05,$c0,$c0,$c2,$04,$c0,$c1,$00,$10
@env26:
	.byte $c1,$7f,$00,$00
@env27:
	.byte $00,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$00,$01
@env28:
	.byte $c0,$c1,$00,$00
@env29:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env30:
	.byte $c0,$cc,$00,$00
@env31:
	.byte $c0,$c0,$cc,$cc,$00,$00

@samples:
	.byte $68+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0d,$40,$00 ; 00 bird (Pitch:13)
	.byte $76+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$48,$40,$01 ; 13 choir_b3 (Pitch:8)
	.byte $76+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4a,$40,$01 ; 14 choir_b3 (Pitch:10)
	.byte $76+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4b,$40,$01 ; 15 choir_b3 (Pitch:11)
	.byte $6e+.lobyte(FAMISTUDIO_DPCM_PTR),$1f,$48,$40,$01 ; 16 choir_cs4 (Pitch:8)
	.byte $6e+.lobyte(FAMISTUDIO_DPCM_PTR),$1f,$49,$40,$01 ; 17 choir_cs4 (Pitch:9)
	.byte $6e+.lobyte(FAMISTUDIO_DPCM_PTR),$1f,$4a,$40,$01 ; 18 choir_cs4 (Pitch:10)
	.byte $6e+.lobyte(FAMISTUDIO_DPCM_PTR),$1f,$4b,$40,$01 ; 19 choir_cs4 (Pitch:11)
	.byte $6e+.lobyte(FAMISTUDIO_DPCM_PTR),$1f,$4c,$40,$01 ; 1a choir_cs4 (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$c2,$0e,$40,$02 ; 09 cymbal (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$4b,$40,$04 ; 0a elevator (Pitch:11)
	.byte $0a+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0b,$40,$04 ; 0b elevator_end (Pitch:11)
	.byte $1c+.lobyte(FAMISTUDIO_DPCM_PTR),$32,$0b,$40,$04 ; 0c elevator_start (Pitch:11)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$07,$40,$02 ; 0d impact_hit_cs6 (Pitch:7)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$08,$40,$02 ; 0e impact_hit_cs6 (Pitch:8)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$09,$40,$02 ; 0f impact_hit_cs6 (Pitch:9)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0a,$40,$02 ; 10 impact_hit_cs6 (Pitch:10)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0b,$40,$02 ; 11 impact_hit_cs6 (Pitch:11)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0c,$40,$02 ; 12 impact_hit_cs6 (Pitch:12)
	.byte $77+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0d,$40,$00 ; 53 megadrive_drumki (Pitch:13)
	.byte $77+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0e,$40,$00 ; 54 megadrive_drumki (Pitch:14)
	.byte $77+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0f,$40,$00 ; 55 megadrive_drumki (Pitch:15)
	.byte $7d+.lobyte(FAMISTUDIO_DPCM_PTR),$06,$0f,$40,$00 ; 56 megadrive_drumki 1 (Pitch:15)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$08,$40,$02 ; 17 nes_drumkit_1 (Pitch:8)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0b,$40,$02 ; 18 nes_drumkit_1 (Pitch:11)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0d,$40,$02 ; 19 nes_drumkit_1 (Pitch:13)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0f,$40,$02 ; 1a nes_drumkit_1 (Pitch:15)
	.byte $4f+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$0f,$40,$02 ; 1b nes_drumkit_2 (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$32,$0f,$40,$02 ; 1c nes_drumkit_3 (Pitch:15)
	.byte $66+.lobyte(FAMISTUDIO_DPCM_PTR),$1e,$0f,$40,$02 ; 1d nes_drumkit_4 (Pitch:15)
	.byte $6e+.lobyte(FAMISTUDIO_DPCM_PTR),$1e,$0f,$40,$02 ; 1e nes_drumkit_4_re (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$70,$00 ; 1f triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$60,$00 ; 20 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$00,$00 ; 21 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$20,$00 ; 22 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$40,$00 ; 23 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$30,$00 ; 24 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$50,$00 ; 25 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$7e,$00 ; 26 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$10,$00 ; 27 triangle noise (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $9d, $78, $80, $1c, $83, $7c, $1d, $81, $7f
@song0ref14:
	.byte $1e, $a3, $00, $91, $1e, $a5, $00, $8f, $47, $48, .lobyte(@env29), .hibyte(@env29), $1c, $a5, $00, $91, $84, $1c, $8f
	.byte $00, $91, $1c, $a5, $48, .lobyte(@env0), .hibyte(@env0), $49, $00, $8f, $47
	.byte $41, $0d
	.word @song0ref5
	.byte $47, $48, .lobyte(@env29), .hibyte(@env29), $84, $1d, $83, $1e, $b3, $1c, $83, $1d, $9d, $1b, $91, $19, $9f, $48, .lobyte(@env0)
	.byte .hibyte(@env0), $49, $83, $47, $4e, $02, $00, $9b, $80, $1c, $83, $1d, $81
	.byte $41, $08
	.word @song0ref14
	.byte $47, $1c, $a5, $00, $91, $1c, $8f, $00, $91, $1c, $a5, $00, $8f, $47, $9d, $1c, $83, $1d, $81, $1e, $a3, $00, $4e, $01
	.byte $87, $1e, $83, $1f, $81, $20, $a5, $00, $87, $4e, $00, $87, $47, $84, $22, $a5, $23, $87, $00, $87, $25, $b7, $00, $a3
@song0ref130:
	.byte $47, $00, $9b
@song0ref133:
	.byte $80, $25, $83, $26, $81, $27, $a3, $00, $91, $23, $b7, $47, $84, $1d, $a5, $1e, $91, $1d, $a3, $1b, $91, $1d, $91, $20
	.byte $8f, $47, $00, $9b, $80, $20, $83, $21, $81, $22, $a3, $00, $91, $23, $b7, $47, $7c, $48, .lobyte(@env29), .hibyte(@env29)
	.byte $4e, $02, $84, $20, $a5, $27, $91, $25, $cb, $48, .lobyte(@env0), .hibyte(@env0), $49, $00, $8d, $7f, $81, $47, $4e
	.byte $00, $9d
	.byte $41, $14
	.word @song0ref133
@song0ref201:
	.byte $1e, $8f, $47, $20, $91, $1e, $91, $1d, $91, $00
@song0ref211:
	.byte $8f, $1d, $91, $1b, $91, $19, $91, $00, $8f, $47, $17, $91, $00, $91, $1b, $91, $00, $8f, $1d, $a5, $19, $91, $16, $8f
	.byte $41, $2e
	.word @song0ref130
	.byte $41, $14
	.word @song0ref133
	.byte $41, $20
	.word @song0ref201
	.byte $47
@song0ref245:
	.byte $00, $9b, $80
@song0ref248:
	.byte $1f, $83, $20, $81, $21, $a3, $00, $87, $1a, $83, $1b, $81, $1c, $b7, $47, $84
@song0ref264:
	.byte $21, $a5, $25, $91, $23, $a3, $21, $91, $20, $91, $21, $8f, $47, $00, $a5, $4e, $02, $1e, $91, $1d, $8f, $1b, $91, $1e
	.byte $91, $1d, $91, $1b, $8f, $47, $48, .lobyte(@env6), .hibyte(@env6), $1d, $a5, $1e, $91, $20, $db, $48, .lobyte(@env0)
	.byte .hibyte(@env0), $49, $81, $47, $4e, $00
	.byte $41, $10
	.word @song0ref245
	.byte $47
	.byte $41, $0d
	.word @song0ref264
@song0ref318:
	.byte $9b, $21, $83, $22, $81, $23, $a3, $00, $91, $1e, $b3, $22, $81, $47, $23, $a5, $27, $91, $25, $b7, $00, $a3, $47, $00
	.byte $9b
	.byte $41, $2f
	.word @song0ref248
	.byte $47, $4e, $00
	.byte $41, $10
	.word @song0ref245
	.byte $47
	.byte $41, $0d
	.word @song0ref264
	.byte $41, $12
	.word @song0ref318
	.byte $a3, $23, $91, $25, $91, $27, $8f, $47, $28, $a5, $2c, $91, $2a, $dd, $47, $00, $91, $2a, $91, $2a, $91, $2a, $8f, $27
	.byte $91, $27, $91, $23, $91, $00, $8f, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $4d, $0e, $4e, $01, $a7, $82
@song0ref400:
	.byte $16, $44, $8f, $00, $a3, $16, $44, $8f, $00, $a3, $14, $44, $8f, $00, $a5, $14, $44, $85, $00, $99, $14, $87, $44, $9b
	.byte $00, $8f, $4d, $0e, $4e, $01, $a7
	.byte $41, $0a
	.word @song0ref400
	.byte $16, $44, $a3, $00, $91, $14, $44, $a1, $00, $b7, $4d, $0e, $4e, $01, $a7
	.byte $41, $1a
	.word @song0ref400
	.byte $4d, $00, $4e, $02, $9d, $84, $13, $14, $81, $15, $16, $17, $87, $16, $15, $81, $14, $13, $00, $8f, $4e, $01, $89, $17
	.byte $18, $81, $19, $1a, $1b, $87, $1a, $19, $81, $18, $17, $00, $93, $17, $81, $18, $19, $1a, $1b, $1c, $1d, $1e, $b9, $20
	.byte $b7, $00, $a3
@song0ref503:
	.byte $00, $a5, $80, $23, $a3, $00, $91, $20, $b7, $84, $19, $a5, $1b, $91, $19, $a3, $17, $91, $19, $91, $1d, $8f, $00, $a5
	.byte $80, $1e, $a3, $00, $91, $20, $b7, $7c, $84, $1c, $a5, $23, $91, $22, $cb, $00, $8d, $7f, $81
	.byte $41, $12
	.word @song0ref503
	.byte $1b
	.byte $41, $09
	.word @song0ref211
@song0ref553:
	.byte $19, $91, $17, $91, $16, $91, $00, $8f, $12, $91, $00, $91, $17, $91, $00, $8f, $19, $a5, $16, $91, $12, $8f
	.byte $41, $25
	.word @song0ref503
	.byte $41, $12
	.word @song0ref503
	.byte $1b
	.byte $41, $09
	.word @song0ref211
	.byte $41, $16
	.word @song0ref553
@song0ref588:
	.byte $00, $a5, $80
@song0ref591:
	.byte $1c, $a3, $00, $91, $19, $b7, $84, $1c, $a5, $00, $91, $1c, $a3, $00, $b7, $a7, $12, $91, $00, $a3, $12, $91, $00, $a3
	.byte $11, $a5, $12, $91, $14, $dd
	.byte $41, $11
	.word @song0ref588
@song0ref624:
	.byte $80, $1e, $a3, $00, $91, $19, $b7, $1e, $a5, $00, $91, $20, $b7, $00, $a3, $00, $a5
	.byte $41, $1d
	.word @song0ref591
	.byte $41, $11
	.word @song0ref588
	.byte $41, $0b
	.word @song0ref624
	.byte $a3, $00, $a5, $25, $8f, $00, $a5, $25, $91, $27, $dd, $00, $91, $27, $91, $27, $91, $27, $8f, $23, $91, $23, $91, $1e
	.byte $91, $00, $8f, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $84
@song0ref682:
	.byte $14, $85, $00, $89, $14, $83, $00, $8b
@song0ref690:
	.byte $14, $8d, $00, $81
@song0ref694:
	.byte $14, $83, $00, $89, $14, $87, $00, $87, $14
@song0ref703:
	.byte $8d, $00, $81, $14, $85, $00, $89, $14, $83, $00, $89, $81, $14, $8b, $00, $83
	.byte $41, $11
	.word @song0ref694
	.byte $41, $0a
	.word @song0ref703
@song0ref725:
	.byte $87, $81, $14, $85, $00, $89, $14, $85, $00, $89
	.byte $41, $13
	.word @song0ref690
@song0ref738:
	.byte $87, $14, $85, $00, $87, $0b, $91, $12, $91, $17, $91, $0b, $a3, $12, $91, $19, $9b, $00, $85
	.byte $41, $25
	.word @song0ref682
	.byte $41, $11
	.word @song0ref694
	.byte $41, $0a
	.word @song0ref703
	.byte $41, $0a
	.word @song0ref725
	.byte $41, $13
	.word @song0ref690
	.byte $41, $0b
	.word @song0ref738
	.byte $0d, $a3, $12, $91, $1a, $9b, $00, $85
	.byte $41, $20
	.word @song0ref682
@song0ref786:
	.byte $17, $91, $1e, $91, $23, $91, $19, $a3, $20, $91, $1d, $91, $25, $8f
	.byte $41, $20
	.word @song0ref682
@song0ref803:
	.byte $10, $91, $17, $91, $1d, $91, $12, $a3, $17, $91, $19, $91, $12, $8f
	.byte $41, $20
	.word @song0ref682
	.byte $41, $0e
	.word @song0ref786
@song0ref823:
	.byte $17, $8f, $00, $93, $23, $8f, $00, $19, $8d, $00, $93, $27, $8f, $00, $93, $19, $8d, $00, $17, $99, $00, $89, $27, $8f
	.byte $00, $91, $25, $8f, $00, $19, $8f, $00, $1b, $8f, $00, $12, $8d, $00
	.byte $41, $20
	.word @song0ref682
	.byte $41, $0e
	.word @song0ref786
	.byte $41, $20
	.word @song0ref682
	.byte $41, $0e
	.word @song0ref803
	.byte $41, $20
	.word @song0ref682
	.byte $41, $0e
	.word @song0ref786
	.byte $41, $26
	.word @song0ref823
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref682
@song0ref888:
	.byte $09, $91, $0b, $91, $0d, $91, $06, $8f, $09, $91, $12, $91, $10, $91, $0b, $8f, $0d, $91, $0b, $91, $0d, $91, $0b, $8f
	.byte $11, $91, $16, $91, $14, $91, $13, $8f
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref682
@song0ref926:
	.byte $16, $85, $00, $89, $16, $83, $00, $8b, $16, $8d, $00, $81, $16, $83, $00, $89, $16, $87, $00, $87, $16, $8d, $00, $81
	.byte $16, $85, $00, $89, $16, $83, $00, $89
	.byte $41, $0c
	.word @song0ref926
@song0ref961:
	.byte $18, $8f, $00, $91, $16, $91, $18, $91, $13, $8f
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref888
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref682
	.byte $41, $20
	.word @song0ref926
	.byte $41, $08
	.word @song0ref926
	.byte $1a, $91
	.byte $41, $08
	.word @song0ref961
	.byte $1a, $8f, $14, $91, $00, $91, $14, $91, $00, $dd, $93, $80
@song0ref1009:
	.byte $12, $91, $12, $91, $12, $8f, $0f, $91, $0f, $91, $0b, $91, $00, $8f, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $86
@song0ref1028:
	.byte $14, $87, $00, $87, $21, $87, $00, $87, $14, $87, $00, $87, $21, $87, $00, $85
	.byte $41, $10
	.word @song0ref1028
	.byte $41, $10
	.word @song0ref1028
	.byte $41, $10
	.word @song0ref1028
	.byte $41, $10
	.word @song0ref1028
	.byte $41, $10
	.word @song0ref1028
@song0ref1059:
	.byte $18, $8d, $00, $81
@song0ref1063:
	.byte $15, $83, $00, $81, $15, $83, $00, $81, $15, $83, $00, $8b, $18, $8f, $00, $91
	.byte $41, $08
	.word @song0ref1063
	.byte $18, $91, $21, $87, $00, $85
	.byte $41, $10
	.word @song0ref1028
	.byte $41, $10
	.word @song0ref1028
	.byte $41, $10
	.word @song0ref1028
	.byte $41, $10
	.word @song0ref1028
	.byte $41, $10
	.word @song0ref1028
	.byte $41, $10
	.word @song0ref1028
	.byte $41, $14
	.word @song0ref1059
@song0ref1109:
	.byte $16, $83, $00, $81, $16, $83, $00, $81
	.byte $41, $08
	.word @song0ref1109
	.byte $16, $83, $00, $81, $16, $81, $00, $81
@song0ref1128:
	.byte $88, $1f, $87, $20, $87, $21, $87, $22, $87, $23, $91, $86
@song0ref1140:
	.byte $14, $83, $21, $81, $00, $85, $14, $83, $21, $81, $00, $87, $14, $83, $21, $81, $00, $87, $1a, $43, $19, $83, $43, $18
	.byte $85, $00, $81
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
@song0ref1197:
	.byte $14, $83, $21, $81, $00, $85
@song0ref1203:
	.byte $16, $1f, $85, $00, $87, $16, $1f, $85, $00, $87
@song0ref1213:
	.byte $19
@song0ref1214:
	.byte $43, $1e, $81, $43, $1f, $81, $43, $20, $85, $00, $16, $00, $8d
	.byte $41, $15
	.word @song0ref1203
	.byte $41, $15
	.word @song0ref1203
	.byte $16
	.byte $41, $09
	.word @song0ref1214
	.byte $8f
	.byte $41, $0b
	.word @song0ref1213
	.byte $41, $23
	.word @song0ref1128
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $1b
	.word @song0ref1197
	.byte $41, $15
	.word @song0ref1203
	.byte $41, $15
	.word @song0ref1203
	.byte $16
	.byte $41, $09
	.word @song0ref1214
	.byte $8f
	.byte $41, $0b
	.word @song0ref1213
	.byte $41, $23
	.word @song0ref1128
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $14, $83, $21, $81, $00, $85
	.byte $41, $23
	.word @song0ref1128
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $14, $83, $21, $81, $00, $85
	.byte $41, $23
	.word @song0ref1128
	.byte $41, $19
	.word @song0ref1140
	.byte $41, $19
	.word @song0ref1140
	.byte $14, $83, $21, $81, $00, $85
@song0ref1396:
	.byte $14, $87, $00, $9b, $14, $87, $00, $99
	.byte $41, $08
	.word @song0ref1396
@song0ref1407:
	.byte $14, $87, $00, $87, $14, $87, $00, $87, $14, $87, $00, $87, $14, $87, $00, $85
	.byte $41, $0b
	.word @song0ref1407
	.byte $99, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1431:
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $ff, $9b, $ff, $9b, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $a7, $80
@song0ref1476:
	.byte $17, $91, $00, $a3, $17, $91, $00, $a3, $15, $a5, $00, $91, $15, $8f, $00, $91, $15, $a5, $00, $8d, $4e, $00, $81, $a7
	.byte $41, $08
	.word @song0ref1476
	.byte $17, $a5, $00, $91, $16, $a3, $00, $b5, $4e, $02, $81, $a7
	.byte $41, $15
	.word @song0ref1476
	.byte $ff, $9b, $bb, $84, $1c, $b7, $00, $a3
@song0ref1526:
	.byte $00, $a5, $80
@song0ref1529:
	.byte $20, $a3, $00, $91, $1b, $b7, $00, $ff, $99, $a7, $1b, $a3, $00, $91, $1b, $b7, $78, $4e, $02, $84, $16, $91, $15, $91
	.byte $13, $91, $11, $8f, $16, $91, $15, $91, $13, $91, $11, $8b, $4e, $00, $81, $7f, $81
	.byte $41, $0b
	.word @song0ref1526
	.byte $ff, $9b, $ff, $9b, $00, $a5
	.byte $41, $22
	.word @song0ref1529
	.byte $41, $0b
	.word @song0ref1526
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $ff, $9b, $e1, $17, $91, $00, $91, $1b, $8f, $00, $a5, $20, $91, $1e, $dd, $78, $4e, $02, $00, $91
	.byte $41, $0c
	.word @song0ref1009
	.byte $4e, $00, $00, $8d, $7f, $81, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $74, $84
@song0ref1644:
	.byte $38, $91, $3a, $91, $3b, $91, $3d, $8f, $3a, $91, $3b, $91, $3d, $91, $38, $8f, $3d, $91, $3b, $91, $3a, $91, $3f, $8f
	.byte $3d, $91, $40, $4e, $91, $40, $4d, $91, $3d, $8f
	.byte $41, $0e
	.word @song0ref1644
	.byte $3f, $8f, $40, $50, $91, $40, $4e, $91, $3f, $91, $40, $4e, $8f, $3f, $91, $3d, $91, $3b, $91, $3a, $8f
	.byte $41, $0e
	.word @song0ref1644
	.byte $3f, $8f, $3d, $91, $3b, $91, $38, $91, $3b, $8f, $3a, $91, $38, $91, $35, $91, $31, $8d, $7f, $81, $00, $ff, $99
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $41, $08
	.word @song0ref1431
	.byte $ff, $9b, $ff, $9b, $78, $93, $80, $0f, $91, $0f, $91, $0f, $8f, $0b, $91, $0b, $91, $06, $91, $00, $8d, $7f, $81, $42
	.word @song0ch6loop
@song1ch0:
@song1ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7f, $50, $ff, $10, $8a
@song1ref10:
	.byte $0d, $ff, $ff, $a9, $47, $ff, $ff, $ab, $47, $7f, $50, $ff, $10, $08, $ff, $ff, $a9, $47, $ff, $ff, $ab, $47, $7f, $50
	.byte $ff, $10, $0b, $ff, $ff, $a9, $47, $ff, $ff, $ab, $47, $7f, $50, $ff, $10, $06, $ff, $ff, $a9, $47, $ff, $ff, $ab, $47
	.byte $7f, $50, $ff, $10
	.byte $41, $1c
	.word @song1ref10
	.byte $47, $7f
@song1ref67:
	.byte $50, $fc, $10, $8c
@song1ref71:
	.byte $19, $ed, $7f, $8a, $0d, $ed, $08, $c9, $47, $01, $ed, $0d, $ed, $06, $a3, $08, $a3, $47, $50, $fc, $10, $8c, $14, $ed
	.byte $7f, $8a, $08, $ed, $03, $c9, $47, $8e, $40, $08, $ed, $8a, $08, $ed, $03, $a3, $04, $a3, $47, $50, $fc, $10, $8c, $17
	.byte $ed, $7f, $8a, $0b, $ed, $06, $c7, $00, $47, $40, $0b, $eb, $00, $0b, $ed, $06, $a1, $00, $01, $9f, $00, $81, $47, $50
	.byte $fc, $10, $8c, $12, $ed, $7f, $8a, $06, $ed, $01, $c9, $47, $8e, $40, $06, $ed, $8a, $06, $ed, $01, $a3, $04, $a3, $47
	.byte $41, $3d
	.word @song1ref67
	.byte $47
	.byte $41, $3d
	.word @song1ref67
	.byte $47, $50, $fe, $00, $8c, $15, $ff, $ff, $a9, $47, $7f, $50, $fe, $00, $14, $ff, $ff, $a9, $47, $7f, $50, $fe, $00, $17
	.byte $ff, $ff, $a9, $47, $7f, $50, $fe, $00, $12, $ff, $ff, $a9, $47, $7f, $50, $fe, $00, $17, $ff, $ff, $a9, $47, $7f, $50
	.byte $fe, $00, $17, $ff, $ff, $a9, $47, $7f, $50, $fe, $00, $16, $ff, $ff, $a9, $47, $7f, $50, $fe, $00, $16, $ff, $ff, $a9
	.byte $47, $7f, $50, $fc, $10
	.byte $41, $3d
	.word @song1ref71
	.byte $47
	.byte $41, $34
	.word @song1ref67
	.byte $a7, $50, $fe, $00, $8c, $28, $9f, $47, $ff, $ff, $a3, $00, $81, $83, $47, $ff, $ff, $ab, $47, $ff, $ff, $ab, $47, $ff
	.byte $ff, $ab, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
@song1ref288:
	.byte $ff, $ff, $ab, $ff, $ff, $ab, $ff, $ff, $ab, $ff, $ff, $ab
	.byte $41, $0c
	.word @song1ref288
	.byte $cb, $7f, $8a
@song1ref306:
	.byte $28, $a1, $27, $a3, $28, $c7, $25, $a3, $27, $a3, $28, $a3, $2f, $a3, $2c, $a1, $28, $c9, $27, $a1, $25, $a3, $20, $a3
	.byte $00, $c9, $27, $a1, $25, $a3, $27, $c7, $20, $a3, $22, $a3, $23, $a3, $2a, $c7, $27, $ff, $97, $00, $9f, $cb, $26, $a1
	.byte $25, $a3, $26, $c7, $1e, $a3, $1f, $a3, $21, $a3, $2a, $c7, $26, $c9, $25, $a1, $23, $a3, $25, $a3, $1e, $c9, $00, $a1
@song1ref378:
	.byte $20, $a3, $21, $a3, $28, $c7, $2c, $a3, $ef, $00, $ff, $b9, $4e, $02, $cb, $8c
	.byte $41, $44
	.word @song1ref306
	.byte $00, $87, $1e, $cd, $00, $93
	.byte $41, $0d
	.word @song1ref378
	.byte $41, $44
	.word @song1ref306
	.byte $00, $87, $1e, $cd, $00, $93
	.byte $41, $0c
	.word @song1ref378
	.byte $cb, $8a, $1b, $a1, $1c, $a1, $00, $1b, $a1, $00, $17, $9f, $00, $1b, $a1, $00, $1c, $9f, $00, $81, $1b, $cb, $1c, $9d
	.byte $00, $1e, $ed, $20, $c7, $00, $1b, $87, $1c, $87, $1b, $b1, $00, $a5, $17, $a1, $00, $23, $a1, $00, $22, $9f, $00, $1e
	.byte $a1, $00, $1b, $9f, $00, $81, $20, $ff, $93, $00, $c7, $03, $a1, $00, $04, $9f, $00, $81, $cb, $1a, $a1, $1c, $a1, $00
	.byte $1a, $a1, $00, $17, $9f, $00, $1a, $a1, $00, $1c, $9f, $00, $81, $1e, $cb, $1f, $9d, $00, $1e, $ed, $1f, $c7, $00, $1c
	.byte $eb, $00, $21, $a1, $00, $25, $a1, $00, $21, $9f, $00, $25, $a1, $00, $28, $9f, $00, $81, $2d, $ed, $00, $ff, $b9, $ff
	.byte $95, $25, $b5, $23, $b5, $20, $a3, $1e, $cb, $1c, $c5, $1e, $c7, $20, $c9, $1e, $87, $1f, $85, $1e, $ff, $81, $1e, $b5
	.byte $25, $b5, $23, $8d, $21, $93, $23, $ff, $dd, $20, $a3, $21, $8d, $20, $93, $1e, $ff, $93, $00, $ff, $93, $ff, $ff, $ab
	.byte $ff, $ff, $ab, $ff, $ff, $ab, $4e, $02, $cb, $8c
	.byte $41, $44
	.word @song1ref306
	.byte $00, $87, $1e, $cd, $00, $93
	.byte $41, $0d
	.word @song1ref378
	.byte $41, $44
	.word @song1ref306
	.byte $00, $87, $1e, $bf, $00, $a1, $20, $a3, $21, $a3, $28, $c7, $00, $85, $50, $fe, $00, $2c, $9b, $ff, $ff, $a7, $00, $81
	.byte $ff, $ff, $ab, $ff, $ff, $ab, $ff, $ff, $ab, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $41, $0c
	.word @song1ref288
	.byte $41, $0c
	.word @song1ref288
	.byte $41, $0c
	.word @song1ref288
	.byte $41, $0c
	.word @song1ref288
	.byte $89, $7f, $50, $fc, $00, $8c
@song1ref666:
	.byte $20, $ff, $91, $00, $ff, $8b, $ff, $ff, $ab, $89, $7f, $50, $fc, $00, $1b, $ff, $91, $00, $ff, $8b, $ff, $ff, $ab, $89
	.byte $7f, $50, $fc, $00, $1e, $ff, $91, $00, $ff, $8b, $ff, $ff, $ab, $89, $7f, $50, $fc, $00, $19, $ff, $91, $00, $ff, $8b
	.byte $ff, $ff, $ab, $89, $7f, $50, $fc, $00
	.byte $41, $28
	.word @song1ref666
	.byte $7f, $50, $fc, $00
	.byte $41, $28
	.word @song1ref666
	.byte $7f, $1c, $ff, $ff, $9f, $89, $1b, $ff, $ff, $9f, $89, $1e, $ff, $ff, $9f, $89, $19, $ff, $ff, $9f, $89, $1e, $ff, $ff
	.byte $9f, $89, $1e, $ff, $ff, $9f, $89, $1d, $ff, $ff, $9f, $89, $1d, $ff, $ff, $9f, $89, $50, $fc, $00
	.byte $41, $28
	.word @song1ref666
	.byte $7f, $50, $fc, $00
	.byte $41, $27
	.word @song1ref666
	.byte $ff, $ff, $ab, $ff, $ff, $ab, $ff, $ff, $ab, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
@song1ref799:
	.byte $72, $84
@song1ref801:
	.byte $40, $04, $ff, $ff, $a9, $40, $04, $ff, $ff, $a9, $40, $04, $ff, $ff, $a9
	.byte $41, $0c
	.word @song1ref801
	.byte $41, $0c
	.word @song1ref801
	.byte $41, $0c
	.word @song1ref801
	.byte $41, $0c
	.word @song1ref801
	.byte $40, $04, $ff, $ff, $a9
@song1ref833:
	.byte $78, $86
@song1ref835:
	.byte $40, $0c, $91, $00, $8f, $7c, $03, $8f, $00, $91, $02, $8f, $00, $8f
@song1ref849:
	.byte $03, $91, $00, $8f, $02, $8f, $00, $91, $03, $8f, $00, $8f, $01, $91, $00, $8f, $02, $8f, $00, $91, $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $0c
	.word @song1ref835
	.byte $90
	.byte $41, $14
	.word @song1ref849
	.byte $41, $0c
	.word @song1ref833
	.byte $90
	.byte $41, $14
	.word @song1ref849
	.byte $41, $0c
	.word @song1ref833
	.byte $90
	.byte $41, $14
	.word @song1ref849
	.byte $41, $0c
	.word @song1ref833
	.byte $90
	.byte $41, $14
	.word @song1ref849
	.byte $41, $0c
	.word @song1ref833
	.byte $90
	.byte $41, $14
	.word @song1ref849
	.byte $41, $0c
	.word @song1ref833
	.byte $90
	.byte $41, $14
	.word @song1ref849
	.byte $41, $0c
	.word @song1ref833
	.byte $90
	.byte $41, $14
	.word @song1ref849
	.byte $ff, $ff, $ab
	.byte $41, $20
	.word @song1ref833
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $78
	.byte $41, $20
	.word @song1ref835
	.byte $41, $0c
	.word @song1ref799
	.byte $40, $04, $ff, $ff, $a9, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $51, $ff
	.byte $41, $0c
	.word @song1ref288
	.byte $41, $0c
	.word @song1ref288
	.byte $41, $0c
	.word @song1ref288
	.byte $41, $0c
	.word @song1ref288
@song1ref1099:
	.byte $51, $80, $93, $51, $90, $91, $51, $a0, $91, $51, $b0, $93, $51, $c0, $91, $51, $d0, $91, $51, $e0, $93, $51, $f0, $91
	.byte $51, $ff, $8b, $51, $ec, $81, $51, $e6, $81, $51, $d9, $81, $51, $d2, $81, $51, $ca, $81, $51, $c1, $81, $51, $b8, $83
	.byte $51, $ab, $81, $51, $a3, $81, $51, $9b, $81, $51, $91, $81, $51, $86, $f1, $ff, $ff, $ab
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
@song1ref1198:
	.byte $51, $80, $93, $51, $90, $91, $51, $a0, $91, $51, $b0, $93, $51, $c0, $91, $51, $d0, $91, $51, $e0, $93, $51, $f0, $91
	.byte $51, $ff, $fb, $51, $ec, $81, $51, $e6, $81, $51, $d9, $81, $51, $d2, $81, $51, $ca, $81, $51, $c1, $81, $51, $b8, $83
	.byte $51, $ab, $81, $51, $a3, $81, $51, $9b, $81, $51, $91, $81, $51, $86, $81
	.byte $41, $15
	.word @song1ref1198
	.byte $41, $15
	.word @song1ref1198
	.byte $41, $15
	.word @song1ref1198
	.byte $41, $15
	.word @song1ref1198
	.byte $41, $15
	.word @song1ref1198
	.byte $41, $15
	.word @song1ref1198
	.byte $41, $15
	.word @song1ref1198
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $41, $18
	.word @song1ref1099
	.byte $51, $80, $93, $51, $90, $91, $51, $a0, $91, $51, $b0, $93, $51, $c0, $91, $51, $d0, $91, $51, $e0, $93, $51, $f0, $91
	.byte $51, $ff, $ff, $95
	.byte $41, $0c
	.word @song1ref288
	.byte $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $8f, $7f, $50, $ff, $10, $8a
@song1ref1344:
	.byte $17, $ff, $ff, $99, $ff, $ff, $ab, $8f, $7f, $50, $ff, $10, $12, $ff, $ff, $99, $ff, $ff, $ab, $8f, $7f, $50, $ff, $10
	.byte $15, $ff, $ff, $99, $ff, $ff, $ab, $8f, $7f, $50, $ff, $10, $10, $ff, $ff, $99, $ff, $ff, $ab, $8f, $7f, $50, $ff, $10
	.byte $41, $20
	.word @song1ref1344
	.byte $7f, $50, $fc, $10, $8c
@song1ref1400:
	.byte $23, $ff, $91, $70, $00, $ff, $85, $ff, $ff, $ab, $8f, $7f, $50, $fc, $10, $1e, $ff, $91, $70, $00, $ff, $85, $ff, $ff
	.byte $ab, $8f, $7f, $50, $fc, $10, $21, $ff, $91, $70, $00, $ff, $85, $ff, $ff, $ab, $ef, $7f, $1c, $a1, $00, $1e, $a1, $00
	.byte $23, $c7, $50, $fe, $00, $25, $a3, $ff, $ff, $9b, $00, $8d, $8f, $7f, $50, $fc, $10
	.byte $41, $2e
	.word @song1ref1400
	.byte $7f, $50, $fc, $10
	.byte $41, $2e
	.word @song1ref1400
	.byte $7f, $50, $fe, $00, $1f, $ff, $ff, $99, $8f, $7f, $50, $fe, $00, $1e, $ff, $ff, $99, $8f, $7f, $50, $fe, $00, $21, $ff
	.byte $ff, $99, $8f, $7f, $50, $fe, $00, $1c, $ff, $ff, $99, $8f, $7f, $50, $fe, $00, $21, $ff, $ff, $99, $8f, $7f, $50, $fe
	.byte $00, $21, $ff, $ff, $99, $8f, $7f, $50, $fe, $00, $20, $ff, $ff, $99, $8f, $7f, $50, $fe, $00, $20, $ff, $ff, $99, $8f
	.byte $7f, $50, $fc, $10
	.byte $41, $2e
	.word @song1ref1400
	.byte $7f, $50, $fc, $10
	.byte $41, $2c
	.word @song1ref1400
	.byte $89, $83, $ff, $ff, $ab, $ff, $ff, $ab, $ff, $ff, $ab, $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
	.byte $83, $7f, $50, $ff, $10, $8a
@song1ref1582:
	.byte $10, $ff, $ff, $a5, $ff, $ff, $ab, $83, $7f, $50, $ff, $10, $0b, $ff, $ff, $a5, $ff, $ff, $ab, $83, $7f, $50, $ff, $10
	.byte $0e, $ff, $ff, $a5, $ff, $ff, $ab, $83, $7f, $50, $ff, $10, $09, $ff, $ff, $a5, $ff, $ff, $ab, $83, $7f, $50, $ff, $10
	.byte $41, $20
	.word @song1ref1582
	.byte $7f, $50, $fd, $10, $8c
@song1ref1638:
	.byte $1c, $ff, $93, $70, $00, $ff, $8f, $ff, $ff, $ab, $83, $7f, $50, $fd, $10, $17, $ff, $93, $70, $00, $ff, $8f, $ff, $ff
	.byte $ab, $83, $7f, $50, $fd, $10, $1a, $ff, $93, $70, $00, $ff, $8f, $ff, $ff, $ab, $83, $7f, $50, $fd, $10, $15, $ff, $93
	.byte $70, $00, $ff, $8f, $ff, $ff, $ab, $83, $7f, $50, $fd, $10
	.byte $41, $28
	.word @song1ref1638
	.byte $7f, $50, $fd, $10
	.byte $41, $24
	.word @song1ref1638
	.byte $7f, $8a, $1c, $ed, $00, $ff, $b9, $83, $50, $fe, $00, $8c, $19, $ff, $ff, $a5, $83, $7f, $50, $fe, $00, $18, $ff, $ff
	.byte $a5, $83, $7f, $50, $fe, $00, $1a, $ff, $ff, $a5, $83, $7f, $50, $fe, $00, $15, $ff, $ff, $a5, $83, $7f, $50, $fe, $00
	.byte $1b, $ff, $ff, $a5, $83, $7f, $50, $fe, $00, $1b, $ff, $ff, $a5, $83, $7f, $50, $fe, $00, $1a, $ff, $ff, $a5, $83, $7f
	.byte $50, $fe, $00, $1a, $ff, $ff, $a5, $83, $7f, $50, $fd, $10
	.byte $41, $28
	.word @song1ref1638
	.byte $7f, $50, $fd, $10
	.byte $41, $1d
	.word @song1ref1638
	.byte $7f, $50, $fd, $10, $83, $15, $ff, $8f, $70, $00, $fb, $7f, $50, $fe, $00, $31, $95, $ff, $ff, $a7, $83, $00, $ff, $ff
	.byte $a9, $ff, $ff, $ab, $ff, $ff, $ab, $42
	.word @song1ch6loop
@song2ch0:
@song2ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $c9, $47, $ff, $ff, $c9, $47, $ff, $ff, $c9, $47
	.byte $ff, $ff, $c9, $47, $ff, $ff, $c9, $47, $ff, $ff, $c9, $47, $ff, $ff, $c9, $47, $ff, $ff, $c9, $47, $ff, $ff, $c9, $47
	.byte $ff, $ff, $c9, $47, $ff, $ff, $c9, $47, $ff, $ff, $c9, $47, $ff, $ff, $c9, $47, $ff, $ff, $c9, $47, $ff, $ff, $c9, $47
	.byte $ff, $ff, $c9, $47, $c1, $47, $78, $50, $01, $f0, $92
@song2ref76:
	.byte $0a, $9f, $11, $9d, $0f, $9f, $14, $9d, $16, $9f, $0f, $9d, $14, $9f, $11, $9d, $15, $9f, $12, $9d, $47, $18, $9f, $19
	.byte $9d, $16, $9f, $18, $9d, $14, $9f, $16, $9d, $11, $9f, $1b, $9d, $18, $9f, $19, $9d, $47, $78, $50, $01, $f0, $0a, $9f
	.byte $11, $9d, $0f, $9f, $14, $9d, $16, $9f, $0f, $9d, $17, $9f, $13, $9d, $18, $9f, $19, $9d, $47, $1a, $9f, $1b, $9d, $18
	.byte $9f, $1a, $9d, $16, $9f, $18, $9d, $13, $9f, $1d, $9d, $1a, $9f, $1b, $9d, $47, $78, $50, $01, $f0
	.byte $41, $50
	.word @song2ref76
	.byte $47, $78, $50, $01, $f0
	.byte $41, $50
	.word @song2ref76
	.byte $47, $78, $50, $01, $f0
	.byte $41, $50
	.word @song2ref76
@song2ref187:
	.byte $47, $0a, $9f, $11, $9d, $0f, $9f, $09, $9d, $10, $9f, $0e, $9d, $0a, $9f, $0b, $9d, $0c, $9f, $0d, $9d, $47, $0a, $9f
	.byte $11, $9d, $0f, $9f, $09, $9d, $10, $9f, $0e, $9d, $0a, $9f, $0c, $9d, $09, $9f, $0b, $9d, $47, $0a, $9f, $11, $9d, $0f
	.byte $9f, $09, $9d, $10, $9f, $0e, $9d, $0a, $9f, $0b, $9d, $0c, $9f, $0d, $9d, $47, $0a, $9f, $11, $9d, $0f, $9f, $09, $9d
	.byte $10, $9f, $0e, $9d, $07, $9f, $0e, $9d, $09, $9f, $10, $9d
	.byte $41, $50
	.word @song2ref187
	.byte $47, $7a, $50, $ff, $00, $14, $ff, $ff, $c7, $47, $ff, $ff, $c9, $47, $00, $ff, $ff, $c7, $47, $ff, $ff, $c9, $47, $ff
	.byte $ff, $c9, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
@song2ref304:
	.byte $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9
	.byte $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9
	.byte $c1, $7c, $4e, $01, $88
@song2ref357:
	.byte $16, $bf, $00, $9f, $18, $bf, $00, $9d, $1a, $9f, $00, $9d, $1b, $9f, $00, $9d, $1d, $ff, $81, $00, $ff, $c3, $16, $bf
	.byte $00, $9f, $18, $bf, $00, $9d, $1c, $9f, $00, $9d, $1d, $9f, $00, $9d, $1f, $ff, $81, $00, $ff, $c3, $4e, $01
	.byte $41, $2c
	.word @song2ref357
	.byte $4e, $01
	.byte $41, $2c
	.word @song2ref357
	.byte $4e, $01
	.byte $41, $2c
	.word @song2ref357
	.byte $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9
	.byte $78, $50, $ff, $00, $92, $10, $ff, $ff, $c7, $ff, $ff, $c9, $00, $ff, $ff, $c7, $ff, $ff, $c9, $ff, $ff, $c9, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $41, $31
	.word @song2ref304
	.byte $41, $30
	.word @song2ref304
	.byte $41, $27
	.word @song2ref304
	.byte $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9
	.byte $78, $90
@song2ref505:
	.byte $40, $01, $8f, $00, $8d, $40, $07, $8d, $00, $8d, $40, $05, $8f, $00, $8d, $40, $01, $8d, $00, $8d, $40, $07, $8f, $00
	.byte $8d, $40, $05, $8d, $00, $8d, $40, $01, $8f, $00, $8d, $40, $05, $8d, $00, $8d, $40, $01, $8f, $00, $8d, $40, $05, $8d
	.byte $00, $8d, $50, $01, $f0, $40, $01, $8f, $00, $8d, $40, $07, $8d, $00, $8d, $40, $05, $8f, $00, $8d, $40, $01, $8d, $00
	.byte $8d, $40, $07, $8f, $00, $8d, $40, $05, $8d, $00, $8d, $40, $01, $8f, $00, $8d, $40, $05, $8d, $00, $8d, $50, $fc, $80
	.byte $40, $01, $8f, $00, $8d, $40, $05, $8d, $00, $8d
	.byte $41, $50
	.word @song2ref505
	.byte $41, $50
	.word @song2ref505
	.byte $41, $45
	.word @song2ref505
	.byte $85, $40, $05, $85, $40, $05, $85, $40, $05, $85, $50, $fe, $80, $00, $b7, $40, $05, $85, $00, $bf
	.byte $41, $50
	.word @song2ref505
	.byte $41, $50
	.word @song2ref505
	.byte $41, $50
	.word @song2ref505
	.byte $41, $50
	.word @song2ref505
	.byte $41, $50
	.word @song2ref505
	.byte $41, $50
	.word @song2ref505
	.byte $41, $50
	.word @song2ref505
	.byte $41, $50
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $41, $28
	.word @song2ref505
	.byte $40, $01, $8f, $00, $8d, $40, $07, $8d, $00, $8d, $40, $05, $8f, $00, $8d, $40, $01, $8d, $00, $8d, $40, $07, $8f, $00
	.byte $8d, $40, $05, $8d, $00, $8d, $40, $01, $8f, $00, $8d, $40, $05, $85, $40, $05, $85, $40, $05, $85, $40, $05, $85, $00
	.byte $b7, $40, $05, $85, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
@song2ref756:
	.byte $51, $00, $02, $e1, $51, $00, $06, $df
@song2ref764:
	.byte $51, $00, $07, $bf, $51, $00, $03, $bf, $51, $00, $04
@song2ref775:
	.byte $87, $51, $84, $87, $51, $88, $87, $51, $8c, $87, $51, $90, $87, $51, $94, $87, $51, $98, $87, $51, $9c, $87, $51, $a0
	.byte $89, $51, $a4, $87, $51, $a8, $87, $51, $ac, $87, $51, $b0, $87, $51, $b4, $87, $51, $b8, $87, $51, $bc, $87, $51, $c0
	.byte $89, $51, $c4, $87, $51, $c8, $87, $51, $cc, $87, $51, $d0, $87, $51, $d4, $87, $51, $d8, $87, $51, $dc, $87, $51, $e0
	.byte $89, $51, $e4, $87, $51, $e8, $87, $51, $ec, $87, $51, $f0, $87, $51, $f4, $87, $51, $f8, $87, $51, $fc, $87, $51, $ff
	.byte $00, $51, $fd, $81, $51, $f9, $81, $51, $f5, $83, $51, $f1, $81, $51, $ed, $81, $51, $e9, $81, $51, $e5, $81, $51, $e1
	.byte $81, $51, $dd, $81, $51, $d9, $81, $51, $d5, $81, $51, $d1, $81, $51, $cd, $81, $51, $c9, $81, $51, $c5, $81, $51, $c0
	.byte $81, $51, $bc, $81, $51, $b8, $81, $51, $b4, $81, $51, $b0, $81, $51, $ac, $81, $51, $a8, $81, $51, $a4, $81, $51, $a0
	.byte $81, $51, $9c, $81, $51, $98, $81, $51, $94, $81, $51, $90, $81, $51, $8c, $81, $51, $88, $81, $51, $84, $81, $51, $00
	.byte $02, $e1, $51, $00, $06, $df, $51, $00, $08, $bf, $51, $00, $04, $bf, $51, $00, $09
	.byte $41, $44
	.word @song2ref775
	.byte $41, $4e
	.word @song2ref764
	.byte $41, $44
	.word @song2ref775
	.byte $41, $4e
	.word @song2ref764
	.byte $41, $44
	.word @song2ref775
	.byte $41, $4e
	.word @song2ref764
	.byte $41, $40
	.word @song2ref775
	.byte $c1
	.byte $41, $52
	.word @song2ref756
	.byte $41, $44
	.word @song2ref775
	.byte $41, $4e
	.word @song2ref764
	.byte $41, $44
	.word @song2ref775
	.byte $41, $4e
	.word @song2ref764
	.byte $41, $44
	.word @song2ref775
	.byte $41, $4e
	.word @song2ref764
	.byte $41, $40
	.word @song2ref775
	.byte $41, $27
	.word @song2ref304
	.byte $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $41, $31
	.word @song2ref304
	.byte $7c, $4e, $01, $88
@song2ref1044:
	.byte $19, $bf, $00, $9f, $1b, $bf, $00, $9d, $1d, $9f, $00, $9d, $1e, $9f, $00, $9d, $20, $ff, $81, $00, $ff, $c3, $19, $bf
	.byte $00, $9f, $1b, $bf, $00, $9d, $1f, $9f, $00, $9d, $20, $9f, $00, $9d, $22, $ff, $81, $00, $ff, $c3, $4e, $01
	.byte $41, $2c
	.word @song2ref1044
	.byte $4e, $01
	.byte $41, $2c
	.word @song2ref1044
	.byte $4e, $01
	.byte $41, $2c
	.word @song2ref1044
	.byte $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9, $ff, $ff, $c9
	.byte $50, $ff, $00, $92, $0d, $ff, $ff, $c7, $ff, $ff, $c9, $00, $ff, $ff, $c7, $ff, $ff, $c9, $ff, $ff, $c9, $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $41, $31
	.word @song2ref304
	.byte $7c, $4e, $01, $88
@song2ref1159:
	.byte $25, $bf, $00, $9f, $27, $bf, $00, $9d, $29, $9f, $00, $9d, $2a, $9f, $00, $9d, $2c, $ff, $81, $00, $ff, $c3, $25, $bf
	.byte $00, $9f, $27, $bf, $00, $9d, $2b, $9f, $00, $9d, $2c, $9f, $00, $9d, $2e, $ff, $81, $00, $ff, $c3, $4e, $01
	.byte $41, $2c
	.word @song2ref1159
	.byte $4e, $01
	.byte $41, $2c
	.word @song2ref1159
	.byte $4e, $01
	.byte $41, $2c
	.word @song2ref1159
	.byte $41, $27
	.word @song2ref304
	.byte $42
	.word @song2ch6loop
@song3ch0:
	.byte $4e, $02, $84
@song3ref4:
	.byte $20, $87, $00, $91, $74, $20, $87, $00, $a5, $7f, $2c, $87, $00, $91, $74, $2c, $87, $00, $91, $7f, $27, $87, $00, $91
	.byte $74, $27, $87, $00, $ff, $89, $47, $7f, $25, $87, $00, $91, $74, $25, $87, $00, $a5, $7f, $2c, $87, $00, $91, $74, $2c
	.byte $87, $00, $91, $7f, $20, $87, $00, $91, $74, $20, $87, $00, $ff, $89, $47, $7f, $20, $87, $00, $91, $74, $20, $87, $00
	.byte $a5, $7f, $25, $87, $00, $91, $74, $25, $87, $00, $91, $7f, $2c, $87, $00, $91, $74, $2c, $87, $00, $a5, $7f, $2e, $87
	.byte $00, $91, $74, $2e, $87, $00, $b9, $47, $7f, $2c, $87, $00, $91, $74, $2c, $87, $00, $a5, $7f, $27, $87, $00, $91, $74
	.byte $27, $87, $00, $91, $7f, $25, $87, $00, $91, $74, $25, $87, $00, $ff, $89, $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $7f, $4e, $02
	.byte $41, $6b
	.word @song3ref4
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf
@song3ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7f, $4e, $02
@song3ref319:
	.byte $20, $87, $74, $94, $2c, $c3, $7f, $84, $2c, $87, $74, $94, $2c, $af, $7f, $84, $27, $87, $74, $94, $2c, $ff, $a7, $47
	.byte $7f, $84, $25, $87, $74, $94, $31, $c3, $7f, $84, $2c, $87, $74, $94, $31, $af, $7f, $84, $20, $87, $74, $94, $31, $ff
	.byte $a7, $47, $7f, $84, $20, $87, $74, $94, $2c, $c3, $7f, $84, $25, $87, $74, $94, $2c, $af, $7f, $84, $2c, $87, $74, $94
	.byte $2c, $c3, $7f, $84, $2e, $87, $74, $94, $2c, $d7, $47, $7f, $84, $2c, $87, $74, $94, $2f, $c3, $7f, $84, $27, $87, $74
	.byte $94, $2e, $af, $7f, $84, $25, $87, $74, $94, $2c, $af, $00, $f5, $47, $7f, $4e, $02, $84
	.byte $41, $38
	.word @song3ref319
	.byte $47, $78, $84
@song3ref439:
	.byte $38, $87, $00, $9b, $31, $87, $00, $9b, $33, $87, $00, $9b, $31, $87, $00, $9b, $2c, $87, $00, $87, $31, $87, $00, $9b
	.byte $33, $87, $00, $9b, $35, $87, $00, $87, $33, $87, $00, $87, $31, $87, $00, $87, $47, $2c, $87, $00, $9b, $31, $87, $00
	.byte $9b, $33, $87, $00, $9b, $36, $87, $00, $87, $35, $87, $00, $9b, $36, $87, $00, $87, $35, $87, $00, $87, $33, $87, $00
	.byte $87, $31, $87, $00, $9b, $2c, $87, $00, $9b, $47
	.byte $41, $50
	.word @song3ref439
	.byte $42
	.word @song3ch0loop
@song3ch1:
@song3ref527:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $4e, $02, $84
@song3ref566:
	.byte $0d, $87, $00, $af, $0d, $87, $00, $87, $11, $87, $00, $87, $0d, $87, $00, $9b, $12, $87, $00, $af, $11, $87, $00, $af
	.byte $0d, $87, $00, $9b, $0f, $87, $00, $87, $4e, $02, $0d, $87, $00, $af, $0d, $87, $00, $87, $11, $87, $00, $87, $0d, $87
	.byte $00, $9b, $12, $87, $00, $af, $14, $87, $00, $9b, $16, $87, $00, $9b, $14, $87, $00, $9b, $4e, $02, $0d, $87, $00, $af
	.byte $0d, $87, $00, $87, $14, $87, $00, $87, $0d, $87, $00, $9b, $11, $87, $00, $c3, $11, $87, $00, $9b, $12, $87, $00, $87
	.byte $14, $87, $00, $9b, $4e, $02, $10, $87, $00, $af, $0b, $87, $00, $87, $10, $87, $00, $87, $0b, $87, $00, $9b, $0f, $87
	.byte $00, $af, $14, $87, $00, $9b, $16, $87, $00, $9b, $14, $87, $00, $9b, $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
@song3ch1loop:
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $4e, $02
	.byte $41, $80
	.word @song3ref566
	.byte $42
	.word @song3ch1loop
@song3ch2:
	.byte $41, $24
	.word @song3ref527
	.byte $41, $24
	.word @song3ref527
	.byte $84
@song3ref796:
	.byte $0d, $87, $00, $af, $0d, $87, $00, $87, $11, $87, $00, $87, $0d, $87, $00, $9b, $12, $87, $00, $af, $11, $87, $00, $af
	.byte $0d, $87, $00, $9b, $0f, $87, $00, $87, $0d, $87, $00, $af, $0d, $87, $00, $87, $11, $87, $00, $87, $0d, $87, $00, $9b
	.byte $12, $87, $00, $af, $14, $87, $00, $9b, $16, $87, $00, $9b, $14, $87, $00, $9b, $0d, $87, $00, $af, $0d, $87, $00, $87
	.byte $14, $87, $00, $87, $0d, $87, $00, $9b, $11, $87, $00, $c3, $11, $87, $00, $9b, $12, $87, $00, $87, $14, $87, $00, $9b
	.byte $10, $87, $00, $af, $0b, $87, $00, $87, $10, $87, $00, $87, $0b, $87, $00, $9b, $0f, $87, $00, $af, $14, $87, $00, $9b
	.byte $16, $87, $00, $9b, $14, $87, $00, $9b
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
@song3ch2loop:
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $41, $80
	.word @song3ref796
	.byte $42
	.word @song3ch2loop
@song3ch3:
	.byte $00, $a5, $86, $1e, $91, $1e, $91, $00, $91, $1e, $91, $1e, $91, $1e, $91, $00, $a5, $1e, $91, $1e, $91, $00, $a5, $1e
	.byte $91, $1e, $91
@song3ref997:
	.byte $00, $a5, $1e, $91, $1e, $91, $00, $91, $1e, $91, $1e, $91, $1e, $91, $00
@song3ref1012:
	.byte $a5, $1e, $91, $1e, $91, $00, $a5, $1e, $91, $1e, $91, $00, $a5, $1e, $91, $1e, $91, $00, $91, $1e, $91, $1e, $91, $1e
	.byte $91, $00, $91, $1e, $91, $1e, $91, $1e, $91, $00, $91, $1e, $91, $1e, $91, $00, $91, $a7, $1e, $91, $1e, $91, $00, $91
	.byte $1e, $91, $1e, $91, $1e, $91, $00, $ff, $9d
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
@song3ch3loop:
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $41, $29
	.word @song3ref997
	.byte $41, $39
	.word @song3ref1012
	.byte $42
	.word @song3ch3loop
@song3ch4:
	.byte $41, $24
	.word @song3ref527
	.byte $41, $24
	.word @song3ref527
	.byte $41, $24
	.word @song3ref527
@song3ref1202:
	.byte $a7, $15, $91, $15, $91, $16, $91, $15, $91, $16, $91, $14, $91, $00, $91, $14, $91, $15, $91, $16, $91, $00, $91, $14
	.byte $91, $15, $91, $16, $91, $00, $a5, $15, $91, $15, $91, $16, $91, $15, $91, $16, $91, $14, $91, $00, $91, $15, $91, $00
	.byte $91, $15, $91, $00, $91, $14, $91, $00, $91, $14, $91, $00, $a5, $15, $91, $15, $91, $16, $91, $15, $91, $16, $91, $14
	.byte $91, $00, $91, $14, $91, $15, $91, $16, $91, $00, $91, $14, $91, $15, $91, $00, $91, $16, $91, $00, $91, $15, $91, $15
	.byte $91, $16, $91, $15, $91, $16, $91, $14, $91, $00, $ff, $9d
	.byte $41, $6c
	.word @song3ref1202
	.byte $41, $6c
	.word @song3ref1202
@song3ref1316:
	.byte $17, $91, $00, $91, $15, $91, $17, $91, $16, $91, $15, $91, $17, $91, $14, $91, $00, $91, $17, $91, $15, $91, $16, $91
	.byte $17, $91, $14, $91, $17, $91, $16, $91, $17, $91, $00, $91, $15, $91, $17, $91, $16, $91, $15, $91, $17, $91, $14, $91
	.byte $00, $91, $15, $91, $17, $91, $15, $91, $17, $91, $14, $91, $17, $91, $14, $91, $17, $91, $00, $91, $15, $91, $17, $91
	.byte $16, $91, $15, $91, $17, $91, $14, $91, $00, $91, $17, $91, $15, $91, $16, $91, $17, $91, $14, $91, $17, $91, $00, $91
	.byte $16, $91, $00, $91, $15, $91, $17, $91, $16, $91, $15, $91, $17, $91, $14, $91, $00, $ff, $9d
	.byte $41, $73
	.word @song3ref1316
	.byte $41, $73
	.word @song3ref1316
	.byte $41, $73
	.word @song3ref1316
	.byte $41, $73
	.word @song3ref1316
	.byte $41, $73
	.word @song3ref1316
@song3ch4loop:
	.byte $41, $73
	.word @song3ref1316
	.byte $41, $73
	.word @song3ref1316
	.byte $41, $73
	.word @song3ref1316
	.byte $42
	.word @song3ch4loop
@song3ch5:
	.byte $41, $24
	.word @song3ref527
	.byte $41, $24
	.word @song3ref527
	.byte $78, $92
@song3ref1467:
	.byte $25, $b9, $44, $91, $29, $b9, $27, $b9, $44, $b9, $00, $b9, $25, $b9, $44, $91, $29, $b9, $20, $b9, $44, $b9, $00, $b9
	.byte $20, $b9, $44, $91, $25, $b9, $27, $b9, $44, $91, $24, $b9, $44, $a5, $25, $b9, $44, $91, $20, $b9, $1e, $b9, $44, $b9
	.byte $00, $b9
	.byte $41, $32
	.word @song3ref1467
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $32
	.word @song3ref1467
	.byte $41, $32
	.word @song3ref1467
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $32
	.word @song3ref1467
	.byte $41, $32
	.word @song3ref1467
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $32
	.word @song3ref1467
	.byte $41, $32
	.word @song3ref1467
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
@song3ch5loop:
	.byte $78
	.byte $41, $32
	.word @song3ref1467
	.byte $41, $32
	.word @song3ref1467
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song3ch5loop
@song3ch6:
	.byte $41, $24
	.word @song3ref527
	.byte $41, $24
	.word @song3ref527
	.byte $41, $24
	.word @song3ref527
	.byte $8a
@song3ref1619:
	.byte $20, $b9, $00, $91, $2c, $b9, $27, $b9, $00, $f5, $25, $b9, $00, $91, $2c, $b9, $20, $b9, $00, $f5, $20, $b9, $00, $91
	.byte $25, $b9, $2c, $b9, $00, $91, $2e, $b9, $00, $a5, $2c, $b9, $00, $91, $27, $b9, $25, $b9, $00, $f5
	.byte $41, $2c
	.word @song3ref1619
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $2c
	.word @song3ref1619
	.byte $41, $2c
	.word @song3ref1619
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
@song3ref1696:
	.byte $4a, .lobyte(@env31), .hibyte(@env31)
@song3ref1699:
	.byte $20, $b9, $00, $91, $4c, $2c, $b9, $4c, $27, $b9, $00, $f5, $4c, $25, $b9, $00, $91, $4c, $2c, $b9, $4c, $20, $b9, $00
	.byte $f5, $4c, $20, $b9, $00, $91, $4c, $25, $b9, $4c, $2c, $b9, $00, $91, $4c, $2e, $b9, $00, $a5, $4c, $2c, $b9, $00, $91
	.byte $4c, $27, $b9, $4c, $25, $b9, $00, $f5, $4c
	.byte $41, $2c
	.word @song3ref1699
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
@song3ch6loop:
	.byte $4b
	.byte $41, $2c
	.word @song3ref1696
	.byte $4c
	.byte $41, $2c
	.word @song3ref1699
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song3ch6loop
