song_once_upon_a_time = 0
song_start_menu = 1
song_your_best_friend = 2
song_fallen_down = 3
song_ruins = 4
song_uwa_so_temperate = 5
song_anticipation = 6
song_unnecessary_tension = 7
song_enemy_approching = 8
song_ghost_fight = 9
song_determination = 10
song_home = 11
song_home_music_box = 12
song_heartache = 13
song_sans = 14
song_nye_heh_heh = 15
song_snowy = 16
song_uwa_so_holiday = 17
song_dogbass_todo = 18
song_mysterious_place = 19
song_dogsong = 20
song_snowdin_town = 21
song_shop = 22
song_bonetrousle_wip = 23
song_dating_start = 24
song_dating_tense = 25
song_dating_fight = 26
song_premonition = 27
song_danger_mystery = 28
song_undyne = 29
song_waterfall = 30
song_run = 31
song_quiet_water = 32
song_memory = 33
song_bird_that_carries_you_over_a_disproportionately_small_gap = 34
song_pathetic_house = 35
song_spooktune = 36
song_spookwave = 37
song_ghouliday = 38
song_chill = 39
song_tem_shop = 40
song_ngahhh = 41
song_ooo = 42
song_small_shock = 43
song_but_the_earth_refused_to_die = 44
song_battle_against_a_true_hero = 45
song_power_of_neo = 46
song_megalovania = 47
song_him = 48
song_max = 49

.if SONG_STRINGS
song_strings:
.asciiz "Once upon a time"
.asciiz "Start Menu"
.asciiz "Your Best Friend"
.asciiz "Fallen Down"
.asciiz "Ruins"
.asciiz "Uwa!! So Temperate~"
.asciiz "Anticipation"
.asciiz "Unnecessary Tension"
.asciiz "Enemy Approching"
.asciiz "Ghost Fight"
.asciiz "Determination"
.asciiz "Home"
.asciiz "Home (Music Box)"
.asciiz "Heartache"
.asciiz "sans."
.asciiz "Nye heh heh!"
.asciiz "Snowy"
.asciiz "Uwa!! So Holiday~"
.asciiz "Dogbass (TODO)"
.asciiz "Mysterious Place"
.asciiz "Dogsong"
.asciiz "Snowdin Town"
.asciiz "Shop"
.asciiz "Bonetrousle (WIP)"
.asciiz "Dating Start"
.asciiz "Dating Tense"
.asciiz "Dating Fight"
.asciiz "Premonition"
.asciiz "Danger Mystery"
.asciiz "Undyne"
.asciiz "Waterfall"
.asciiz "Run!"
.asciiz "Quiet Water"
.asciiz "Memory"
.asciiz "Bird That Carries You Over A Disproportionately Small Gap"
.asciiz "Pathetic House"
.asciiz "Spooktune"
.asciiz "Spookwave"
.asciiz "Ghouliday"
.asciiz "Chill"
.asciiz "Tem Shop"
.asciiz "NGAHHH!!"
.asciiz "Ooo"
.asciiz "Small Shock"
.asciiz "But the Earth Refused to Die"
.asciiz "Battle Against a True Hero"
.asciiz "Power of "NEO""
.asciiz "Megalovania"
.asciiz "HIM"
.endif
