; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_undertale_ost_0=music_data_undertale_ost_0
.endif

music_data_undertale_ost_0:
	.byte 8
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6 ; 00 : Once upon a time
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,@song1ch5,@song1ch6 ; 01 : Start Menu
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,@song2ch5,@song2ch6 ; 02 : Your Best Friend
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,@song3ch5,@song3ch6 ; 03 : Fallen Down
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,@song4ch5,@song4ch6 ; 04 : Ruins
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,@song5ch5,@song5ch6 ; 05 : Uwa!! So Temperate~
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,@song6ch5,@song6ch6 ; 06 : Anticipation
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,@song7ch5,@song7ch6 ; 07 : Unnecessary Tension
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_undertale_ost_0
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env9,@env14,@env0 ; 00 : Lead
	.word @env13,@env9,@env12,@env3 ; 01 : Vibrate low vol
	.word @env8,@env9,@env10,@env0 ; 02 : Lead wavy
	.word @env2,@env9,@env10,@env0 ; 03 : Kicks
	.word @env7,@env9,@env10,@env11 ; 04 : Fade
	.word @env6,@env9,@env10,@env0 ; 05 : Basic
	.word @env15,@env9,@env1,@env0 ; 06 : Flowey
	.word @env6,@env9,@env12,@env16 ; 07 : Vibrate
	.word @env18,@env9,@env10,@env3 ; 08 : Vibrate vol
	.word @env5,@env9,@env10,@env0 ; 09 : SImple

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$c0,$c1,$00,$02
@env2:
	.byte $00,$c8,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $00,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$00,$01
@env4:
	.byte $0e,$cf,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$00,$0b,$c3,$05,$c2,$06,$c1,$06,$c1,$00,$14
@env5:
	.byte $00,$cd,$cf,$ce,$cd,$00,$04
@env6:
	.byte $00,$cf,$7f,$00,$02
@env7:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env8:
	.byte $0c,$c2,$c4,$c6,$c7,$c8,$c9,$ca,$02,$c9,$00,$05,$c7,$c5,$c4,$c3,$c2,$00,$10
@env9:
	.byte $c0,$7f,$00,$01
@env10:
	.byte $7f,$00,$00
@env11:
	.byte $00,$bd,$be,$bf,$be,$bf,$c0,$00,$06
@env12:
	.byte $c2,$7f,$00,$00
@env13:
	.byte $00,$ca,$c7,$c5,$c3,$00,$04
@env14:
	.byte $c1,$7f,$00,$00
@env15:
	.byte $00,$cf,$03,$c0,$00,$03
@env16:
	.byte $00,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$00,$01
@env17:
	.byte $c0,$cc,$00,$00
@env18:
	.byte $00,$cf,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$00,$08

@samples:
	.byte $01+.lobyte(FAMISTUDIO_DPCM_PTR),$c2,$0e,$40 ; 00 cymbal (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$7e ; 01 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$00 ; 02 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$60 ; 03 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$20 ; 04 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$40 ; 05 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$10 ; 06 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$70 ; 07 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$50 ; 08 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$30 ; 09 triangle noise (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $25, $eb, $31, $eb, $47, $2c, $eb, $00, $eb, $47, $2a, $eb, $31, $eb, $47, $25, $eb, $00, $eb, $47, $25, $eb, $2a, $eb
	.byte $47, $31, $eb, $33, $eb, $47, $31, $eb, $2c, $eb, $47, $2a, $eb, $00, $eb, $47
	.byte $41, $1f
	.word @song0ref6
	.byte $d1, $7f, $4e, $01, $84, $17, $8b, $18, $89
@song0ref58:
	.byte $47, $19, $a7, $00, $8b, $7a, $19, $99, $44, $97, $7f, $25, $99, $44, $99, $22, $99, $44, $97, $47, $20, $99, $44, $99
	.byte $1e, $b3, $1d, $b5, $1e, $b3, $47, $20, $d1, $44, $97, $29, $d1, $28, $8b, $27, $89, $47, $25, $ff, $a3, $44, $b3, $47
	.byte $1b, $a7, $00, $8b, $7c, $1b, $8b, $00, $8b, $78, $1b, $8b, $00, $89, $7f, $25, $a7, $44, $8b, $22, $a7, $44, $89, $47
	.byte $20, $a7, $44, $8b, $1e, $b3, $20, $b5, $22, $b3, $47, $1d, $b5, $44, $b3, $20, $b7, $44, $b1, $47, $20, $b5, $1e, $b3
	.byte $1d, $b5, $1e, $b3
	.byte $41, $57
	.word @song0ref58
	.byte $47, $4e, $00, $88
@song0ref165:
	.byte $31, $99, $78, $31, $99, $7f, $2a, $99, $78, $2a, $97, $7f, $2c, $99, $78, $2c, $99, $7f, $2a, $99, $78, $2a, $97, $47
	.byte $7f, $24, $99, $78, $24, $99, $7f, $2a, $99, $78, $2a, $97, $7f, $2c, $99, $78, $2c, $99, $7f, $2a, $99, $78, $2a, $97
	.byte $47, $7f, $23, $99, $78, $23, $99, $7f, $2a, $99, $78, $2a, $97, $7f, $2c, $99, $78, $2c, $99, $7f, $2f, $99, $78, $2f
	.byte $97, $47, $7f, $2e, $99, $78, $2e, $99, $7f, $2c, $99, $78, $2c, $97, $7f, $2a, $99, $78, $2a, $99, $7f, $25, $99, $78
	.byte $25, $97, $47, $7f, $4e, $00
	.byte $41, $40
	.word @song0ref165
	.byte $47, $7f, $31, $99, $78, $31, $99, $7f, $2a, $99, $78, $2a, $97, $7e, $2c, $99, $77, $2c, $99, $7e, $2a, $99, $77, $2a
	.byte $97, $47, $7d, $24, $99, $77, $24, $99, $7d, $2a, $99, $77, $2a, $97, $7c, $2c, $99, $76, $2c, $99, $7c, $2a, $99, $76
	.byte $2a, $97, $47, $7b, $23, $99, $76, $23, $99, $7b, $2a, $99, $76, $2a, $97, $7a, $2c, $99, $75, $2c, $99, $7a, $2f, $99
	.byte $75, $2f, $97, $47, $79, $2e, $99, $75, $2e, $99, $79, $2c, $99, $75, $2c, $97, $78, $2a, $99, $74, $2a, $99, $78, $25
	.byte $99, $74, $25, $97, $47, $77, $31, $99, $74, $31, $99, $77, $2a, $99, $74, $2a, $97, $76, $2c, $99, $73, $2c, $99, $76
	.byte $2a, $99, $73, $2a, $97, $47, $75, $24, $99, $73, $24, $99, $75, $2a, $99, $73, $2a, $97, $74, $2c, $99, $72, $2c, $99
	.byte $74, $2a, $99, $72, $2a, $97, $47, $73, $23, $99, $72, $23, $99, $73, $2a, $99, $72, $2a, $97, $2c, $99, $00, $99, $2f
	.byte $99, $00, $97, $47, $71, $2e, $99, $00, $99, $2c, $99, $00, $b3, $7f, $d1, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $73, $80
@song0ref459:
	.byte $25, $b5, $25, $b3, $31, $b5, $31, $b3, $2c, $b5, $2c, $b3, $00, $eb, $2a, $b5, $2a, $b3, $31, $b5, $31, $b3, $25, $b5
	.byte $25, $b3, $00, $eb, $25, $b5, $25, $b3, $2a, $b5, $2a, $b3, $31, $b5, $31, $b3, $33, $b5, $33, $b3, $31, $b5, $31, $b3
	.byte $2c, $b5, $2c, $b3, $2a, $b5, $2a, $b3, $00, $eb
	.byte $41, $39
	.word @song0ref459
	.byte $df, $7f, $8b, $82
@song0ref524:
	.byte $0b, $b5, $12, $b3, $14, $b5, $12, $b3, $0b, $b5, $12, $b3, $14, $b5, $12, $b3, $0a, $b5, $12, $b3, $14, $b5, $12, $b3
	.byte $09, $b5, $12, $b3, $14, $b5, $12, $b3, $08, $b5, $12, $b3, $14, $b5, $12, $b3, $0d, $b5, $12, $b3, $14, $b5, $12, $b3
	.byte $0a, $b5, $12, $b3, $14, $b5, $12, $b3, $0f, $b5, $12, $b3, $11, $b5, $0d, $b3
	.byte $41, $40
	.word @song0ref524
@song0ref591:
	.byte $00, $ff, $d9
@song0ref594:
	.byte $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db
	.byte $ff, $db, $ff, $db, $ff, $db, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $82
@song0ref629:
	.byte $1e, $ff, $d9, $22, $ff, $d9, $21, $ff, $d9, $20, $ff, $d9, $1e, $ff, $d9, $22, $ff, $d9, $21, $ff, $d9, $20, $ff, $a3
	.byte $00, $b3
	.byte $41, $1a
	.word @song0ref629
	.byte $17, $ff, $d9, $ff, $db
@song0ref663:
	.byte $16, $ff, $d9, $15, $ff, $d9, $14, $ff, $d9, $19, $ff, $d9, $16, $ff, $d9, $1b, $eb, $19, $eb, $17, $ff, $d9, $17, $ff
	.byte $d9
	.byte $41, $13
	.word @song0ref663
	.byte $2a, $ff, $d9, $2c, $ff, $d9, $23, $ff, $d9, $2a, $ff, $d9, $2a, $ff, $d9, $2c, $ff, $d9, $23, $ff, $d9, $2a, $ff, $d9
	.byte $41, $11
	.word @song0ref591
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $1e
	.word @song0ref594
	.byte $ff, $db, $86
@song0ref728:
	.byte $04, $8b, $00, $a7, $10, $8b, $00, $a5, $0a, $8b, $00, $dd, $04, $8b, $00, $a7, $10, $8b, $00, $a5, $0a, $8b, $00, $dd
	.byte $41, $18
	.word @song0ref728
	.byte $41, $18
	.word @song0ref728
	.byte $41, $18
	.word @song0ref728
	.byte $41, $18
	.word @song0ref728
	.byte $41, $18
	.word @song0ref728
	.byte $41, $18
	.word @song0ref728
	.byte $41, $18
	.word @song0ref728
	.byte $41, $18
	.word @song0ref728
	.byte $41, $18
	.word @song0ref728
	.byte $41, $18
	.word @song0ref728
	.byte $41, $18
	.word @song0ref728
	.byte $41, $10
	.word @song0ref594
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $02, $8b, $00, $ff, $cb
	.byte $41, $1e
	.word @song0ref594
	.byte $41, $1e
	.word @song0ref594
	.byte $41, $1e
	.word @song0ref594
	.byte $ff, $db, $ff, $db, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $41, $1e
	.word @song0ref594
	.byte $41, $1e
	.word @song0ref594
	.byte $41, $1e
	.word @song0ref594
	.byte $ff, $db, $ff, $db, $ff, $db, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $41, $1e
	.word @song0ref594
	.byte $41, $1e
	.word @song0ref594
	.byte $41, $1e
	.word @song0ref594
	.byte $ff, $db, $ff, $db, $ff, $db, $42
	.word @song0ch6loop
@song1ch0:
@song1ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7f, $4e, $02, $8a
@song1ref9:
	.byte $20, $87, $00, $8b, $74, $85, $20, $87, $00, $a5, $7f, $2c, $87, $00, $8b, $74, $85, $2c, $87, $00, $91, $7f, $27, $87
	.byte $00, $8b, $74, $85, $27, $87, $00, $ff, $89, $47, $7f, $25, $87, $00, $8b, $74, $85, $25, $87, $00, $a5, $7f, $2c, $87
	.byte $00, $8b, $74, $85, $2c, $87, $00, $91, $7f, $20, $87, $00, $8b, $74, $85, $20, $87, $00, $ff, $89, $47, $7f, $20, $87
	.byte $00, $8b, $74, $85, $20, $87, $00, $a5, $7f, $25, $87, $00, $8b, $74, $85, $25, $87, $00, $91, $7f, $2c, $87, $00, $8b
	.byte $74, $85, $2c, $87, $00, $a5, $7f, $2e, $87, $00, $8b, $74, $85, $2e, $87, $00, $b9, $47, $7f, $2c, $87, $00, $8b, $74
	.byte $85, $2c, $87, $00, $a5, $7f, $27, $87, $00, $8b, $74, $85, $27, $87, $00, $91, $7f, $25, $87, $00, $8b, $74, $85, $25
	.byte $87, $00, $ff, $89, $47, $7f, $4e, $02
	.byte $41, $78
	.word @song1ref9
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
@song1ref184:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $41, $24
	.word @song1ref184
	.byte $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $00, $a5, $86
@song1ref234:
	.byte $1e, $91, $1e, $91, $00, $91, $1e, $91, $1e, $91, $1e, $91, $00, $a5, $1e, $91, $1e, $91, $00, $a5, $1e, $91, $1e, $91
	.byte $00, $a5
	.byte $41, $1a
	.word @song1ref234
@song1ref263:
	.byte $1e, $91, $1e, $91, $00, $91, $1e, $91, $1e, $91, $1e, $91, $00, $91, $1e, $91, $1e, $91, $1e, $91, $00, $91, $1e, $91
	.byte $1e, $91, $00, $91, $a7, $1e, $91, $1e, $91, $00, $91, $1e, $91, $1e, $91, $1e, $91, $00, $ff, $9d, $00, $a5
	.byte $41, $1a
	.word @song1ref234
	.byte $41, $1a
	.word @song1ref234
	.byte $41, $2e
	.word @song1ref263
	.byte $41, $1a
	.word @song1ref234
	.byte $41, $1a
	.word @song1ref234
	.byte $41, $2c
	.word @song1ref263
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $41, $24
	.word @song1ref184
	.byte $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $41, $24
	.word @song1ref184
	.byte $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
	.byte $41, $24
	.word @song1ref184
	.byte $42
	.word @song1ch6loop
@song2ch0:
@song2ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song2ref5:
	.byte $ff, $e7, $47, $ff, $e7, $47, $ff, $e7, $47, $ff, $e7, $47
	.byte $41, $08
	.word @song2ref5
	.byte $47
	.byte $41, $08
	.word @song2ref5
	.byte $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $7f, $8c
@song2ref30:
	.byte $21, $87, $00, $87, $78, $21, $87, $00, $87, $72, $21
@song2ref41:
	.byte $87, $00, $85, $7f, $25, $89, $00, $85, $78, $25, $87, $00, $87, $72, $25
@song2ref56:
	.byte $87, $00, $85, $7f, $1c, $89, $00, $85, $78, $1c, $87, $00, $87, $72, $1c
	.byte $41, $0f
	.word @song2ref41
	.byte $7f
	.byte $41, $21
	.word @song2ref30
	.byte $41, $0f
	.word @song2ref41
	.byte $7f
	.byte $41, $21
	.word @song2ref30
	.byte $41, $0f
	.word @song2ref41
	.byte $7f
	.byte $41, $21
	.word @song2ref30
	.byte $41, $0f
	.word @song2ref41
	.byte $7f
	.byte $41, $21
	.word @song2ref30
	.byte $41, $0f
	.word @song2ref41
@song2ref102:
	.byte $7f, $23, $87, $00, $87
@song2ref107:
	.byte $78, $23, $87, $00, $87, $72, $23
@song2ref114:
	.byte $87, $00, $85, $7f, $28, $89, $00, $85, $78, $28, $87, $00, $87, $72, $28
	.byte $41, $0c
	.word @song2ref56
	.byte $41, $0c
	.word @song2ref114
	.byte $87, $00, $85, $7f
	.byte $41, $21
	.word @song2ref30
	.byte $41, $0f
	.word @song2ref41
@song2ref145:
	.byte $7f, $1a, $87, $00, $87, $78, $1a, $87, $00, $87, $72, $1a, $87, $00, $85, $7f
	.byte $41, $0c
	.word @song2ref30
	.byte $7f, $23, $89, $00, $85
	.byte $41, $08
	.word @song2ref107
	.byte $7f, $34, $89, $00, $85, $78, $34, $87, $00, $87, $72, $34, $87, $00, $85, $7f
	.byte $41, $21
	.word @song2ref30
	.byte $41, $0f
	.word @song2ref41
	.byte $41, $0c
	.word @song2ref145
	.byte $41, $0c
	.word @song2ref102
@song2ref200:
	.byte $7f, $20, $87, $00, $87, $78, $20, $87, $00, $87, $72, $20, $87, $00, $85, $7f, $2c, $89, $00, $85, $78, $2c, $87, $00
	.byte $87, $72, $2c, $87, $00, $85
	.byte $41, $0c
	.word @song2ref145
	.byte $7f, $1e, $87, $00, $87, $78, $1e, $87, $00, $87, $72, $1e, $87, $00, $85, $7f, $1c, $87, $00, $87, $78, $1c, $87, $00
	.byte $87, $72, $1c, $87, $00, $85
	.byte $41, $0c
	.word @song2ref200
	.byte $7f
	.byte $41, $0c
	.word @song2ref30
	.byte $7f, $9d, $2a, $81, $2a, $81, $2c, $2c, $81, $2d, $83, $2d, $81, $2d, $81, $2d, $81, $2d, $83, $2d, $2d, $81, $00, $e1
	.byte $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
@song2ref298:
	.byte $ff, $e7, $ff, $e7, $ff, $e7, $ff, $e7, $80
@song2ref307:
	.byte $3d, $8d, $00, $a7, $3d, $9b, $3e, $99, $40, $4c, $9b, $00, $99, $3d, $9b, $00, $99, $3e, $8d, $00, $a7, $3e, $9b, $40
	.byte $4c, $99, $3b, $9b, $00, $99, $34, $9b, $00, $99
	.byte $41, $0c
	.word @song2ref307
	.byte $40, $51, $9b, $00, $99, $40, $4e, $e3, $3e, $83, $3f, $85, $40, $4c, $9b, $00, $d3
	.byte $41, $20
	.word @song2ref307
	.byte $41, $08
	.word @song2ref307
	.byte $3b, $9b, $00, $99, $38, $9b, $00, $99, $39, $d5, $40, $4f, $85, $40, $50, $83, $40, $51, $9b, $00, $e1, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $41, $08
	.word @song2ref298
	.byte $41, $08
	.word @song2ref298
	.byte $41, $08
	.word @song2ref298
	.byte $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $41, $08
	.word @song2ref298
	.byte $41, $08
	.word @song2ref298
	.byte $41, $08
	.word @song2ref298
	.byte $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $41, $08
	.word @song2ref298
	.byte $41, $08
	.word @song2ref298
	.byte $41, $08
	.word @song2ref298
	.byte $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $41, $08
	.word @song2ref298
	.byte $41, $08
	.word @song2ref298
	.byte $41, $08
	.word @song2ref298
	.byte $42
	.word @song2ch6loop
@song3ch0:
@song3ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $73, $8e
@song3ref7:
	.byte $2b, $8d, $2b, $8d, $26, $8d, $26, $8d, $2b, $8d, $2b, $8d, $26, $8d, $26, $8d, $2b, $8d, $2b, $8d, $26, $8d, $26, $8d
	.byte $47, $2b, $8d, $2b, $8d, $26, $8d, $26, $8d, $2b, $8d, $2b, $8d, $26, $8d, $26, $8d, $2b, $8d, $2b, $8d, $26, $8d, $26
	.byte $8d, $47, $24, $8d, $24, $8d, $22, $8d, $22, $8d, $26, $8d, $26, $8d, $00, $9d, $22, $8d, $22, $8d, $24, $8d, $24, $8d
	.byte $47, $29, $8d, $29, $8d, $28, $8d, $28, $8d, $29, $8d, $29, $8d, $2b, $8d, $2b, $8d, $28, $8d, $28, $8d, $24, $8d, $24
	.byte $8d, $47, $2b, $8d, $2b, $8d, $24, $8d, $24, $8d, $2b, $8d, $2b, $8d, $24, $8d, $24, $8d, $2b, $8d, $2b, $8d, $24, $8d
	.byte $24, $8d, $47, $2b, $8d, $2b, $8d, $23, $8d, $23, $8d, $2b, $8d, $2b, $8d, $24, $8d, $24, $8d, $2c, $8d, $2c, $8d, $00
	.byte $9d, $47, $2b, $8d, $2b, $8d, $27, $8d, $27, $8d, $2b, $8d, $2b, $8d, $27, $8d, $27, $8d, $29, $8d, $29, $8d, $2b, $8d
	.byte $2b, $8d, $47, $29, $8d, $29, $8d, $00, $9d, $27, $8d, $27, $8d, $00, $9d, $26, $8d, $26, $8d, $00, $9d, $47
	.byte $41, $b6
	.word @song3ref7
	.byte $47
	.byte $41, $b6
	.word @song3ref7
	.byte $47
	.byte $41, $a4
	.word @song3ref7
	.byte $47, $26, $8d, $26, $8d, $00, $9d, $2b, $8d, $2b, $8d, $00, $9d, $26, $8d, $26, $8d, $00, $9d, $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $7a
@song3ref232:
	.byte $4e, $02, $8a, $1b, $8d, $82, $1b, $8d, $8a, $1f, $8d, $82, $1f, $8d, $8a, $22, $8d, $82, $22, $8d, $8a, $1f, $8d, $82
	.byte $1f, $8d, $8a, $22, $8d, $82, $22, $8d, $8a, $1f, $8d, $82, $1f, $8d, $4e, $02, $8a, $1b, $8d, $82, $1b, $8d, $8a, $1f
	.byte $8d, $82, $1f, $8d, $8a, $22, $8d, $82, $22, $8d, $8a, $1f, $8d, $82, $1f, $8d, $8a, $22, $8d, $82, $22, $8d, $8a, $1f
	.byte $8d, $82, $1f, $8d, $8a, $18, $8d, $82, $18, $8d, $8a, $1c, $8d, $82, $1c, $8d, $8a, $1f, $8d, $82, $1f, $8d, $8a, $1c
	.byte $8d, $82, $1c, $8d, $8a, $1f, $8d, $82, $1f, $8d, $8a, $1c, $8d, $82, $1c, $8d, $8a, $18, $8d, $82, $18, $8d, $8a, $1c
	.byte $8d, $82, $1c, $8d, $8a, $1f, $8d, $82, $1f, $8d, $8a, $1c, $8d, $82, $1c, $8d, $8a, $1f, $8d, $82, $1f, $8d, $8a, $1c
	.byte $8d, $82, $1c, $8d, $8a, $14, $8d, $82, $14, $8d, $8a, $18, $8d, $82, $18, $8d, $8a, $1b, $8d, $82, $1b, $8d, $8a, $18
	.byte $8d, $82, $18, $8d, $8a, $1b, $8d, $82, $1b, $8d, $8a, $18, $8d, $82, $18, $8d, $8a, $14, $8d, $82, $14, $8d, $8a, $17
	.byte $8d, $82, $17, $8d, $8a, $1b, $8d, $82, $1b, $8d, $8a, $17, $8d, $82, $17, $8d, $8a, $1b, $8d, $82, $1b, $8d, $8a, $17
	.byte $8d, $82, $17, $8d, $4e, $02, $8a, $1b, $8d, $82, $1b, $8d, $8a, $1f, $8d, $82, $1f, $8d, $8a, $22, $8d, $82, $22, $8d
	.byte $8a, $1f, $8d, $82, $1f, $8d, $8a, $22, $8d, $82, $22, $8d, $8a, $1f, $8d, $82, $1f, $8d, $8a, $1a, $8d, $82, $1a, $8d
	.byte $8a, $1d, $8d, $82, $1d, $8d, $8a, $22, $8d, $82, $22, $8d, $8a, $1d, $8d, $82, $1d, $8d, $8a, $22, $8d, $82, $22, $8d
	.byte $8a, $1d, $8d, $82, $1d, $8d
	.byte $41, $c0
	.word @song3ref232
	.byte $41, $c0
	.word @song3ref232
	.byte $41, $c0
	.word @song3ref232
	.byte $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $8a
@song3ref540:
	.byte $37, $8d, $00, $8d, $32, $8d, $00, $8d, $37, $8d, $00, $8d, $32, $8d, $00, $8d, $37, $8d, $00, $8d, $32, $8d, $00, $8d
	.byte $37, $8d, $00, $8d, $32, $8d, $00, $8d, $37, $8d, $00, $8d, $32, $8d, $00, $8d, $37, $8d, $00, $8d, $32, $8d, $00, $8d
	.byte $30, $8d, $00, $8d, $2e, $8d, $00, $8d, $32, $8d, $00, $ad, $2e, $8d, $00, $8d, $30, $8d, $00, $8d, $35, $8d, $00, $8d
	.byte $34, $8d, $00, $8d, $35, $8d, $00, $8d, $37, $8d, $00, $8d, $34, $8d, $00, $8d, $30, $8d, $00, $8d, $37, $8d, $00, $8d
	.byte $30, $8d, $00, $8d, $37, $8d, $00, $8d, $30, $8d, $00, $8d, $37, $8d, $00, $8d, $30, $8d, $00, $8d, $37, $8d, $00, $8d
	.byte $2f, $8d, $00, $8d, $37, $8d, $00, $8d, $30, $8d, $00, $8d, $38, $8d, $00, $ad, $37, $8d, $00, $8d, $33, $8d, $00, $8d
	.byte $37, $8d, $00, $8d, $33, $8d, $00, $8d, $35, $8d, $00, $8d, $37, $8d, $00, $8d, $35, $8d, $00, $ad, $33, $8d, $00, $ad
	.byte $32, $8d, $00, $ad
	.byte $41, $ac
	.word @song3ref540
	.byte $41, $ac
	.word @song3ref540
	.byte $41, $a0
	.word @song3ref540
	.byte $32, $8d, $00, $ad, $37, $8d, $00, $ad, $32, $8d, $00, $ad, $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
@song3ref737:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $41, $20
	.word @song3ref737
	.byte $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $41, $20
	.word @song3ref737
	.byte $41, $20
	.word @song3ref737
	.byte $42
	.word @song3ch4loop
@song3ch5:
@song3ch5loop:
	.byte $41, $1f
	.word @song3ref737
	.byte $78, $8e
@song3ref791:
	.byte $0e, $bd, $43, $11, $dd, $43, $03, $c5, $43, $4f, $ab, $0f, $16, $95, $43, $0a, $fd, $43, $0e, $bd, $43, $0c, $ff, $8d
	.byte $43, $4f, $1a, $18, $13, $ad, $43, $07, $ff, $bd, $43, $08, $bd, $43, $4f, $d0, $14, $1b, $9d, $43, $0f, $dd, $bf, $43
	.byte $4f, $19, $1b, $17, $9d, $43, $0b, $dd, $43, $0a, $ff, $bd, $43, $0a, $bd, $43, $08, $bd, $43
	.byte $41, $1f
	.word @song3ref791
	.byte $43, $03, $ff, $bd, $ff, $00, $bd, $42
	.word @song3ch5loop
@song3ch6:
@song3ch6loop:
	.byte $41, $20
	.word @song3ref737
	.byte $41, $20
	.word @song3ref737
	.byte $42
	.word @song3ch6loop
@song4ch0:
@song4ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $9b, $47, $ff, $9b, $47, $ff, $9b, $47, $78, $b3, $80
	.byte $2a, $97, $2b, $97, $2a, $81, $2b, $83, $2a, $81, $2b, $83, $2a, $83, $26, $97, $47
@song4ref34:
	.byte $28, $cb, $2d, $b1, $30, $97, $47, $2d, $b1, $2f, $97, $30, $97, $32, $97, $2f, $97, $47, $30, $cb, $2f, $b1, $2d, $8b
	.byte $2b, $89, $47, $2a, $b1, $30, $97, $32, $97, $34, $97, $36, $97, $47, $30, $cb, $2f, $b1, $28, $97, $47, $2d, $b1, $2b
	.byte $b1, $2a, $b1, $47, $2b, $97, $2a, $97, $28, $97, $26, $b1, $2d, $97, $47, $28, $b1, $00, $97, $23, $97, $24, $97, $23
	.byte $97, $47, $26, $e5, $00, $b1, $47, $b3
@song4ref114:
	.byte $36, $97, $37, $97, $36, $97, $37, $97, $47, $36, $cb, $39, $cb, $47, $34, $cb, $2f, $97, $30, $97, $2f, $97, $47, $32
	.byte $e5, $00, $b1, $47, $cd, $2f, $97, $30, $97, $2f, $97, $47, $32, $e5, $00, $b1, $47, $ff, $9b, $47, $7f, $4e, $02, $90
	.byte $41, $47
	.word @song4ref34
	.byte $80
	.byte $41, $25
	.word @song4ref114
	.byte $47, $4e, $02, $90
	.byte $41, $47
	.word @song4ref34
	.byte $80
	.byte $41, $0e
	.word @song4ref114
	.byte $90, $23, $97, $24, $97, $23, $97, $47, $26, $ff, $99, $47, $00, $cb, $23, $97, $25, $97, $23, $97, $47, $26, $ff, $99
	.byte $47, $2c, $cb, $2b, $97, $29, $97, $2c, $97, $47, $24, $ff, $99, $47, $00, $b1, $23, $b1, $24, $b1, $47, $23, $cb, $24
	.byte $8b, $23, $89, $21, $97, $23, $97, $47, $2a, $e5, $26, $b1, $47, $28, $ff, $99, $47, $00, $e5, $29, $8b, $28, $89, $26
	.byte $97, $47, $28, $e5, $23, $b1, $47, $1f, $b1, $21, $b1, $23, $b1, $47, $26, $ff, $99, $47, $00, $e5, $28, $8b, $26, $89
	.byte $24, $97, $47, $26, $ff, $99, $47, $24, $ff, $99, $47, $26, $ff, $99, $47, $24, $ff, $99, $47, $2a, $ff, $99, $47, $00
	.byte $ff, $99, $47, $ff, $9b, $47, $ff, $9b, $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $78, $80
@song4ref314:
	.byte $15, $97, $1c, $97, $18, $b1, $17, $97, $18, $97, $1a, $b1, $00, $cb, $13, $97
	.byte $41, $0d
	.word @song4ref314
	.byte $e5
	.byte $41, $10
	.word @song4ref314
	.byte $41, $0d
	.word @song4ref314
	.byte $e5
	.byte $41, $10
	.word @song4ref314
	.byte $41, $0d
	.word @song4ref314
@song4ref347:
	.byte $97, $0e, $97, $13, $97, $10
@song4ref353:
	.byte $97, $15, $97, $1c, $97, $18, $b1, $17, $97, $18, $97, $1a, $b1, $0e, $97, $15, $97, $18, $97, $17
	.byte $41, $0d
	.word @song4ref353
	.byte $12, $97, $0e, $97, $10, $97, $11
	.byte $41, $0d
	.word @song4ref353
	.byte $00, $e5, $21, $97, $28, $97, $24, $b1, $23, $97, $24, $97, $26, $b1, $00, $e5
@song4ref402:
	.byte $7f
@song4ref403:
	.byte $09, $97, $10, $97, $0c, $b1, $0b, $97, $0c, $97, $0e, $b1, $00, $97, $09, $97, $07, $97, $13, $97, $09, $97, $10, $97
	.byte $0c, $b1, $0e, $97, $10, $97, $12, $b1, $00, $b1, $12, $97, $0e, $97
	.byte $41, $22
	.word @song4ref403
	.byte $09, $97, $0e, $97, $78
	.byte $41, $0d
	.word @song4ref314
	.byte $41, $13
	.word @song4ref347
	.byte $00
	.byte $41, $13
	.word @song4ref347
	.byte $00, $e5, $ff, $9b, $ff, $9b
	.byte $41, $26
	.word @song4ref402
	.byte $41, $22
	.word @song4ref403
	.byte $09, $97, $0e, $97, $78
	.byte $41, $0d
	.word @song4ref314
	.byte $41, $13
	.word @song4ref347
	.byte $00, $97, $0e, $97, $13, $97, $10, $97, $7f, $0b, $97, $12, $97, $0e, $b1, $0b, $97, $12, $97, $0b, $97, $12, $97, $17
	.byte $b1, $00, $b1, $0a, $97, $11, $97, $0e, $b1, $0a, $97, $11, $97, $0a, $97, $11, $97, $14, $b1, $13, $97, $11, $97, $09
	.byte $97, $10, $97, $0c, $b1, $09, $97, $10, $97, $09, $97, $10, $97, $15, $b1, $10, $b1, $07, $97, $0b, $97, $13, $b1, $0e
	.byte $b1, $0e, $b1, $10, $b1, $12, $b1, $05, $97, $10, $97, $0c, $cb, $10, $97, $05, $b1, $10, $b1, $15, $b1, $0b, $97, $0e
	.byte $97, $0b, $cb, $0e, $97, $0b, $b1, $0e, $b1, $10, $b1, $13, $ff, $99, $00, $ff, $99
@song4ref595:
	.byte $28, $97, $2b, $97, $2f, $97, $2b, $97, $2e, $97, $2a, $97, $28, $97, $2b, $97, $2f, $97, $2b, $97, $2e, $97, $2a, $97
	.byte $41, $18
	.word @song4ref595
	.byte $28, $97, $2f, $97, $32, $97, $2f, $97, $31, $97, $2d, $97, $28, $97, $2f, $97, $32, $97, $2f, $97, $31, $97, $2d, $97
	.byte $00, $ff, $99, $ff, $9b, $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
@song4ref655:
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $ff, $9b, $90
@song4ref684:
	.byte $1c, $cb, $21, $b1, $24, $97, $21, $b1, $23, $97, $24, $97, $26, $97, $23, $97, $24, $cb, $23, $b1, $21, $8b, $1f, $89
	.byte $1e, $b1, $24, $97, $26, $97, $28, $97, $2a, $97, $24, $cb, $23, $b1, $1c, $97, $21, $b1, $1f, $b1, $1e, $b1, $1f, $97
	.byte $1e, $97, $1c, $97, $1a, $b1, $21, $97, $1c, $b1, $00, $97, $17, $97, $18, $97, $17, $97, $1a, $e5, $00, $b1, $ff, $9b
	.byte $ff, $9b, $cd, $17, $97, $18, $97, $17, $97, $1a, $ff, $99, $00, $cb, $17, $97, $19, $97, $17, $97, $1a, $ff, $99, $20
	.byte $cb, $1f, $97, $1d, $97, $20, $97, $18, $ff, $99, $00, $b1, $17, $b1, $18, $b1, $17, $cb, $18, $8b, $17, $89, $15, $97
	.byte $17, $97, $1e, $e5, $1a, $b1, $1c, $ff, $99, $00, $e5, $1d, $8b, $1c, $89, $1a, $97, $1c, $e5, $17, $b1, $13, $b1, $15
	.byte $b1, $17, $b1, $1a, $ff, $99, $00, $e5, $1c, $8b, $1a, $89, $18, $97, $1a, $ff, $99, $18, $ff, $99, $1a, $ff, $99, $18
	.byte $ff, $99, $1e, $ff, $99, $00, $ff, $99, $ff, $9b, $ff, $9b, $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $86
@song4ref887:
	.byte $30, $8b, $00, $a3
@song4ref891:
	.byte $30, $8b, $00, $89, $29
@song4ref896:
	.byte $8b, $00, $89, $30, $8b, $00, $89, $29, $8b, $00, $89, $30, $8b, $00, $a3, $25, $8b, $00, $a3, $25, $8b, $00, $89, $29
	.byte $8b, $00, $89
	.byte $41, $18
	.word @song4ref887
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song4ref896
	.byte $41, $20
	.word @song4ref891
	.byte $41, $18
	.word @song4ref887
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song4ref896
@song4ref948:
	.byte $30, $8b, $00, $a3, $30, $8b, $00, $a3, $30, $8b, $00, $a3, $25, $8b, $00, $a3, $25, $8b, $00, $a3, $30, $8b, $00, $a3
	.byte $30, $8b, $00, $a3, $30, $8b, $00, $a3, $30, $8b, $00, $a3, $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song4ref896
	.byte $41, $29
	.word @song4ref948
	.byte $41, $0f
	.word @song4ref896
	.byte $41, $20
	.word @song4ref891
	.byte $41, $18
	.word @song4ref887
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song4ref896
	.byte $41, $20
	.word @song4ref891
	.byte $41, $18
	.word @song4ref887
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song4ref896
	.byte $41, $29
	.word @song4ref948
	.byte $8b, $00, $89, $30, $8b, $00, $89, $29, $8b, $00, $89, $7f, $2e, $8b, $00, $a3, $7c, $2e, $8b, $00, $a3, $78, $2e, $8b
	.byte $00, $89, $7f, $29, $8b, $00, $89
@song4ref1060:
	.byte $74, $2e, $8b, $00
@song4ref1064:
	.byte $d7, $7f, $29, $8b, $00, $a3
@song4ref1070:
	.byte $2e, $8b, $00, $a3, $7c, $2e, $8b, $00, $89, $7f, $29, $8b, $00, $89, $78, $2e, $8b, $00, $89, $7f, $29, $8b, $00, $89
	.byte $74, $2e, $8b, $00, $f1, $7f, $29, $8b, $00, $89
	.byte $41, $0f
	.word @song4ref1070
	.byte $a3
	.byte $41, $1f
	.word @song4ref1060
	.byte $41, $14
	.word @song4ref1064
	.byte $a3
	.byte $41, $20
	.word @song4ref1060
	.byte $7f, $2a, $8b, $00, $89, $2e, $8b, $00, $a3, $7c, $2e, $8b, $00, $89, $7f, $2a, $8b, $00, $89, $78, $2e, $8b, $00, $a3
	.byte $74, $2e, $8b, $00, $a3, $7f, $e7
	.byte $41, $0e
	.word @song4ref655
	.byte $ff, $9b, $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $41, $0e
	.word @song4ref655
	.byte $42
	.word @song4ch4loop
@song4ch5:
@song4ch5loop:
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $c1, $78, $82, $2a, $97, $2b, $97, $2a, $81, $2b, $81, $2a, $81, $2b, $85, $2a, $83, $26
	.byte $89, $8d, $28, $cb, $2d, $b1, $30, $89, $8d, $2d, $b1, $2f, $97, $30, $97, $32, $97, $2f, $89, $8d, $30, $cb, $2f, $b1
	.byte $2d, $89, $2b, $8b, $2a, $b1, $30, $97, $32, $97, $34, $97, $36, $89, $8d, $30, $cb, $2f, $b1, $28, $89, $8d, $2d, $b1
	.byte $2b, $b1, $2a, $a3, $8d, $2b, $97, $2a, $97, $28, $97, $26, $b1, $2d, $89, $8d, $28, $b1, $00, $97, $23, $97, $24, $97
	.byte $23, $89, $8d, $26, $e5, $00, $a3
@song4ref1295:
	.byte $c1, $36, $97, $37, $97, $36, $97, $37, $89, $8d, $36, $cb, $39, $bd, $8d, $34, $cb, $2f, $97, $30, $97, $2f, $89, $8d
	.byte $32, $e5, $00, $a3, $db, $2f, $97, $30, $97, $2f, $89, $2b, $b1, $2b, $b1, $00, $97, $2b, $97, $2a, $b1, $00, $e5, $7f
	.byte $41, $46
	.word @song4ref684
	.byte $41, $23
	.word @song4ref1295
	.byte $8d, $32, $e5, $00, $a3, $ff, $9b, $34, $cb, $39, $b1, $3c, $97, $39, $b1, $3b, $97, $3c, $97, $3e, $97, $3b, $97, $3c
	.byte $cb, $3b, $b1, $39, $8b, $37, $89, $36, $b1, $3c, $97, $3e, $97, $40, $4c, $97, $40, $4e, $97, $3c, $cb, $3b, $b1, $34
	.byte $97, $39, $b1, $37, $b1, $36, $b1, $37, $97, $36, $97, $34, $97, $32, $b1, $39, $97, $34, $b1, $00, $97, $2f, $97, $30
	.byte $97, $2f, $97, $32, $e5, $00, $b1
	.byte $41, $10
	.word @song4ref1295
	.byte $bd, $2f, $97, $30, $97, $2f, $97, $32, $ff, $99, $00, $cb, $2f, $97, $31, $97, $2f, $97, $32, $ff, $99, $38, $cb, $37
	.byte $97, $35, $97, $38, $97, $30, $ff, $99, $00, $b1, $2f, $b1, $30, $b1, $2f, $cb, $30, $8b, $2f, $89, $2d, $97, $2f, $97
	.byte $36, $e5, $32, $b1, $34, $ff, $99, $00, $e5, $35, $8b, $34, $89, $32, $97, $34, $e5, $2f, $b1, $2b, $b1, $2d, $b1, $2f
	.byte $b1, $32, $ff, $99, $00, $e5, $34, $8b, $32, $89, $30, $97, $32, $ff, $99, $30, $ff, $99, $32, $ff, $99, $30, $ff, $99
	.byte $80
@song4ref1528:
	.byte $10, $97, $17, $97, $13, $b1, $12, $97, $13, $97, $15, $b1, $00, $e5
	.byte $41, $0e
	.word @song4ref1528
	.byte $42
	.word @song4ch5loop
@song4ch6:
@song4ch6loop:
	.byte $78, $8d, $82
@song4ref1552:
	.byte $15, $97, $1c, $97, $18, $b1, $17, $97, $18, $89, $8d, $1a, $b1, $00, $cb, $13, $89, $8d
	.byte $41, $0e
	.word @song4ref1552
	.byte $d7, $8d
	.byte $41, $12
	.word @song4ref1552
	.byte $41, $0e
	.word @song4ref1552
	.byte $d7, $8d
	.byte $41, $12
	.word @song4ref1552
	.byte $41, $0e
	.word @song4ref1552
	.byte $97, $0e, $97, $13, $97, $10, $89, $8d
	.byte $41, $0d
	.word @song4ref1552
	.byte $0e, $97, $15, $97, $18, $97, $17, $89, $8d
	.byte $41, $0d
	.word @song4ref1552
	.byte $12, $97, $0e, $97, $10, $97, $11, $89, $8d
	.byte $41, $0e
	.word @song4ref1552
	.byte $d7, $8d, $21, $97, $28, $97, $24, $b1, $23, $97, $24, $89, $8d, $26, $b1, $00, $d7, $7f
@song4ref1642:
	.byte $8d, $09, $97, $10, $97, $0c, $b1, $0b, $97, $0c, $89, $8d, $0e, $b1, $00, $97, $09, $97, $07, $97, $13, $89, $8d, $09
	.byte $97, $10, $97, $0c, $b1, $0e, $97, $10, $89, $8d, $12, $b1, $00, $b1, $12, $97, $0e, $89
	.byte $41, $26
	.word @song4ref1642
	.byte $09, $97, $0e, $89, $8d
	.byte $41, $0e
	.word @song4ref1552
	.byte $97, $0e, $97, $13, $97, $10, $89, $8d
	.byte $41, $0e
	.word @song4ref1552
	.byte $97, $0e, $97, $13, $97, $10, $89, $8d
	.byte $41, $0e
	.word @song4ref1552
	.byte $d7, $ff, $9b, $ff, $9b
	.byte $41, $2a
	.word @song4ref1642
	.byte $41, $26
	.word @song4ref1642
	.byte $09, $97, $0e, $89, $8d
	.byte $41, $0e
	.word @song4ref1552
	.byte $97, $0e, $97, $13, $97, $10, $89, $8d
	.byte $41, $0e
	.word @song4ref1552
	.byte $97, $0e, $97, $13, $97, $10, $89, $8d, $0b, $97, $12, $97, $0e, $b1, $0b, $97, $12, $89, $8d, $0b, $97, $12, $97, $17
	.byte $b1, $00, $a3, $8d, $0a, $97, $11, $97, $0e, $b1, $0a, $97, $11, $89, $8d, $0a, $97, $11, $97, $14, $b1, $13, $97, $11
	.byte $89, $8d, $09, $97, $10, $97, $0c, $b1, $09, $97, $10, $89, $8d, $09, $97, $10, $97, $15, $b1, $10, $a3, $8d, $07, $97
	.byte $0b, $97, $13, $b1, $0e, $a3, $8d, $0e, $b1, $10, $b1, $12, $a3, $8d, $05, $97, $10, $97, $0c, $cb, $10, $89, $8d, $05
	.byte $b1, $10, $b1, $15, $a3, $8d, $0b, $97, $0e, $97, $0b, $cb, $0e, $89, $8d, $0b, $b1, $0e, $b1, $10, $a3, $8d, $13, $ff
	.byte $8b, $8d, $00, $ff, $8b
@song4ref1872:
	.byte $8d, $28, $97, $2b, $97, $2f, $97, $2b, $97, $2e, $97, $2a, $89
	.byte $41, $0d
	.word @song4ref1872
	.byte $41, $0d
	.word @song4ref1872
	.byte $41, $0d
	.word @song4ref1872
@song4ref1894:
	.byte $8d, $28, $97, $2f, $97, $32, $97, $2f, $97, $31, $97, $2d, $89
	.byte $41, $0d
	.word @song4ref1894
	.byte $8d, $10, $97, $17, $97, $13, $b1, $12, $97, $13, $89, $8d, $15, $b1, $00, $d7, $42
	.word @song4ch6loop
@song5ch0:
@song5ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $4e, $02, $90
@song5ref8:
	.byte $38, $b1, $36, $97, $38, $95, $31, $b1, $2f, $97, $31, $95, $47, $2c, $b1, $2a, $97, $2c, $95, $25, $e3, $47, $2a, $b1
	.byte $28, $97, $2a, $95, $2f, $e3, $47, $2a, $b1, $28, $97, $2a, $95, $32, $e3, $47, $4e, $02
	.byte $41, $24
	.word @song5ref8
	.byte $47, $4e, $02
	.byte $41, $24
	.word @song5ref8
	.byte $47, $4e, $02
	.byte $41, $24
	.word @song5ref8
	.byte $47, $00, $ff, $c9, $47, $ff, $cb, $47, $ff, $cb, $47, $ff, $cb, $47, $ff, $cb, $47, $ff, $cb, $47, $ff, $cb, $47, $ff
	.byte $cb, $47, $4e, $02
	.byte $41, $24
	.word @song5ref8
	.byte $47, $4e, $02
	.byte $41, $24
	.word @song5ref8
	.byte $42
	.word @song5ch0loop
@song5ch1:
@song5ch1loop:
	.byte $4e, $02, $90
@song5ref109:
	.byte $15, $b1, $19, $af, $20, $e3, $4e, $02, $15, $b1, $19, $af, $20, $e3, $13, $b1, $17, $af, $1e, $e3, $13, $b1, $17, $af
	.byte $1a, $e3, $4e, $02, $15, $b1, $19, $af, $20, $e3, $4e, $02, $15, $b1, $19, $af, $20, $e3, $18, $b1, $1c, $af, $23, $e3
	.byte $18, $b1, $1c, $af, $1f, $e3, $4e, $02
	.byte $41, $30
	.word @song5ref109
	.byte $4e, $02
	.byte $41, $30
	.word @song5ref109
	.byte $4e, $02
	.byte $41, $30
	.word @song5ref109
	.byte $42
	.word @song5ch1loop
@song5ch2:
@song5ch2loop:
	.byte $8a
@song5ref183:
	.byte $40, $50, $8b, $00, $a3, $40, $4e, $8b, $00, $89, $40, $50, $89, $00, $89, $3d, $8b, $00, $a3, $3b, $8b, $00, $89, $3d
	.byte $89, $00, $89, $38, $8b, $00, $a3, $36, $8b, $00, $89, $38, $89, $00, $89, $31, $8b, $00, $d5, $36, $8b, $00, $a3, $34
	.byte $8b, $00, $89, $36, $89, $00, $89, $3b, $8b, $00, $d5, $36, $8b, $00, $a3, $34, $8b, $00, $89, $36, $89, $00, $89, $3e
	.byte $8b, $00, $d5
	.byte $41, $48
	.word @song5ref183
	.byte $41, $48
	.word @song5ref183
	.byte $41, $48
	.word @song5ref183
@song5ref267:
	.byte $12, $a5, $00, $89, $12, $8b, $00, $89, $12, $89, $00, $89, $12, $a5, $00, $89, $0d, $a3, $00, $89, $99, $12, $a5, $00
	.byte $89, $12, $89, $00, $89, $12, $8b, $00, $89, $12, $8b, $00, $89, $12, $8b, $00, $89, $12, $89, $00, $89, $10, $a5, $00
	.byte $89, $10, $8b, $00, $89, $10, $89, $00, $89, $10, $a5, $00, $89, $0b, $a3, $00, $89, $99, $10, $a5, $00, $89, $10, $89
	.byte $00, $89, $10, $8b, $00, $89, $10, $8b, $00, $89, $10, $8b, $00, $89, $10, $89, $00, $89
	.byte $41, $2d
	.word @song5ref267
@song5ref360:
	.byte $17, $a5, $00, $89, $17, $8b, $00, $89, $17, $89, $00, $89, $17, $a5, $00, $89, $12, $a3, $00, $89, $99, $17, $a5, $00
	.byte $89, $17, $89, $00, $89, $17, $8b, $00, $89, $17, $8b, $00, $89, $17, $8b, $00, $89, $17, $89, $00, $89
	.byte $41, $5a
	.word @song5ref267
	.byte $41, $2d
	.word @song5ref267
	.byte $41, $2d
	.word @song5ref360
	.byte $42
	.word @song5ch2loop
@song5ch3:
@song5ch3loop:
@song5ref418:
	.byte $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb
	.byte $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $78, $88
@song5ref452:
	.byte $16, $b1, $7f, $86, $20, $8b, $00, $89, $1e, $89, $00, $89, $78, $88, $1a, $b1, $86, $20, $8b, $00, $89, $1e, $89, $00
	.byte $89, $b3, $7f, $20, $8b, $00, $89, $1e, $89, $00, $89, $78, $88, $1a, $97, $76, $8d, $1a, $a3, $74, $1a, $91, $00, $81
	.byte $78
	.byte $41, $26
	.word @song5ref452
	.byte $78
	.byte $41, $26
	.word @song5ref452
	.byte $78
	.byte $41, $26
	.word @song5ref452
	.byte $78
	.byte $41, $26
	.word @song5ref452
	.byte $78
	.byte $41, $26
	.word @song5ref452
	.byte $78
	.byte $41, $26
	.word @song5ref452
	.byte $78
	.byte $41, $26
	.word @song5ref452
	.byte $42
	.word @song5ch3loop
@song5ch4:
@song5ch4loop:
	.byte $41, $20
	.word @song5ref418
	.byte $41, $20
	.word @song5ref418
	.byte $42
	.word @song5ch4loop
@song5ch5:
@song5ch5loop:
	.byte $8d, $82
@song5ref544:
	.byte $38, $b1, $36, $95, $38, $97, $31, $b1, $2f, $95, $31, $89, $8d, $2c, $b1, $2a, $95, $2c, $97, $25, $d5, $8d, $2a, $b1
	.byte $28, $95, $2a, $97, $2f, $d5, $8d, $2a, $b1, $28, $95, $2a, $97, $32, $d5, $8d
	.byte $41, $28
	.word @song5ref544
	.byte $41, $28
	.word @song5ref544
	.byte $41, $28
	.word @song5ref544
	.byte $00, $ff, $bb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $ff, $cb, $8d
	.byte $41, $28
	.word @song5ref544
	.byte $41, $27
	.word @song5ref544
	.byte $42
	.word @song5ch5loop
@song5ch6:
@song5ch6loop:
	.byte $41, $20
	.word @song5ref418
	.byte $41, $20
	.word @song5ref418
	.byte $42
	.word @song5ch6loop
@song6ch0:
@song6ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song6ref5:
	.byte $ff, $9b, $47, $ff, $9b, $47, $ff, $9b, $47, $ff, $9b, $47
	.byte $41, $08
	.word @song6ref5
	.byte $42
	.word @song6ch0loop
@song6ch1:
@song6ch1loop:
@song6ref24:
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b
	.byte $41, $08
	.word @song6ref24
	.byte $42
	.word @song6ch1loop
@song6ch2:
@song6ch2loop:
	.byte $8a
@song6ref40:
	.byte $14, $85, $00, $89, $14, $83, $00, $8b
@song6ref48:
	.byte $14, $8d, $00, $81
@song6ref52:
	.byte $14, $83, $00, $89, $14, $87, $00, $87, $14
@song6ref61:
	.byte $8d, $00, $81, $14, $85, $00, $89, $14, $83, $00, $89, $81, $14, $8b, $00, $83
	.byte $41, $11
	.word @song6ref52
	.byte $41, $0a
	.word @song6ref61
@song6ref83:
	.byte $87, $81, $14, $85, $00, $89, $14, $85, $00, $89
	.byte $41, $13
	.word @song6ref48
@song6ref96:
	.byte $87, $14, $85, $00, $87, $0b, $91, $12, $91, $17, $91, $0b, $a3, $12, $91, $19, $9b, $00, $85
	.byte $41, $25
	.word @song6ref40
	.byte $41, $11
	.word @song6ref52
	.byte $41, $0a
	.word @song6ref61
	.byte $41, $0a
	.word @song6ref83
	.byte $41, $13
	.word @song6ref48
	.byte $41, $0b
	.word @song6ref96
	.byte $0d, $a3, $12, $91, $1a, $9b, $00, $85, $42
	.word @song6ch2loop
@song6ch3:
@song6ch3loop:
	.byte $88, $1f, $87, $20, $87, $21, $87, $22, $87, $43, $23, $91, $86
@song6ref158:
	.byte $21, $87, $00, $85, $14, $87, $00, $87, $21, $87, $00, $87, $14, $87, $00, $87
	.byte $41, $10
	.word @song6ref158
	.byte $41, $10
	.word @song6ref158
	.byte $41, $10
	.word @song6ref158
	.byte $41, $10
	.word @song6ref158
@song6ref186:
	.byte $21, $87, $00, $85, $18, $8d, $00, $81
@song6ref194:
	.byte $15, $83, $00, $81, $15, $83, $00, $81, $15, $83, $00, $8b, $18, $8f, $00, $91
	.byte $41, $08
	.word @song6ref194
	.byte $18, $91
	.byte $41, $10
	.word @song6ref158
	.byte $41, $10
	.word @song6ref158
	.byte $41, $10
	.word @song6ref158
	.byte $41, $10
	.word @song6ref158
	.byte $41, $10
	.word @song6ref158
	.byte $41, $10
	.word @song6ref158
	.byte $41, $18
	.word @song6ref186
@song6ref236:
	.byte $16, $83, $00, $81, $16, $83, $00, $81
	.byte $41, $08
	.word @song6ref236
	.byte $16, $83, $00, $81, $16, $81, $00, $81, $42
	.word @song6ch3loop
@song6ch4:
@song6ch4loop:
	.byte $41, $08
	.word @song6ref24
	.byte $41, $08
	.word @song6ref24
	.byte $42
	.word @song6ch4loop
@song6ch5:
@song6ch5loop:
	.byte $41, $08
	.word @song6ref24
	.byte $41, $08
	.word @song6ref24
	.byte $42
	.word @song6ch5loop
@song6ch6:
@song6ch6loop:
	.byte $41, $08
	.word @song6ref24
	.byte $41, $08
	.word @song6ref24
	.byte $42
	.word @song6ch6loop
@song7ch0:
@song7ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $92, $02, $97, $00, $89, $03, $95, $00, $c7, $0a, $95, $00
	.byte $89, $09, $95, $47, $02, $97, $00, $89, $03, $95, $00, $89, $08, $95, $09, $c7, $00, $95, $47, $04, $97, $00, $89, $05
	.byte $95, $00, $c7, $0c, $95, $00, $89, $0b, $95, $47, $04, $97, $00, $89, $05, $95, $00, $89, $0b, $df, $00, $95, $42
	.word @song7ch0loop
@song7ch1:
@song7ch1loop:
	.byte $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $42
	.word @song7ch1loop
@song7ch2:
@song7ch2loop:
	.byte $8a
@song7ref80:
	.byte $40, $56, $85, $00, $83, $3e, $83, $00, $83, $3e, $83, $00, $83, $3e, $83, $00, $83, $40, $56, $83, $00, $83, $3e, $83
	.byte $00, $83, $3e, $83, $00, $83, $3e, $83, $00, $83
	.byte $41, $20
	.word @song7ref80
	.byte $41, $20
	.word @song7ref80
	.byte $41, $20
	.word @song7ref80
@song7ref123:
	.byte $40, $58, $85, $00, $83, $40, $4c, $83, $00, $83, $40, $4c, $83, $00, $83, $40, $4c, $83, $00, $83, $40, $58, $83, $00
	.byte $83, $40, $4c, $83, $00, $83, $40, $4c, $83, $00, $83, $40, $4c, $83, $00, $83
	.byte $41, $20
	.word @song7ref123
	.byte $41, $20
	.word @song7ref123
	.byte $41, $20
	.word @song7ref123
	.byte $42
	.word @song7ch2loop
@song7ch3:
@song7ch3loop:
	.byte $88
@song7ref177:
	.byte $38
@song7ref178:
	.byte $97, $40, $4d, $83, $00, $8f, $40, $4d, $83, $00, $8f, $40, $4d, $83, $00, $8f, $3f, $87, $40, $4c, $85, $40, $4d, $85
	.byte $40, $4e, $83, $00, $83, $40, $4d, $83, $00, $9b, $40, $4d, $83, $00, $8f
	.byte $41, $17
	.word @song7ref177
	.byte $8f, $40, $4d, $83, $00, $8f, $40, $4d, $83, $00, $8f, $39
	.byte $41, $17
	.word @song7ref178
	.byte $39, $95, $00, $89, $39, $95
	.byte $41, $20
	.word @song7ref177
	.byte $42
	.word @song7ch3loop
@song7ch4:
@song7ch4loop:
	.byte $02, $85, $00, $ff, $b9, $ff, $c3, $ff, $c3, $ff, $c3, $42
	.word @song7ch4loop
@song7ch5:
@song7ch5loop:
	.byte $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $42
	.word @song7ch5loop
@song7ch6:
@song7ch6loop:
	.byte $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $42
	.word @song7ch6loop
