; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_undertale_ost_4=music_data_undertale_ost_4
.endif

music_data_undertale_ost_4:
	.byte 2
	.word @instruments
	.word @samples-5
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6 ; 00 : Undertale
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,@song1ch5,@song1ch6 ; 01 : Last Goodbye
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_undertale_ost_4
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env5,@env12,@env26,@env0 ; 00 : Lead 1
	.word @env7,@env12,@env24,@env0 ; 01 : Basic
	.word @env10,@env12,@env26,@env0 ; 02 : Music box
	.word @env27,@env12,@env26,@env3 ; 03 : Vibrate low vol
	.word @env8,@env12,@env26,@env0 ; 04 : Quick Fade
	.word @env2,@env12,@env24,@env0 ; 05 : Kicks
	.word @env11,@env12,@env24,@env0 ; 06 : Lead wavy
	.word @env9,@env12,@env24,@env25 ; 07 : Fade
	.word @env5,@env12,@env29,@env0 ; 08 : Lead
	.word @env28,@env12,@env24,@env0 ; 09 : Echo
	.word @env7,@env12,@env24,@env30 ; 0a : Vibrate
	.word @env13,@env12,@env24,@env0 ; 0b : Kicks Loud
	.word @env6,@env12,@env24,@env0 ; 0c : SImple

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c0,$bd,$bd,$c0,$c3,$c3,$00,$01
@env2:
	.byte $00,$c8,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $00,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$00,$01
@env4:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$00,$00
@env5:
	.byte $0e,$cf,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$00,$0b,$c3,$05,$c2,$06,$c1,$06,$c1,$00,$14
@env6:
	.byte $00,$cd,$cf,$ce,$cd,$00,$04
@env7:
	.byte $00,$cf,$7f,$00,$02
@env8:
	.byte $00,$cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$09
@env9:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env10:
	.byte $00,$c9,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c9,$c8,$c7,$c6,$c5,$c4,$c4,$c3,$c7,$c6,$c5,$c4,$c3,$c3,$c2,$c4,$c3,$c3,$c2,$02,$c1,$00,$1d
@env11:
	.byte $0c,$c2,$c4,$c6,$c7,$c8,$c9,$ca,$02,$c9,$00,$05,$c7,$c5,$c4,$c3,$c2,$00,$10
@env12:
	.byte $c0,$7f,$00,$01
@env13:
	.byte $00,$cf,$ca,$c8,$c6,$c4,$c2,$c1,$c0,$00,$08
@env14:
	.byte $c0,$b5,$00,$00
@env15:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$00,$00
@env16:
	.byte $c0,$b6,$00,$00
@env17:
	.byte $c0,$b7,$00,$00
@env18:
	.byte $c0,$bd,$00,$00
@env19:
	.byte $c0,$bc,$00,$00
@env20:
	.byte $c0,$b8,$00,$00
@env21:
	.byte $c0,$b9,$00,$00
@env22:
	.byte $c0,$bb,$00,$00
@env23:
	.byte $c0,$ba,$00,$00
@env24:
	.byte $7f,$00,$00
@env25:
	.byte $00,$bd,$be,$bf,$be,$bf,$c0,$00,$06
@env26:
	.byte $c2,$7f,$00,$00
@env27:
	.byte $00,$ca,$c7,$c5,$c3,$00,$04
@env28:
	.byte $00,$cf,$06,$c0,$c0,$c8,$05,$c0,$c0,$c4,$05,$c0,$c0,$c2,$04,$c0,$c1,$00,$10
@env29:
	.byte $c1,$7f,$00,$00
@env30:
	.byte $00,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$00,$01
@env31:
	.byte $c0,$cc,$00,$00
@env32:
	.byte $c0,$c0,$cc,$cc,$00,$00
@env33:
	.byte $00,$c0,$bd,$bc,$bd,$bf,$c1,$c3,$c4,$c3,$00,$01

@samples:
	.byte $68+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0d,$40,$00 ; 00 bird (Pitch:13)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$c2,$0e,$40,$02 ; 01 cymbal (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$4b,$40,$04 ; 02 elevator (Pitch:11)
	.byte $0a+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0b,$40,$04 ; 03 elevator_end (Pitch:11)
	.byte $1c+.lobyte(FAMISTUDIO_DPCM_PTR),$32,$0b,$40,$04 ; 04 elevator_start (Pitch:11)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$07,$40,$02 ; 05 impact_hit_cs6 (Pitch:7)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$08,$40,$02 ; 06 impact_hit_cs6 (Pitch:8)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$09,$40,$02 ; 07 impact_hit_cs6 (Pitch:9)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0a,$40,$02 ; 08 impact_hit_cs6 (Pitch:10)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0b,$40,$02 ; 09 impact_hit_cs6 (Pitch:11)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0c,$40,$02 ; 0a impact_hit_cs6 (Pitch:12)
	.byte $77+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0d,$40,$00 ; 53 megadrive_drumki (Pitch:13)
	.byte $77+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0e,$40,$00 ; 54 megadrive_drumki (Pitch:14)
	.byte $77+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0f,$40,$00 ; 55 megadrive_drumki (Pitch:15)
	.byte $7d+.lobyte(FAMISTUDIO_DPCM_PTR),$06,$0f,$40,$00 ; 56 megadrive_drumki 1 (Pitch:15)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$08,$40,$02 ; 0f nes_drumkit_1 (Pitch:8)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0b,$40,$02 ; 10 nes_drumkit_1 (Pitch:11)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0d,$40,$02 ; 11 nes_drumkit_1 (Pitch:13)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0f,$40,$02 ; 12 nes_drumkit_1 (Pitch:15)
	.byte $4f+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$0f,$40,$02 ; 13 nes_drumkit_2 (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$32,$0f,$40,$02 ; 14 nes_drumkit_3 (Pitch:15)
	.byte $66+.lobyte(FAMISTUDIO_DPCM_PTR),$1e,$0f,$40,$02 ; 15 nes_drumkit_4 (Pitch:15)
	.byte $6e+.lobyte(FAMISTUDIO_DPCM_PTR),$1e,$0f,$40,$02 ; 16 nes_drumkit_4_re (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$30,$00 ; 17 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$50,$00 ; 18 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$70,$00 ; 19 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$10,$00 ; 1a triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$40,$00 ; 1b triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$20,$00 ; 1c triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$60,$00 ; 1d triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$00,$00 ; 1e triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$7e,$00 ; 1f triangle noise (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $80
@song0ref6:
	.byte $17, $a1, $1e, $a1, $1c, $a1, $17, $9f, $1b, $b3, $1b, $b3, $1c, $9f, $47, $a3, $17, $a1, $1c, $a1, $17, $9f, $1b, $b3
	.byte $1b, $b3, $1c, $9f, $47, $17, $a1, $1e, $a1, $1c, $a1, $17, $9f, $1b, $b3, $1b, $b3, $1c, $9f, $47, $a3, $17, $a1, $1c
	.byte $a1, $20, $9f, $1e, $b3, $1c, $b3, $1e, $9f, $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $2a
	.word @song0ref6
	.byte $00, $ff, $f5, $47, $7a, $88
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref5
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $2a
	.word @song0ref6
	.byte $7f, $4e, $01, $8c, $34, $a1, $33, $a1, $2f, $9f, $2c, $a1, $2a, $a1, $28, $a1, $23, $9f
@song0ref154:
	.byte $47, $23, $ff, $8b, $2f, $c5, $2c, $c3, $47, $2a, $c5, $28, $c3, $27, $c5, $28, $c3, $47, $2a, $ff, $8b, $33, $e9, $32
	.byte $8f, $31, $8d, $47, $2f, $ff, $ff, $99, $47, $25, $ff, $8b, $2f, $c5, $2c, $c3, $47, $2a, $c5, $28, $c3, $2a, $c5, $2c
	.byte $c3, $47, $27, $ff, $8b, $2a, $ff, $8b, $47, $2a, $c5, $28, $c3, $27, $c5, $28, $c3
	.byte $41, $39
	.word @song0ref154
	.byte $47
	.byte $41, $36
	.word @song0ref5
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47
	.byte $41, $36
	.word @song0ref6
	.byte $47, $78, $84
@song0ref257:
	.byte $2f, $a1, $36, $a1, $34, $a1, $2f, $9f, $33, $b3, $33, $b3, $34, $9f, $47, $a3, $2f, $a1, $34, $a1, $2f, $9f, $33, $b3
	.byte $33, $b3, $34, $9f, $47, $2f, $a1, $36, $a1, $34, $a1, $2f, $9f, $33, $b3, $33, $b3, $34, $9f, $47, $a3, $2f, $a1, $34
	.byte $a1, $38, $9f, $36, $b3, $34, $b3, $36, $9f, $47
	.byte $41, $36
	.word @song0ref257
	.byte $47
	.byte $41, $36
	.word @song0ref257
	.byte $47
	.byte $41, $36
	.word @song0ref257
	.byte $47, $8c
@song0ref328:
	.byte $18, $8f, $00, $8f, $1f
@song0ref333:
	.byte $8f, $00, $8f, $1d, $8f, $00, $8f, $18, $8f, $00, $8d, $1c, $8f, $00, $a1, $1c, $8f, $00, $a1, $1d, $8f, $00, $8d, $47
	.byte $a3, $18
	.byte $41, $17
	.word @song0ref333
	.byte $47
	.byte $41, $1e
	.word @song0ref328
@song0ref366:
	.byte $8f, $00, $8f, $1d, $8f, $00, $8f, $21, $8f, $00, $8d, $1f, $8f, $00, $a1, $1d, $8f, $00, $a1, $1f, $8f, $00, $8d, $47
	.byte $41, $1e
	.word @song0ref328
	.byte $41, $17
	.word @song0ref333
	.byte $47
	.byte $41, $1e
	.word @song0ref328
	.byte $41, $17
	.word @song0ref366
	.byte $47
	.byte $41, $1e
	.word @song0ref328
	.byte $41, $17
	.word @song0ref333
	.byte $47
	.byte $41, $1e
	.word @song0ref328
	.byte $41, $17
	.word @song0ref366
	.byte $47
	.byte $41, $1e
	.word @song0ref328
	.byte $41, $17
	.word @song0ref333
	.byte $47
	.byte $41, $1e
	.word @song0ref328
	.byte $41, $17
	.word @song0ref366
	.byte $47, $84
@song0ref433:
	.byte $30, $a1, $37, $a1, $35, $a1, $30, $9f, $34, $b3, $34, $b3, $35, $9f, $47, $a3, $30, $a1, $35, $a1, $30, $9f, $34, $b3
	.byte $34, $b3, $35, $9f, $47, $30, $a1, $37, $a1, $35, $a1, $30, $9f, $34, $b3, $34, $b3, $35, $9f, $47, $a3, $30, $a1, $35
	.byte $a1, $39, $9f, $37, $b3, $35, $b3, $37, $9f, $47
	.byte $41, $36
	.word @song0ref433
	.byte $47, $91, $74, $37, $b3, $72, $37, $e7, $71, $e9, $47, $00, $ff, $ff, $99, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref513:
	.byte $ff
@song0ref514:
	.byte $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b
	.byte $41, $18
	.word @song0ref513
	.byte $7f, $84
@song0ref542:
	.byte $23, $b3, $78, $23, $d5, $7f, $2f, $b3, $78, $2f, $d5, $7f, $2a, $b3, $78, $2a, $b3, $74, $2a, $ff, $ad, $7f, $28, $b3
	.byte $78, $28, $d5, $7f, $2f, $b3, $78, $2f, $d5, $7f, $23, $b3, $78, $23, $b3, $74, $23, $ff, $ad, $7f, $23, $b3, $78, $23
	.byte $d5, $7f, $27, $b3, $78, $27, $d5, $7f, $2f, $b3, $78, $2f, $b3, $74, $2f, $e7, $7f, $31, $b3, $78, $31, $8d, $7f, $2f
	.byte $b3, $78, $2f, $b3, $74, $2f, $9f, $7f, $2a, $b3, $78, $2a, $b3, $74, $2a, $9f, $7f, $28, $b3, $78, $28, $b3, $74, $28
	.byte $ff, $ad, $7f
	.byte $41, $43
	.word @song0ref542
	.byte $7f
	.byte $41, $3d
	.word @song0ref542
	.byte $a1, $34, $a1, $33, $a1, $2f, $9f, $2c, $a1, $2a, $a1, $28, $a1, $23, $9f
	.byte $41, $43
	.word @song0ref542
	.byte $7f
	.byte $41, $43
	.word @song0ref542
	.byte $7f
	.byte $41, $43
	.word @song0ref542
	.byte $7f
	.byte $41, $41
	.word @song0ref542
	.byte $b1, $00, $f9, $78, $90
@song0ref683:
	.byte $09, $ff, $ff, $99, $ff, $ff, $9b, $0b, $ff, $ff, $99, $10, $ff, $ff, $99, $09, $ff, $ff, $99, $ff, $ff, $9b, $0b, $ff
	.byte $ff, $99, $0d, $ff, $8b, $0b, $ff, $8b
	.byte $41, $20
	.word @song0ref683
	.byte $7f, $4e, $01, $8c
@song0ref722:
	.byte $23, $ff, $8b, $2f, $ff, $8b, $2a, $ff, $d3, $44, $c3, $28, $ff, $8b, $2f, $ff, $8b, $23, $ff, $d3, $44, $c3, $23, $ff
	.byte $8b, $27, $ff, $8b, $2f, $ff, $8b, $44, $c5, $31, $c3, $2f, $ff, $8b, $2a, $ff, $8b, $28, $ff, $8b, $44, $c5, $00, $c3
	.byte $4e, $01
	.byte $41, $30
	.word @song0ref722
	.byte $4e, $01
	.byte $41, $30
	.word @song0ref722
	.byte $4e, $01
	.byte $41, $30
	.word @song0ref722
	.byte $90
@song0ref786:
	.byte $1c, $c5, $00, $c3, $1c, $c5, $00, $c3, $17, $c5, $00, $c3, $14, $c5, $15, $c3, $17, $c5, $00, $c3, $17, $c5, $15, $c3
	.byte $14, $c5, $00, $c3, $1c, $c5, $1e, $c3, $1c, $c5, $00, $c3, $1c, $c5, $20, $c3, $1e, $c5, $00, $c3, $1c, $c5, $1e, $c3
	.byte $17, $c5, $23, $c3, $1e, $c5, $1c, $c3, $1c, $c5, $00, $ff, $d1
	.byte $41, $3d
	.word @song0ref786
	.byte $8c
@song0ref851:
	.byte $24, $ff, $8b, $30, $ff, $8b, $2b, $ff, $d3, $44, $c3, $29, $ff, $8b, $30, $ff, $8b, $29, $ff, $8b, $44, $c5, $00, $c3
	.byte $24, $ff, $8b, $28, $ff, $8b, $30, $ff, $8b, $44, $c5, $32, $c3, $30, $ff, $8b, $2b, $ff, $8b, $29, $ff, $8b, $44, $c5
	.byte $00, $c3
	.byte $41, $32
	.word @song0ref851
	.byte $41, $18
	.word @song0ref513
	.byte $ff, $ff, $9b, $ff, $ff, $9b, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $41, $18
	.word @song0ref513
	.byte $82
@song0ref921:
	.byte $15, $a1, $00, $a1, $15
@song0ref926:
	.byte $a1, $00, $9f, $15, $a1, $00, $a1, $15, $a1, $00, $9f
@song0ref937:
	.byte $15, $a1, $00, $a1, $15, $a1, $00, $9f
@song0ref945:
	.byte $15, $a1, $00, $a1, $15, $a1, $00, $9f
@song0ref953:
	.byte $14, $a1, $00, $a1, $14, $a1, $00, $9f, $14, $a1, $00, $a1, $14, $a1, $00, $9f, $14, $a1, $00, $a1, $14, $a1, $00, $9f
	.byte $14, $a1, $00, $a1, $14
	.byte $41, $1b
	.word @song0ref926
@song0ref985:
	.byte $15, $a1, $00, $a1, $15, $a1, $00, $9f, $17, $a1, $00, $a1, $17, $a1, $00, $9f, $17, $a1, $00, $a1, $17, $a1, $00, $9f
	.byte $19, $a1, $00, $a1, $19, $a1, $00, $9f, $19, $a1, $00, $a1, $19
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref945
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref985
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref945
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref985
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref945
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $1b
	.word @song0ref985
	.byte $ff, $f5
	.byte $41, $3d
	.word @song0ref921
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref985
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref945
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref985
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref945
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref985
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $25
	.word @song0ref945
	.byte $41, $1b
	.word @song0ref926
	.byte $41, $18
	.word @song0ref985
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $ff, $ff, $9b, $15, $a1, $00, $a1, $15, $a1, $00, $9f
	.byte $41, $18
	.word @song0ref985
@song0ref1125:
	.byte $14, $a1, $00, $a1, $14, $a1, $00, $9f, $14, $a1, $00, $a1, $14, $a1, $00, $9f, $19, $a1, $00, $a1, $19, $a1, $00, $9f
	.byte $19, $a1, $00, $a1, $19, $a1, $00, $9f, $15, $a1, $00, $a1, $15, $a1, $00, $9f
	.byte $41, $18
	.word @song0ref985
	.byte $41, $28
	.word @song0ref1125
	.byte $41, $18
	.word @song0ref985
	.byte $41, $28
	.word @song0ref1125
	.byte $41, $18
	.word @song0ref985
	.byte $41, $28
	.word @song0ref1125
	.byte $41, $18
	.word @song0ref985
	.byte $41, $28
	.word @song0ref1125
	.byte $41, $18
	.word @song0ref985
	.byte $41, $28
	.word @song0ref1125
	.byte $41, $18
	.word @song0ref985
	.byte $41, $28
	.word @song0ref1125
	.byte $41, $18
	.word @song0ref985
	.byte $41, $28
	.word @song0ref1125
	.byte $41, $18
	.word @song0ref985
	.byte $41, $28
	.word @song0ref1125
	.byte $41, $18
	.word @song0ref985
	.byte $41, $28
	.word @song0ref1125
	.byte $41, $18
	.word @song0ref985
	.byte $41, $28
	.word @song0ref1125
	.byte $41, $18
	.word @song0ref985
	.byte $41, $20
	.word @song0ref1125
@song0ref1231:
	.byte $16, $a1, $00, $a1, $16, $a1, $00, $9f, $16, $a1, $00, $a1, $16, $a1, $00, $9f, $18, $a1, $00, $a1, $18, $a1, $00, $9f
	.byte $18, $a1, $00, $a1, $18, $a1, $00, $9f, $15, $a1, $00, $a1, $15, $a1, $00, $9f, $15, $a1, $00, $a1, $15, $a1, $00, $9f
	.byte $1a, $a1, $00, $a1, $1a, $a1, $00, $9f, $1a, $a1, $00, $a1, $1a, $a1, $00, $9f
	.byte $41, $40
	.word @song0ref1231
	.byte $41, $40
	.word @song0ref1231
	.byte $41, $40
	.word @song0ref1231
	.byte $41, $18
	.word @song0ref513
	.byte $ff, $ff, $9b, $ff, $ff, $9b, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $8a
@song0ref1333:
	.byte $01, $8f, $00, $8f, $01, $8f, $00, $8f
@song0ref1341:
	.byte $01, $8f, $00, $8f, $01, $8f, $00, $8d, $01, $8f, $00, $8f, $01, $8f, $00, $8f, $01, $8f, $02, $8f, $01, $8f, $00, $8d
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $41, $20
	.word @song0ref1333
	.byte $7f, $8e, $04, $a1, $74, $04, $a1, $7f, $8a
	.byte $41, $18
	.word @song0ref1341
@song0ref1422:
	.byte $7c, $8e, $40, $09, $a1, $76, $40, $09, $a1, $73, $40, $09, $a1, $7f, $8a, $01, $8f, $00, $8d, $01, $8f, $00, $8f, $01
	.byte $8f, $00, $8f, $01, $8f, $02, $8f, $01, $8f, $00, $8d, $8e, $04, $a1, $74, $04, $a1, $7f, $8a
	.byte $41, $18
	.word @song0ref1341
	.byte $41, $1e
	.word @song0ref1422
	.byte $7f, $8a
	.byte $41, $18
	.word @song0ref1341
	.byte $41, $1e
	.word @song0ref1422
	.byte $7f, $8a
	.byte $41, $18
	.word @song0ref1341
	.byte $41, $1e
	.word @song0ref1422
	.byte $7f, $8a
	.byte $41, $18
	.word @song0ref1341
	.byte $41, $1e
	.word @song0ref1422
	.byte $7f, $8a
	.byte $41, $18
	.word @song0ref1341
	.byte $41, $1e
	.word @song0ref1422
	.byte $7f, $8a
	.byte $41, $18
	.word @song0ref1341
	.byte $41, $1e
	.word @song0ref1422
	.byte $7f, $8a
	.byte $41, $18
	.word @song0ref1341
	.byte $c7, $70, $50, $03, $f0, $82, $03, $ff, $c1, $8f, $00, $ff, $ff, $99
	.byte $41, $18
	.word @song0ref513
	.byte $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $c7, $70, $50, $03, $f0, $03
	.byte $ff, $c1, $8f
@song0ref1560:
	.byte $8e
@song0ref1561:
	.byte $40, $08, $a1, $8a
@song0ref1565:
	.byte $40, $0b, $8f, $40, $0b, $8f, $01, $8f, $40, $08, $87, $40, $08, $85, $40, $0b, $8f, $40, $0b, $8d, $8e, $01, $a1, $8a
	.byte $40, $0b, $8f, $78, $8e, $01, $a1, $7f, $8a, $40, $0b, $8f, $74, $8e, $01, $8f, $7f, $8f, $8a, $40, $0b, $8f, $40, $08
	.byte $8f, $40, $0b, $8f, $40, $0b, $8f, $01, $8f, $40, $0b, $8f, $40, $0b, $8f, $40, $0b, $8d, $8e, $40, $07, $a1, $8a, $40
	.byte $0b, $8f, $78, $8e, $40, $07, $a1, $7f, $8a, $40, $0b, $8f, $74, $8e, $40, $07, $8f, $7f, $8f, $8a, $40, $0b, $8f, $40
	.byte $08, $8f
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $34
	.word @song0ref1565
	.byte $41, $3a
	.word @song0ref1561
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $29
	.word @song0ref1565
	.byte $82, $03, $ff, $8b
	.byte $41, $3a
	.word @song0ref1560
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $38
	.word @song0ref1565
	.byte $41, $34
	.word @song0ref1565
	.byte $00, $ff, $ff, $99
	.byte $41, $18
	.word @song0ref513
	.byte $ff, $ff, $9b, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $ff, $ff, $9b, $ff, $ff, $9b, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $7f, $84
@song0ref1861:
	.byte $17, $b3, $78, $17, $d5, $7f, $23, $b3, $78, $23, $d5, $7f, $1e, $b3, $78, $1e, $b3, $74, $1e, $ff, $ad, $7f, $1c, $b3
	.byte $78, $1c, $d5, $7f, $23, $b3, $78, $23, $d5, $7f, $17, $b3, $78, $17, $b3, $74, $17, $ff, $ad, $7f, $17, $b3, $78, $17
	.byte $d5, $7f, $1b, $b3, $78, $1b, $d5, $7f, $23, $b3, $78, $23, $b3, $74, $23, $e7, $7f, $25, $b3, $78, $25, $8d, $7f, $23
	.byte $b3, $78, $23, $b3, $74, $23, $9f, $7f, $1e, $b3, $78, $1e, $b3, $74, $1e, $9f, $7f, $1c, $b3, $78, $1c, $b3, $74, $1c
	.byte $ff, $ad, $7f
	.byte $41, $43
	.word @song0ref1861
	.byte $7f
	.byte $41, $43
	.word @song0ref1861
	.byte $7f
	.byte $41, $41
	.word @song0ref1861
	.byte $b1, $00, $f9
	.byte $41, $18
	.word @song0ref513
	.byte $78, $4e, $01, $8c
@song0ref1981:
	.byte $19, $c5, $15, $a1, $00, $9f, $19, $c5, $15, $a1, $00, $9f, $4e, $01, $19, $c5, $15, $a1, $00, $9f, $19, $c5, $15, $a1
	.byte $00, $9f, $1b, $c5, $17, $c3, $1b, $c5, $17, $c3, $1c, $c5, $17, $c3, $1c, $c5, $17, $c3, $4e, $01
	.byte $41, $1b
	.word @song0ref1981
	.byte $a1, $00, $9f, $1b, $c5, $17, $a1, $00, $9f, $1c, $c5, $19, $c3, $1b, $c5, $17, $c3, $7f
@song0ref2046:
	.byte $4e, $01, $00, $ff, $8b, $28, $ff, $8b, $23, $ff, $d3, $44, $c3, $23, $ff, $8b, $27, $ff, $8b, $28, $ff, $d3, $44, $c3
	.byte $2a, $ff, $8b, $2c, $ff, $8b, $23, $ff, $8b, $44, $c5, $25, $c3, $23, $ff, $8b, $1e, $ff, $8b, $1c, $ff, $8b, $44, $c5
	.byte $00, $c3
	.byte $41, $30
	.word @song0ref2046
	.byte $41, $30
	.word @song0ref2046
	.byte $41, $30
	.word @song0ref2046
	.byte $90
@song0ref2106:
	.byte $04, $c5, $00, $ff, $d1, $0b, $c5, $00, $c3, $08, $c5, $09, $c3, $0b, $c5, $00, $c3, $0b, $c5, $09, $c3, $08, $c5, $00
	.byte $c3, $10, $c5, $12, $c3, $10, $c5, $00, $c3, $14, $c5, $15, $c3, $17, $c5, $00, $c3, $14, $c5, $15, $c3, $0b, $c5, $14
	.byte $c3, $0d, $c5, $09, $c3, $0d, $c5, $00, $ff, $d1
	.byte $41, $3a
	.word @song0ref2106
	.byte $ff, $8d, $8c
@song0ref2170:
	.byte $29, $ff, $8b, $28, $ff, $d3, $44, $c3, $00, $ff, $8b, $28, $ff, $8b, $00, $ff, $ff, $99, $ff, $ff, $9b, $28, $ff, $8d
	.byte $44, $c3, $26, $c3, $24, $ff, $8b, $00, $ff, $8b, $1d, $ff, $8b, $44, $c5, $00, $c3, $ff, $8d
	.byte $41, $2a
	.word @song0ref2170
	.byte $41, $17
	.word @song0ref514
	.byte $ff, $ff, $9b, $ff, $ff, $9b, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
	.byte $41, $18
	.word @song0ref513
@song0ref2238:
	.byte $86
@song0ref2239:
	.byte $19, $ff, $ff, $99, $ff, $ff, $9b, $17, $ff, $ff, $99, $ff, $ff, $9b, $19, $ff, $ff, $99, $ff, $ff, $9b, $17, $ff, $ff
	.byte $99, $19, $ff, $ff, $99
	.byte $41, $19
	.word @song0ref2239
	.byte $43, $17, $44, $8d, $00, $ff, $ff, $87, $78, $4e, $02, $8c, $15, $a1, $00, $a1, $15, $a1, $00, $9f, $15, $a1, $00, $a1
	.byte $15, $a1, $00, $9f, $4e, $02
	.byte $41, $2d
	.word @song0ref937
	.byte $a1, $00, $9f, $4e, $02, $15, $a1, $00, $a1, $15, $a1, $00, $9f, $15, $a1, $00, $a1, $15, $a1, $00, $9f, $4e, $02, $15
	.byte $a1, $00, $a1, $15, $a1, $00, $9f
	.byte $41, $25
	.word @song0ref985
	.byte $a1, $00, $9f, $4e, $02
	.byte $41, $18
	.word @song0ref921
	.byte $7f, $84, $36, $a1, $38, $a1, $36, $a1, $34, $9f, $78, $8c
	.byte $41, $18
	.word @song0ref953
	.byte $7f, $84, $27, $a1, $28, $a1, $2c, $a1, $31, $9f, $2f, $a1, $78, $a3, $8c, $15, $a1, $00, $9f, $7f, $84, $36, $b3, $78
	.byte $36, $d5, $7f, $34, $b3, $78, $34, $b3, $00, $9f, $7f, $34, $a1, $33, $a1, $34, $a1, $36, $9f, $38, $ff, $8b, $8c, $17
	.byte $a1, $00, $a1, $17, $a1, $84, $34, $9f, $c7, $8c, $19, $a1, $00, $9f, $19, $a1, $00, $a1, $19, $a1, $00, $9f
	.byte $41, $1d
	.word @song0ref2238
	.byte $19, $ff, $ff, $99, $ff, $8d, $84, $36, $a1, $38, $a1, $36, $a1, $34, $9f, $86, $17, $ff, $ff, $99, $ff, $8d, $84, $27
	.byte $a1, $28, $a1, $2c, $a1, $31, $9f, $2f, $c5, $00, $c3, $36, $b3, $78, $36, $d5, $7f, $34, $b3, $78, $34, $b3, $00, $9f
	.byte $7f, $34, $a1, $33, $a1, $34, $a1, $36, $9f, $38, $ff, $8b, $00, $e9, $34, $9f, $c7, $00, $ff, $d1
	.byte $41, $18
	.word @song0ref513
	.byte $78, $4e, $01, $8c
@song0ref2509:
	.byte $1c, $c5, $00, $c3, $1c, $c5, $00, $c3, $1b, $c5, $00, $c3, $1b, $c5, $00, $c3, $1e, $c5, $00, $c3, $1e, $c5, $00, $c3
	.byte $20, $c5, $00, $c3, $20, $c5, $00, $c3, $4e, $01
	.byte $41, $1c
	.word @song0ref2509
	.byte $1e, $c5, $00, $c3, $7f, $4e, $01, $00, $ff, $ff, $99, $27, $ff, $d3, $44, $c3, $00, $ff, $ff, $99, $ff, $ff, $9b, $1e
	.byte $ff, $8b, $20, $ff, $8b, $27, $ff, $8b, $44, $c5, $00, $c3, $27, $ff, $8b, $23, $ff, $8b, $20, $ff, $8b, $44, $c5, $00
	.byte $c3, $4e, $01, $00, $ff, $ff, $99, $27, $ff, $8b, $84, $2f, $c5, $31, $c3, $00, $ff, $ff, $99, $2c, $ff, $8b, $2c, $a1
	.byte $2d, $a1, $2c, $a1, $2a, $9f, $8c, $1e, $ff, $8b, $20, $ff, $8b, $27, $ff, $8b, $84, $2f
@song0ref2636:
	.byte $c5, $31, $c3, $8c, $27, $ff, $8b, $23, $ff, $8b, $20, $a1, $84, $34, $a1, $33, $a1, $2f, $9f, $2c, $a1, $2a, $a1, $28
	.byte $a1, $23, $9f, $4e, $01, $00, $ff, $ff, $99, $8c, $27, $ff, $8b, $84, $23, $c5, $25, $a1, $00, $9f, $ff, $ff, $9b, $a3
	.byte $2c, $a1, $33, $a1, $34, $9f, $38, $a1, $36, $a1, $34, $a1, $2f, $9f, $8c, $1e, $ff, $8b, $20, $ff, $8b, $27, $ff, $8b
	.byte $84, $27
	.byte $41, $42
	.word @song0ref2636
	.byte $41, $19
	.word @song0ref2636
	.byte $00, $ff, $ff, $99, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $90
@song0ref2730:
	.byte $14, $c5, $00, $c3, $19, $c5, $19, $c3, $1b, $c5, $00, $c3, $19, $c5, $17, $c3, $14, $c5, $20, $c3, $17, $c5, $10, $c3
	.byte $10, $c5, $00, $ff, $d1, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b, $ff, $ff, $9b
	.byte $41, $21
	.word @song0ref2730
	.byte $8d, $84
@song0ref2776:
	.byte $24, $c5, $29, $c3, $00, $ff, $ff, $99, $a3, $2d, $a1, $34, $a1, $35, $9f, $39, $a1, $37, $a1, $35, $a1, $30, $9f, $00
	.byte $ff, $ff, $99, $ff, $8d, $2b, $c5, $2d, $c3, $2b, $c5, $29, $c3, $28, $c5, $24, $c3, $00, $a1, $35, $a1, $34, $a1, $30
	.byte $9f, $2d, $a1, $2b, $a1, $29, $a1, $24, $9f, $00, $ff, $ff, $99, $ff, $8d
	.byte $41, $3e
	.word @song0ref2776
	.byte $41, $17
	.word @song0ref514
	.byte $ff, $ff, $9b, $42
	.word @song0ch6loop
@song1ch0:
	.byte $70, $50, $02, $f0, $4e, $02, $92, $2b, $91, $1f, $91, $2b, $91, $1f, $91, $2b, $91, $1f, $91, $2b, $91, $1f, $91, $47
	.byte $4e, $02, $2b, $91, $1f, $91, $2b, $91, $1f, $91, $2b, $91, $1f, $91, $2b, $91, $1f, $91, $47, $94
@song1ref45:
	.byte $1f, $cd, $2b, $a5, $28, $a5, $47, $26, $a5, $24, $a5, $23, $91, $24, $91, $00, $91, $26, $91, $47, $cf, $2f, $b9, $2d
	.byte $87, $2c, $87, $47, $2b, $f5, $50, $f4, $00, $a7, $47, $7f, $21, $cd, $2b, $a5, $28, $a5, $47, $26, $a5, $24, $a5, $26
	.byte $91, $28, $91, $00, $91, $23, $91, $47, $cf, $26, $cd, $47, $26, $a5, $24, $a5, $23, $a5, $24, $a5, $47
	.byte $41, $1c
	.word @song1ref45
	.byte $47, $7f, $4e, $01, $21, $cd, $2b, $a5, $28, $a5, $47, $26, $a5, $24, $a5, $26, $91, $28, $91, $00, $91, $29, $91, $47
	.byte $a7, $28, $a5, $26, $91, $24, $91, $00, $91, $24, $91, $47, $f7, $50, $f4, $00, $a7, $47, $7f, $80, $1f, $cd, $2b, $cd
	.byte $47, $26, $ff, $9d, $47, $24, $cd, $2b, $a5, $2d, $91, $2b, $91, $47, $00, $91, $28, $91, $00, $91, $26, $a5, $28, $87
	.byte $26, $87, $24
@song1ref192:
	.byte $a5, $47, $24, $91, $00, $91, $24, $91, $26, $91, $28, $a5, $24, $a5, $47, $26, $91, $00, $91, $26, $91, $28, $91, $26
	.byte $91, $28, $87, $26, $87, $24, $a5, $47, $27, $a5, $26, $a5, $22, $a5, $26, $a5, $47, $4a, .lobyte(@env31), .hibyte(@env31)
	.byte $24, $cd, $4c, $26, $cd, $47, $00, $91, $4a, .lobyte(@env12), .hibyte(@env12), $4b, $1f, $91, $24, $91, $26, $91, $00
	.byte $91, $1f, $91, $24, $91, $26, $91, $47, $00, $91, $20, $91, $24, $91, $26, $91, $00, $91, $20, $91, $24, $91, $26, $91
	.byte $47, $2d, $a5, $28, $a5, $26, $91, $24, $91, $00, $91, $26, $91, $47, $93, $28, $87, $26, $87, $24, $a5, $1f, $a5, $21
	.byte $41, $29
	.word @song1ref192
	.byte $47, $7d, $4a, .lobyte(@env12), .hibyte(@env12), $4b, $2b, $a5, $44, $a5, $00, $37, $a5, $34, $a3, $47, $32, $a5, $30
	.byte $a5, $2f, $a5, $30, $a5, $47, $2b, $cd, $00, $3c, $a5, $3b, $a3, $47, $81, $37, $cb, $2b, $a5, $30, $a5, $47, $00, $35
	.byte $a3, $34, $a5, $30, $a5, $2b, $a5, $47, $00, $35, $a3, $34, $a5, $30, $a5, $2b, $a5, $47, $32, $cd, $34, $cd, $47, $2b
	.byte $f5, $2b, $a5, $47, $2b, $cd, $00, $37, $a3, $32, $87, $34, $9b, $47, $32, $a5, $30, $a5, $2f, $a5, $30, $a5, $47, $81
	.byte $32, $cb, $3b, $cd, $47, $37, $cd, $2b, $cd, $47, $00, $35, $a3, $34, $a5, $30, $a5, $2b, $a5, $47, $35, $a5, $34, $a5
	.byte $30, $a5, $2b, $91, $32, $91, $47, $30, $cd, $2b, $a5, $24, $a5, $47, $2b, $cd, $1f, $cd, $47, $7f
@song1ref441:
	.byte $2b, $a5, $24, $a5, $26, $a5, $24, $a5, $47, $1f, $91, $24, $91, $00, $91, $26, $a5, $28, $87, $26, $87, $24, $a5, $47
	.byte $1f, $a5, $24, $a5, $26, $91, $29, $91, $00, $91, $28, $91, $47, $93, $29, $87, $28, $87, $26, $a5, $24, $a5, $1f, $a5
	.byte $47
	.byte $41, $16
	.word @song1ref441
@song1ref493:
	.byte $47, $4a, .lobyte(@env32), .hibyte(@env32), $1f, $a5, $4a, .lobyte(@env18), .hibyte(@env18), $24, $a5, $4a, .lobyte(@env32)
	.byte .hibyte(@env32), $24, $91, $4a, .lobyte(@env14), .hibyte(@env14), $2f, $91, $00, $91, $4a, .lobyte(@env18), .hibyte(@env18)
	.byte $2b, $91, $47, $00, $91, $4a, .lobyte(@env19), .hibyte(@env19), $28, $91, $4a, .lobyte(@env18), .hibyte(@env18), $26
	.byte $91, $4c, $24, $a5, $4c, $26, $91, $4c, $24, $91, $4c, $1f, $91, $47, $4a, .lobyte(@env12), .hibyte(@env12), $4b
	.byte $41, $2d
	.word @song1ref441
	.byte $47
	.byte $41, $16
	.word @song1ref441
	.byte $41, $1a
	.word @song1ref493
	.byte $47, $4a, .lobyte(@env12), .hibyte(@env12), $4b, $2b, $91, $28, $91, $29, $91, $28, $91, $2b, $91, $28, $91, $29, $91
	.byte $28, $91, $47, $2d, $91, $28, $91, $29, $91, $28, $91, $2d, $91, $28, $91, $29, $91, $28, $91, $47, $30, $91, $29, $91
	.byte $2b, $91, $29, $91, $30, $91, $29, $91, $2b, $91, $29, $91, $47, $32, $91, $29, $91, $2b, $91, $2d, $91, $30, $91, $35
	.byte $91, $34, $91, $32, $91, $47, $30, $91, $2b, $91, $37, $91, $2b, $91, $34, $91, $2b, $91, $30, $91, $2b, $91, $47, $32
	.byte $91, $2b, $91, $37, $91, $2b, $91, $32, $91, $2b, $91, $2f, $91, $2b, $91, $47, $2d, $91, $29, $91, $2d, $91, $30, $91
	.byte $32, $91, $35, $91, $34, $91, $30, $91, $47, $32, $91, $2c, $91, $2d, $91, $28, $91, $29, $91, $28, $91, $26, $91, $23
	.byte $91, $47, $24, $cd, $2b, $cd, $47, $28, $cd, $24, $cd, $47, $26, $cd, $28, $cd, $47, $26, $cd, $24, $cd, $47, $7c, $4a
	.byte .lobyte(@env31), .hibyte(@env31), $1f, $91, $4c, $1f, $91, $00, $91, $4c, $1f, $91, $4c, $1f, $91, $00, $91, $4c, $1f
	.byte $91, $4c, $1f, $91, $47, $00, $91, $4c, $1f, $91, $4c, $1f, $91, $00, $91, $4c, $1f, $91, $00, $91, $4c, $1f, $91, $00
	.byte $91, $47, $4a, .lobyte(@env12), .hibyte(@env12), $4b, $2b, $91, $00, $a5, $2b, $91, $00, $a5, $2b, $91, $00, $91, $47
	.byte $93, $2b, $91, $00, $a5, $2b, $91, $00, $91, $2b, $91, $00, $91, $47, $7f, $8c, $1d, $bf, $1c, $bd, $18, $a7, $47, $93
	.byte $00, $81, $1d, $c5, $1c, $ad, $18, $ad, $47, $50, $fe, $70, $ff, $ef, $47, $7f, $80, $2b, $bb, $44, $ff, $b7, $47, $2b
	.byte $b9, $44, $ff, $b1, $47, $00, $ff, $ff, $e5, $47, $2b, $b7, $44, $ff, $ff, $ef, $47, $29, $b7, $44, $ff, $ff, $ab, $47
	.byte $50, $ff, $00, $29, $b5, $44, $ff, $ff, $ff, $ff, $85
@song1ch0loop:
	.byte $4b, $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $00, $ff, $ff, $ff, $ff, $bd, $42
	.word @song1ch0loop
@song1ch1:
	.byte $9d, $70, $50, $01, $80, $4e, $02, $92, $2b, $91, $1f, $91, $2b, $91, $1f, $91, $2b, $91, $1f, $91, $2b, $87, $89, $1f
	.byte $91, $4e, $02, $2b, $91, $1f, $91, $2b, $91, $1f, $91, $2b, $91, $1f, $91, $2b, $87, $7c, $4e, $01, $8c
@song1ref928:
	.byte $13, $cd, $1f, $a5, $1c, $a5, $1a, $a5, $18, $a5, $17, $91, $18, $91, $00, $91, $1a, $91, $cf, $23, $b9, $21, $87, $20
	.byte $87, $1f, $f5, $7f, $50, $f4, $00, $a7, $7c, $4e, $01, $15, $cd, $1f, $a5, $1c, $a5, $1a, $a5, $18, $a5, $1a, $91, $1c
	.byte $91, $00, $91, $17, $91, $cf, $1a, $cd, $1a, $a5, $18, $a5, $17, $a5, $18, $a5, $4e, $01
	.byte $41, $2c
	.word @song1ref928
	.byte $1d, $91, $a7, $1c, $a5, $1a, $91, $18, $91, $00, $91, $18, $91, $f7, $50, $f6, $00, $a7, $7f, $48, .lobyte(@env33)
	.byte .hibyte(@env33), $4e, $01, $98, $13, $cd, $1f, $cd, $1a, $ff, $9d, $18, $cd, $1f, $a5, $21, $91, $1f, $91, $00, $91
	.byte $1c, $91, $00, $91, $1a, $a5, $1c, $87, $1a, $87, $18
@song1ref1050:
	.byte $a5, $18, $91, $00, $91, $18, $91, $1a, $91, $1c, $a5, $18, $a5, $1a, $91, $00, $91, $1a, $91, $1c, $91, $1a, $91, $1c
	.byte $87, $1a, $87, $18, $a5, $1b, $a5, $1a, $a5, $16, $a5, $1a, $a5, $18, $cd, $1a, $cd, $00, $91, $13, $91, $18, $91, $1a
	.byte $91, $00, $91, $13, $91, $18, $91, $1a, $91, $00, $91, $14, $91, $18, $91, $1a, $91, $00, $91, $14, $91, $18, $91, $1a
	.byte $91, $21, $a5, $1c, $a5, $1a, $91, $18, $91, $00, $91, $1a, $91, $93, $1c, $87, $1a, $87, $18, $a5, $13, $a5, $15
	.byte $41, $29
	.word @song1ref1050
	.byte $7d, $48, .lobyte(@env0), .hibyte(@env0), $49, $80, $1d, $a5, $44, $f5, $1f, $a5, $44, $a5, $1a, $a5, $13, $a5, $1c
	.byte $a5, $21, $a5, $44, $a5, $1c, $a5, $10, $a5, $1c, $a5, $44, $a5, $10, $a5, $18, $a5, $44, $a5, $1d, $a5, $44, $a5, $1d
	.byte $a5, $44, $a5, $1a, $a5, $1f, $a5, $1c, $a5, $21, $a5, $44, $cd, $1c, $a5, $44, $a5, $1c, $a5, $44, $a5, $18, $a5, $1d
	.byte $a5, $44, $cd, $1d, $a5, $44, $a5, $1f, $a5, $44, $a5, $1c, $a5, $21, $a5, $44, $cd, $21, $a5, $44, $cd, $1d, $a5, $1a
	.byte $a5, $44, $f5, $1d, $a5, $44, $cd, $1f, $a5, $1c, $a5, $21, $f5, $00, $ff, $9d, $7f, $4e, $01, $98
@song1ref1259:
	.byte $1f, $a5, $18, $a5, $1a, $a5, $18, $a5, $13, $91, $18, $91, $00, $91, $1a, $a5, $1c, $87, $1a, $87, $18, $a5, $13, $a5
	.byte $18, $a5, $1a, $91, $1d, $91, $00, $91, $1c, $91, $93, $1d, $87, $1c, $87, $1a, $a5, $18, $a5, $13, $a5, $4e, $01
	.byte $41, $16
	.word @song1ref1259
@song1ref1309:
	.byte $1f, $a5, $18, $a5, $24, $91, $23, $91, $00, $91, $1f, $91, $00, $91, $1c, $91, $1a, $91, $18, $a5, $1a, $91, $18, $91
	.byte $13, $91, $4e, $01
	.byte $41, $2d
	.word @song1ref1259
	.byte $4e, $01
	.byte $41, $16
	.word @song1ref1259
	.byte $41, $1a
	.word @song1ref1309
	.byte $1f, $91, $1c, $91, $1d, $91, $1c, $91, $1f, $91, $1c, $91, $1d, $91, $1c, $91, $21, $91, $1c, $91, $1d, $91, $1c, $91
	.byte $21, $91, $1c, $91, $1d, $91, $1c, $91, $24, $91, $1d, $91, $1f, $91, $1d, $91, $24, $91, $1d, $91, $1f, $91, $1d, $91
	.byte $26, $91, $1d, $91, $1f, $91, $21, $91, $24, $91, $29, $91, $28, $91, $26, $91, $24, $91, $1f, $91, $2b, $91, $1f, $91
	.byte $28, $91, $1f, $91, $24, $91, $1f, $91, $26, $91, $1f, $91, $2b, $91, $1f, $91, $26, $91, $1f, $91, $23, $91, $1f, $91
	.byte $21, $91, $1d, $91, $21, $91, $24, $91, $26, $91, $29, $91, $28, $91, $24, $91, $26, $91, $20, $91, $21, $91, $1c, $91
	.byte $1d, $91, $1c, $91, $1a, $91, $17, $91, $18, $cd, $1f, $cd, $1c, $cd, $18, $cd, $1a, $cd, $1c, $cd, $1a, $cd, $18, $cd
	.byte $7c, $80, $26, $91, $26, $91, $00, $91, $26, $91, $26, $91, $00, $91, $26, $91, $26, $91, $00, $91, $26, $91, $26, $91
	.byte $00, $91, $26, $91, $00, $91, $26, $91, $00, $91, $26, $91, $00, $a5, $26, $91, $00, $a5, $26, $91, $00, $91, $93, $26
	.byte $91, $00, $a5, $26, $91, $00, $91, $26, $91, $00, $91, $ff, $ab, $ff, $bf, $7f, $2b, $b9, $44, $b9, $37, $b9, $44, $b9
	.byte $32, $bb, $44, $ff, $b7, $30, $b9, $44, $b9, $37, $b9, $44, $b9, $2b, $d7, $44, $ff, $ff, $8b, $32, $e9, $44, $ff, $ff
	.byte $bd, $30, $d9, $44, $ff, $ff, $89, $50, $ff, $00, $30, $d7, $44, $ff, $ff, $ff, $e3
@song1ch1loop:
	.byte $ff, $ff, $c7, $00, $ff, $f5, $42
	.word @song1ch1loop
@song1ch2:
	.byte $ff, $9f, $ff, $9f, $82
@song1ref1620:
	.byte $11
@song1ref1621:
	.byte $87, $00, $87, $11, $87, $00, $87, $11, $87, $00, $87, $11, $87, $00, $87, $11, $87, $00, $87, $11, $87, $00, $87
	.byte $41, $18
	.word @song1ref1620
@song1ref1647:
	.byte $11, $87, $00, $87, $11, $87, $00, $87, $11, $87, $00, $87, $13, $87, $00, $87, $10, $87, $00, $87, $10, $87, $00, $87
	.byte $10, $87, $00, $87, $10, $87, $00, $87, $10, $87, $00, $87, $10, $87, $00, $87, $10, $87, $00, $87, $10, $87, $00, $87
	.byte $0f, $87, $00, $87, $0f, $87, $00, $87, $0f, $87, $00, $87, $0f, $87, $00, $87, $0f, $87, $00, $87, $0f, $87, $00, $87
	.byte $0f, $87, $00, $87, $11, $87, $00, $87, $0e, $87, $00, $87, $0e, $87, $00, $87, $0e, $87, $00, $87, $0e, $87, $00, $87
	.byte $0e, $87, $00, $87, $0e, $87, $00, $87, $0e, $87, $00, $87, $0e, $87, $00, $87, $13, $87, $00, $87, $13, $87, $00, $87
	.byte $13, $87, $00, $87, $13, $87
@song1ref1773:
	.byte $00, $87, $13, $87, $00, $87, $13, $87, $00, $87, $13, $87, $00, $87, $13, $87, $00, $87, $14, $87, $00, $87, $14, $87
	.byte $00, $87, $14, $87, $00, $87, $14, $87, $00, $87, $14, $87, $00, $87, $14, $87, $00, $87, $14, $87, $00, $87, $14, $87
	.byte $00, $87, $15, $87, $00, $87, $15, $87, $00, $87, $10, $87, $00, $87, $10, $87, $00, $87, $13, $87, $00, $87, $13, $87
	.byte $00, $87, $0e, $87, $00, $87, $0e
	.byte $41, $17
	.word @song1ref1621
	.byte $41, $18
	.word @song1ref1620
	.byte $11, $87, $00, $87
	.byte $41, $51
	.word @song1ref1647
	.byte $9b, $00, $af, $0e, $9b, $00, $87, $18, $9b, $00, $87, $17, $9b, $00, $87, $15, $9b
	.byte $41, $33
	.word @song1ref1773
	.byte $9b, $00, $87, $1c, $9b, $00, $87, $1a, $9b, $00, $87, $13, $9b, $00, $87
@song1ref1900:
	.byte $09
@song1ref1901:
	.byte $8d, $00, $81, $09, $8d, $00, $81, $09, $8d, $00, $81, $15, $8d, $00, $81, $09, $8d, $00, $81, $09, $8d, $00, $81, $15
	.byte $8d, $00, $81, $09, $8d, $00, $81, $14, $8d, $00, $81, $08, $8d, $00, $81, $08, $8d, $00, $81, $14, $8d, $00, $81, $08
	.byte $8d, $00, $81, $08, $8d, $00, $81, $14, $8d, $00, $81, $08, $8d, $00, $81
@song1ref1964:
	.byte $13, $8d, $00, $81, $07, $8d, $00, $81, $07, $8d, $00, $81, $13, $8d, $00, $81, $07, $8d, $00, $81, $07, $8d, $00, $81
	.byte $13, $8d, $00, $81, $07, $8d, $00, $81, $12, $8d, $00, $81, $06, $8d, $00, $81, $06, $8d, $00, $81, $12, $8d, $00, $81
	.byte $06, $8d, $00, $81, $06, $8d, $00, $81, $12, $8d, $00, $81, $06, $8d, $00, $81
@song1ref2028:
	.byte $11, $8d, $00, $81, $05, $8d, $00, $81, $05, $8d, $00, $81, $11, $8d, $00, $81, $05, $8d, $00, $81, $05, $8d, $00, $81
	.byte $11, $8d, $00, $81, $05, $8d, $00, $81, $10, $8d, $00, $81, $04, $8d, $00, $81, $04, $8d, $00, $81, $10, $8d, $00, $81
	.byte $04, $8d, $00, $81, $04, $8d, $00, $81, $10, $8d, $00, $81, $04, $8d, $00, $81, $0f, $8d, $00, $81, $03, $8d, $00, $81
	.byte $03, $8d, $00, $81, $0f, $8d, $00, $81, $03, $8d, $00, $81, $03, $8d, $00, $81, $0f, $8d, $00, $81, $03, $8d, $00, $81
	.byte $0e, $b5, $00, $81, $0e, $8d, $00, $81, $13, $c9, $00, $81
	.byte $41, $ec
	.word @song1ref1900
@song1ref2139:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $20
	.word @song1ref1900
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $41, $20
	.word @song1ref1900
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $41, $20
	.word @song1ref1900
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $41, $20
	.word @song1ref1900
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $41, $20
	.word @song1ref1900
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $41, $20
	.word @song1ref1900
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
@song1ref2233:
	.byte $0e, $91, $0e, $91, $00, $91, $0e, $91, $0e, $91, $00, $91, $0e, $91, $0e, $91, $00, $91, $0e, $91, $0e, $91, $00, $91
	.byte $0e, $91, $00, $91, $0e, $91, $00, $91, $07, $b9, $0c, $b9, $13, $a5, $93, $0e, $a5, $00, $91, $0c, $a5, $07, $a5, $00
	.byte $ff, $a9
@song1ref2283:
	.byte $ff, $bf, $ff, $ef, $ff, $f7, $ff, $ef, $ff, $ff, $e7, $ff, $ff, $ff, $ab, $ff, $ff, $e7, $ff, $ff, $ff, $ff, $bf
@song1ch2loop:
	.byte $ff, $ff, $ff, $ff, $bf, $42
	.word @song1ch2loop
@song1ch3:
	.byte $ff, $9f, $ff, $9f, $8e, $40, $0c, $91, $8a
@song1ref2324:
	.byte $03, $87, $00, $87, $96, $40, $04, $87, $00, $87, $8a, $40, $0c
@song1ref2337:
	.byte $87, $00, $87, $40, $0c, $87, $00, $87, $03, $87, $00, $87, $96, $40, $04, $87, $00, $87, $8a, $40, $0c, $87, $00, $87
	.byte $40, $0c, $87, $00, $87
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $1c
	.word @song1ref2324
	.byte $8e, $01, $a5, $8a, $40, $0a, $87, $00, $9b, $8e, $01, $91, $8a, $40, $01, $87, $00, $87, $40, $02, $87, $00, $87, $40
	.byte $03
@song1ref2397:
	.byte $87, $00, $87, $8e, $01, $91, $8a, $01, $87, $00, $87, $40, $0a, $87, $00, $87, $01, $87, $00, $87, $01, $87, $00, $87
	.byte $01, $87, $00, $87, $40, $0a, $87, $00, $87, $01
	.byte $41, $17
	.word @song1ref2337
	.byte $41, $20
	.word @song1ref2324
	.byte $03, $87, $00, $87, $96, $40, $04, $87, $00, $87, $8a, $40, $0c, $87, $00, $87, $8e, $01, $a5, $8a, $40, $0a, $87, $00
	.byte $9b, $8e, $01, $91, $8a, $40, $03, $87, $00, $87, $40, $02, $87, $00, $87, $40, $01
	.byte $41, $1e
	.word @song1ref2397
	.byte $41, $17
	.word @song1ref2337
	.byte $41, $20
	.word @song1ref2324
	.byte $03, $87, $00, $87, $96, $40, $04, $87, $00, $87, $8a, $40, $0c, $87, $00, $87, $8e, $01, $a5, $8a, $40, $0a, $87, $00
	.byte $9b, $8e, $01, $91, $8a, $40, $01, $87, $00, $87, $40, $02, $87, $00, $87, $40, $03, $87, $00, $87, $40, $0c, $87, $00
	.byte $87, $03, $87, $00, $87, $40, $04, $87, $00, $9b, $8e, $40, $0b, $a5, $40, $0c, $a5, $01, $91, $8a, $40, $0c, $87, $00
	.byte $87, $40, $04, $87, $00, $9b, $40, $0c, $87, $00, $87, $03, $87, $00, $9b, $8e, $01, $91, $8a, $40, $0c, $87, $00, $87
	.byte $41, $1c
	.word @song1ref2324
	.byte $8e, $01, $a5, $96, $40, $04, $87, $00, $9b, $40, $03, $87, $00, $87, $40, $02, $87, $00, $87, $40, $01, $87, $00, $87
	.byte $40, $01, $87, $00, $87, $8a, $40, $0c, $87, $00, $87
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $1c
	.word @song1ref2324
	.byte $41, $1e
	.word @song1ref2139
	.byte $d9, $40, $01, $87, $00, $87, $40, $01, $87, $00, $87, $96, $04, $87, $00, $87, $04, $87, $8a, $40, $0c, $87, $00, $87
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $20
	.word @song1ref2324
	.byte $41, $1c
	.word @song1ref2324
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $ab
	.byte $41, $17
	.word @song1ref2283
@song1ch3loop:
	.byte $ff, $ff, $ff, $ff, $bf, $42
	.word @song1ch3loop
@song1ch4:
	.byte $ff, $9f, $ff, $9f
@song1ref2802:
	.byte $a7, $51, $00, $15, $91, $51, $80, $00, $b9, $51, $00, $15, $91, $51, $80, $00, $91, $a7, $51, $00, $15, $91, $51, $80
	.byte $00, $b9, $51, $00, $15, $91, $51, $80, $00, $91, $a7, $51, $00, $15, $91, $51, $80, $00, $b9, $51, $00, $15, $91, $51
	.byte $80, $00, $91, $a7, $15, $91, $00, $e1
	.byte $41, $20
	.word @song1ref2802
	.byte $41, $20
	.word @song1ref2802
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
@song1ref2872:
	.byte $a7, $51, $00, $16, $91, $51, $80, $00, $b9, $51, $00, $16, $91, $51, $80, $00, $91, $a7, $51, $00, $16, $91, $51, $80
	.byte $00, $b9, $51, $00, $16, $91, $51, $80, $00, $91, $a7, $51, $00, $16, $91, $51, $80, $00, $b9, $51, $00, $16, $91, $51
	.byte $80, $00, $91
	.byte $41, $1b
	.word @song1ref2872
	.byte $41, $1b
	.word @song1ref2872
	.byte $41, $1b
	.word @song1ref2872
	.byte $41, $1b
	.word @song1ref2872
	.byte $a7, $51, $00, $16, $91, $51, $80, $00, $b9, $51, $00, $16, $91, $51, $80, $00, $91
	.byte $41, $20
	.word @song1ref2139
	.byte $41, $1b
	.word @song1ref2872
	.byte $41, $1b
	.word @song1ref2872
	.byte $41, $1b
	.word @song1ref2872
	.byte $41, $1b
	.word @song1ref2872
	.byte $41, $1b
	.word @song1ref2872
	.byte $41, $1b
	.word @song1ref2872
	.byte $41, $1b
	.word @song1ref2872
	.byte $41, $1b
	.word @song1ref2872
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $51, $c0, $ff, $9f, $ff, $9f, $51, $80, $ff, $9f, $ff, $9f, $ff, $ab
	.byte $41, $17
	.word @song1ref2283
@song1ch4loop:
	.byte $ff, $ff, $ff, $ff, $bf, $42
	.word @song1ch4loop
@song1ch5:
	.byte $ff, $9f, $ff, $9f, $00, $87, $78
@song1ref3020:
	.byte $4e, $02, $94, $1f, $cd, $2b, $a5, $28, $9b, $89, $26, $a5, $24, $a5, $23, $91, $24, $91, $00, $91, $26, $87, $d9, $2f
	.byte $b9, $2d, $87, $2c, $87, $2b, $f5, $50, $f7, $00, $9d, $78, $4e, $01, $8c, $11, $cd, $1c, $a5, $18, $a5, $17, $a5, $15
	.byte $a5, $17, $91, $18, $91, $00, $91, $14, $91, $cf, $17, $cd, $17, $a5, $15, $a5, $13, $a5, $10, $a5, $00, $87
	.byte $41, $1d
	.word @song1ref3020
	.byte $78, $48, .lobyte(@env1), .hibyte(@env1), $4e, $01, $1d, $cd, $28, $a5, $24, $a5, $23, $a5, $21, $a5, $23, $91, $24
	.byte $91, $00, $91, $26, $91, $a7, $24, $a5, $23, $91, $21, $91, $00, $91, $21, $91, $a7, $28, $91, $00, $91, $26, $91, $24
	.byte $91, $21, $91, $1f, $91, $48, .lobyte(@env0), .hibyte(@env0), $49, $4e, $02, $82, $15
	.byte $41, $eb
	.word @song1ref1901
	.byte $48, .lobyte(@env0), .hibyte(@env0), $49, $4e, $02, $15
	.byte $41, $eb
	.word @song1ref1901
	.byte $7d, $80, $24, $a5, $44, $a5, $30, $a5, $2b, $a5, $2b, $a5, $2b, $a5, $2b, $a5, $2b, $a5, $00, $cd, $34, $a5, $32, $a5
	.byte $2f, $cd, $44, $cd, $2d, $a5, $44, $f5, $30, $a5, $44, $f5, $2b, $cd, $2b, $cd, $00, $ff, $9d, $cf, $30, $a5, $00, $a5
	.byte $ff, $9f, $2b, $cd, $32, $cd, $30, $cd, $00, $cd, $ff, $9f, $ff, $9f, $2b, $cd, $00, $cd, $24, $cd, $00, $cd, $78, $48
	.byte .lobyte(@env0), .hibyte(@env0), $49, $4e, $02, $82, $15
	.byte $41, $1f
	.word @song1ref1901
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $48, .lobyte(@env0), .hibyte(@env0), $49, $4e, $02, $15
	.byte $41, $1f
	.word @song1ref1901
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $48, .lobyte(@env0), .hibyte(@env0), $49, $4e, $02, $15
	.byte $41, $1f
	.word @song1ref1901
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $48, .lobyte(@env0), .hibyte(@env0), $49, $4e, $02, $15
	.byte $41, $1f
	.word @song1ref1901
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $48, .lobyte(@env0), .hibyte(@env0), $49, $4e, $02, $15
	.byte $41, $1f
	.word @song1ref1901
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $48, .lobyte(@env0), .hibyte(@env0), $49, $4e, $02, $15
	.byte $41, $1f
	.word @song1ref1901
	.byte $41, $20
	.word @song1ref1964
	.byte $41, $40
	.word @song1ref2028
	.byte $7f, $80, $09, $ff, $9d, $f7, $00, $87, $09, $87, $0b, $87, $0c, $87, $0e, $ff, $9d, $f7, $44, $a5, $7c, $4a, .lobyte(@env31)
	.byte .hibyte(@env31), $07, $91, $4c, $07, $91, $00, $91, $4c, $07, $91, $4c, $07, $91, $00, $91, $4c, $07, $91, $4c, $07
	.byte $91, $00, $91, $4c, $07, $91, $4c, $07, $91, $00, $91, $4c, $07, $91, $00, $91, $4c, $07, $91, $00, $91, $4a, .lobyte(@env12)
	.byte .hibyte(@env12), $4b, $1f, $91, $00, $a5, $1f, $91, $00, $a5, $1f, $91, $00, $91, $93, $1f, $91, $00, $a5, $1f, $91
	.byte $00, $91, $1f, $91, $00, $91, $8b, $78, $8c, $11, $bd, $10, $bf, $0c, $9b, $9d, $00, $83, $11, $c5, $10, $ad, $0c, $a1
	.byte $8f, $50, $ff, $00, $ff, $df, $ff, $b1, $00, $c3, $7f, $ff, $ef, $ff, $ff, $e7, $ff, $ff, $ff, $ab, $ff, $ff, $e7, $ff
	.byte $ff, $ff, $ff, $bf
@song1ch5loop:
	.byte $4b, $ff, $ff, $ff, $ff, $bf, $42
	.word @song1ch5loop
@song1ch6:
	.byte $ff, $9f, $ff, $9f, $78, $82
@song1ref3486:
	.byte $05
@song1ref3487:
	.byte $87, $00, $87, $05, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00, $87
	.byte $41, $18
	.word @song1ref3486
@song1ref3513:
	.byte $05, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00, $87, $07, $87, $00, $87, $04, $87, $00, $87, $04, $87, $00, $87
	.byte $04, $87, $00, $87, $04, $87, $00, $87, $04, $87, $00, $87, $04, $87, $00, $87, $04, $87, $00, $87, $04, $87, $00, $87
	.byte $03, $87, $00, $87, $03, $87, $00, $87, $03, $87, $00, $87, $03, $87, $00, $87, $03, $87, $00, $87, $03, $87, $00, $87
	.byte $03, $87, $00, $87, $05, $87, $00, $87, $02, $87, $00, $87, $02, $87, $00, $87, $02, $87, $00, $87, $02, $87, $00, $87
	.byte $02, $87, $00, $87, $02, $87, $00, $87, $02, $87, $00, $87, $02, $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87
	.byte $07, $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87, $07, $87, $00, $87
	.byte $08, $87, $00, $87, $08, $87, $00, $87, $08, $87, $00, $87, $08, $87, $00, $87, $08, $87, $00, $87, $08, $87, $00, $87
	.byte $08, $87, $00, $87, $08, $87, $00, $87, $09, $87, $00, $87, $09, $87, $00, $87, $04, $87, $00, $87, $04, $87, $00, $87
	.byte $07, $87, $00, $87, $07, $87, $00, $87, $02, $87, $00, $87, $02
	.byte $41, $17
	.word @song1ref3487
	.byte $41, $18
	.word @song1ref3486
	.byte $05, $87, $00, $87
	.byte $41, $50
	.word @song1ref3513
	.byte $4e, $01, $8c, $11, $cd, $1c, $a5, $18, $a5, $17, $a5, $15, $a5, $17, $91, $18, $91, $00, $91, $1a, $91, $a7, $18, $a5
	.byte $17, $91, $15, $91, $00, $91, $15, $91, $f7, $50, $f9, $00, $a7, $78, $4e, $02, $94
@song1ref3772:
	.byte $15, $ff, $9d, $14, $ff, $9d, $4e, $02, $13, $ff, $9d, $12, $ff, $9d, $11, $ff, $9d, $10, $ff, $9d, $0f, $ff, $9d, $0e
	.byte $cd, $13, $cd, $4e, $02
	.byte $41, $19
	.word @song1ref3772
	.byte $00, $ff, $9d, $ff, $9f, $7d, $80, $15, $a5, $44, $cd, $00, $a5, $ff, $9f, $11, $a5, $44, $f5, $13, $a5, $44, $f5, $15
	.byte $a5, $44, $f5, $10, $a5, $44, $a5, $00, $cd, $11, $a5, $44, $f5, $13, $a5, $44, $a5, $00, $cd, $15, $a5, $44, $f5, $17
	.byte $a5, $44, $cd, $00, $a5, $0e, $a5, $44, $f5, $13, $a5, $44, $f5, $15, $a5, $44, $f5, $ff, $9f, $78, $4e, $02, $94
@song1ref3875:
	.byte $15, $ff, $9d, $4e, $02, $13, $ff, $9d, $11, $ff, $9d, $10, $ff, $9d, $4e, $02, $15, $ff, $9d, $4e, $02, $13, $ff, $9d
	.byte $11, $ff, $9d, $10, $ff, $9d, $4e, $02
	.byte $41, $18
	.word @song1ref3875
	.byte $00, $ff, $9d
	.byte $41, $16
	.word @song1ref2139
	.byte $7c, $80
	.byte $41, $20
	.word @song1ref2233
	.byte $90, $1f, $b9, $24, $b9, $2b, $a5, $93, $26, $a5, $00, $91, $24, $a5, $1f, $a5, $80, $07, $bf, $0c, $bd, $13, $a7, $93
	.byte $00, $81, $0e, $ad, $00, $95, $0c, $ad, $07, $ad, $7f, $18, $b9, $44, $ff, $b1, $17, $bb, $44, $ff, $b7, $16, $b9, $44
	.byte $ff, $b1, $15, $b7, $44, $ff, $ff, $ab, $0f, $b7, $44, $ff, $ff, $ef, $0e, $b7, $44, $ff, $ff, $ab, $50, $ff, $00, $0d
	.byte $b5, $44, $ff, $ff, $ff, $ff, $85
@song1ch6loop:
	.byte $00, $ff, $ff, $ff, $ff, $bd, $42
	.word @song1ch6loop
