song_ = 0
song_once_upon_a_time = 1
song_start_menu = 2
song_your_best_friend = 3
song_fallen_down = 4
song_ruins = 5
song_uwa_so_temperate = 6
song_anticipation = 7
song_unnecessary_tension = 8
song_enemy_approching = 9
song_ghost_fight = 10
song_determination = 11
song_home = 12
song_home_music_box = 13
song_heartache = 14
song_sans = 15
song_nye_heh_heh = 16
song_snowy = 17
song_uwa_so_holiday = 18
song_dogbass = 19
song_mysterious_place = 20
song_dogsong = 21
song_snowdin_town = 22
song_shop = 23
song_bonetrousle = 24
song_dating_start = 25
song_dating_tense = 26
song_dating_fight = 27
song_premonition = 28
song_danger_mystery = 29
song_undyne = 30
song_waterfall = 31
song_run = 32
song_quiet_water = 33
song_memory = 34
song_bird_that_carries_you_over_a_disproportionately_small_gap = 35
song_dummy = 36
song_pathetic_house = 37
song_spooktune = 38
song_spookwave = 39
song_ghouliday = 40
song_chill = 41
song_thundersnail = 42
song_temmie_village = 43
song_tem_shop = 44
song_ngahhh = 45
song_spear_of_justice = 46
song_ooo = 47
song_alphys = 48
song_its_showtime = 49
song_metal_crusher = 50
song_another_medium = 51
song_uwa_so_heats = 52
song_stronger_monster_wip = 53
song_hotel = 54
song_can_you_really_call_this_a_hotel_i_didnt_receive_a_mint_on_my_pillow_or_anything = 55
song_confession = 56
song_live_report = 57
song_death_report = 58
song_wrong_enemy_ = 59
song_oh_one_true_love = 60
song_oh_dungeon = 61
song_spider_dance_wip = 62
song_its_raining_somewhere_else = 63
song_core_approach = 64
song_core = 65
song_last_episode = 66
song_oh_my = 67
song_death_by_glamour = 68
song_for_the_fans = 69
song_long_elevator = 70
song_undertale = 71
song_song_that_might_play_when_you_fight_sans = 72
song_small_shock = 73
song_barrier = 74
song_bergentrückung = 75
song_asgore_wip = 76
song_your_idiot = 77
song_an_ending = 78
song_shes_playing_piano = 79
song_here_we_are_wip = 80
song_amalgam_wip = 81
song_but_the_earth_refused_to_die = 82
song_battle_against_a_true_hero = 83
song_power_of_neo = 84
song_megalovania_wip = 85
song_wrong_number_song = 86
song_happy_town = 87
song_meat_factory = 88
song_trouble_dingle = 89
song_him = 90
song_max = 91

.if SONG_STRINGS
song_strings:
.asciiz "=)"
.asciiz "Once upon a time"
.asciiz "Start Menu"
.asciiz "Your Best Friend"
.asciiz "Fallen Down"
.asciiz "Ruins"
.asciiz "Uwa!! So Temperate~"
.asciiz "Anticipation"
.asciiz "Unnecessary Tension"
.asciiz "Enemy Approching"
.asciiz "Ghost Fight"
.asciiz "Determination"
.asciiz "Home"
.asciiz "Home (Music Box)"
.asciiz "Heartache"
.asciiz "sans."
.asciiz "Nye heh heh!"
.asciiz "Snowy"
.asciiz "Uwa!! So Holiday~"
.asciiz "Dogbass"
.asciiz "Mysterious Place"
.asciiz "Dogsong"
.asciiz "Snowdin Town"
.asciiz "Shop"
.asciiz "Bonetrousle"
.asciiz "Dating Start"
.asciiz "Dating Tense"
.asciiz "Dating Fight"
.asciiz "Premonition"
.asciiz "Danger Mystery"
.asciiz "Undyne"
.asciiz "Waterfall"
.asciiz "Run!"
.asciiz "Quiet Water"
.asciiz "Memory"
.asciiz "Bird That Carries You Over A Disproportionately Small Gap"
.asciiz "Dummy!"
.asciiz "Pathetic House"
.asciiz "Spooktune"
.asciiz "Spookwave"
.asciiz "Ghouliday"
.asciiz "Chill"
.asciiz "Thundersnail"
.asciiz "Temmie Village"
.asciiz "Tem Shop"
.asciiz "NGAHHH!!"
.asciiz "Spear Of Justice"
.asciiz "Ooo"
.asciiz "Alphys"
.asciiz "It's Showtime!"
.asciiz "Metal Crusher"
.asciiz "Another Medium"
.asciiz "Uwa!! So HEATS!!~"
.asciiz "Stronger Monster (WIP)"
.asciiz "Hotel"
.asciiz "Can You Really Call This A Hotel, I Didn't Receive A Mint On My Pillow Or Anything"
.asciiz "Confession"
.asciiz "Live Report"
.asciiz "Death Report"
.asciiz "Wrong Enemy !?"
.asciiz "Oh! One True Love"
.asciiz "Oh! Dungeon"
.asciiz "Spider Dance (WIP)"
.asciiz "It's Raining Somewhere Else"
.asciiz "CORE Approach"
.asciiz "Core"
.asciiz "Last Episode"
.asciiz "Oh My..."
.asciiz "Death By Glamour"
.asciiz "For the Fans"
.asciiz "Long Elevator"
.asciiz "Undertale"
.asciiz "Song That Might Play When You Fight Sans"
.asciiz "Small Shock"
.asciiz "Barrier"
.asciiz "Bergentrückung"
.asciiz "ASGORE (WIP)"
.asciiz "Your Idiot"
.asciiz "An Ending"
.asciiz "She's Playing Piano"
.asciiz "Here We Are (WIP)"
.asciiz "Amalgam (WIP)"
.asciiz "But the Earth Refused to Die"
.asciiz "Battle Against a True Hero"
.asciiz "Power of "NEO""
.asciiz "Megalovania (WIP)"
.asciiz "Wrong Number Song"
.asciiz "Happy Town"
.asciiz "Meat Factory"
.asciiz "Trouble Dingle"
.asciiz "HIM"
.endif
