; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_undertale_ost_3=music_data_undertale_ost_3
.endif

music_data_undertale_ost_3:
	.byte 3
	.word @instruments
	.word @samples-5
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6 ; 00 : Your Best Nightmare
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,@song1ch5,@song1ch6 ; 01 : Battle Against a True Hero
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,@song2ch5,@song2ch6 ; 02 : Happy Town
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_undertale_ost_3
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env11,@env22,@env0 ; 00 : Lead wavy
	.word @env27,@env11,@env1,@env0 ; 01 : Flowey
	.word @env6,@env11,@env22,@env0 ; 02 : Basic
	.word @env8,@env11,@env22,@env23 ; 03 : Fade
	.word @env7,@env11,@env24,@env0 ; 04 : Quick Fade
	.word @env2,@env11,@env22,@env0 ; 05 : Kicks
	.word @env5,@env11,@env24,@env0 ; 06 : Lead 2
	.word @env0,@env11,@env22,@env0 ; 07 : NoSound
	.word @env4,@env11,@env26,@env0 ; 08 : Lead
	.word @env4,@env11,@env22,@env0 ; 09 : Lead 3
	.word @env9,@env11,@env24,@env0 ; 0a : Music box
	.word @env25,@env11,@env22,@env0 ; 0b : Echo

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$c0,$c1,$00,$02
@env2:
	.byte $00,$c8,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$00,$00
@env4:
	.byte $0e,$cf,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$00,$0b,$c3,$05,$c2,$06,$c1,$06,$c1,$00,$14
@env5:
	.byte $0c,$c6,$c7,$c8,$c8,$c8,$c9,$ca,$02,$c9,$00,$05,$c7,$c5,$c4,$c3,$c2,$00,$10
@env6:
	.byte $00,$cf,$7f,$00,$02
@env7:
	.byte $00,$cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$09
@env8:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env9:
	.byte $00,$c9,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c9,$c8,$c7,$c6,$c5,$c4,$c4,$c3,$c7,$c6,$c5,$c4,$c3,$c3,$c2,$c4,$c3,$c3,$c2,$02,$c1,$00,$1d
@env10:
	.byte $0c,$c2,$c4,$c6,$c7,$c8,$c9,$ca,$02,$c9,$00,$05,$c7,$c5,$c4,$c3,$c2,$00,$10
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $c0,$b5,$00,$00
@env13:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$00,$00
@env14:
	.byte $c0,$b6,$00,$00
@env15:
	.byte $c0,$b7,$00,$00
@env16:
	.byte $c0,$bd,$00,$00
@env17:
	.byte $c0,$bc,$00,$00
@env18:
	.byte $c0,$b8,$00,$00
@env19:
	.byte $c0,$b9,$00,$00
@env20:
	.byte $c0,$bb,$00,$00
@env21:
	.byte $c0,$ba,$00,$00
@env22:
	.byte $7f,$00,$00
@env23:
	.byte $00,$bd,$be,$bf,$be,$bf,$c0,$00,$06
@env24:
	.byte $c2,$7f,$00,$00
@env25:
	.byte $00,$cf,$06,$c0,$c0,$c8,$05,$c0,$c0,$c4,$05,$c0,$c0,$c2,$04,$c0,$c1,$00,$10
@env26:
	.byte $c1,$7f,$00,$00
@env27:
	.byte $00,$cf,$03,$c0,$00,$03
@env28:
	.byte $c0,$cc,$00,$00
@env29:
	.byte $c0,$c0,$cc,$cc,$00,$00

@samples:
	.byte $3d+.lobyte(FAMISTUDIO_DPCM_PTR),$80,$44,$40,$00 ; 00 aaah_f6 (Pitch:4)
	.byte $3d+.lobyte(FAMISTUDIO_DPCM_PTR),$80,$46,$40,$00 ; 01 aaah_f6 (Pitch:6)
	.byte $3d+.lobyte(FAMISTUDIO_DPCM_PTR),$80,$47,$40,$00 ; 02 aaah_f6 (Pitch:7)
	.byte $3d+.lobyte(FAMISTUDIO_DPCM_PTR),$80,$48,$40,$00 ; 03 aaah_f6 (Pitch:8)
	.byte $3d+.lobyte(FAMISTUDIO_DPCM_PTR),$80,$49,$40,$00 ; 04 aaah_f6 (Pitch:9)
	.byte $3d+.lobyte(FAMISTUDIO_DPCM_PTR),$80,$4a,$40,$00 ; 05 aaah_f6 (Pitch:10)
	.byte $3d+.lobyte(FAMISTUDIO_DPCM_PTR),$80,$4b,$40,$00 ; 06 aaah_f6 (Pitch:11)
	.byte $3d+.lobyte(FAMISTUDIO_DPCM_PTR),$80,$4c,$40,$00 ; 07 aaah_f6 (Pitch:12)
	.byte $5d+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4b,$40,$00 ; 08 aahs_1 (Pitch:11)
	.byte $01+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$4b,$40,$00 ; 09 aahs_2 (Pitch:11)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$41,$40,$00 ; 0a aahs_3 (Pitch:1)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$42,$40,$00 ; 0b aahs_3 (Pitch:2)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$44,$40,$00 ; 0c aahs_3 (Pitch:4)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$4b,$40,$00 ; 0d aahs_3 (Pitch:11)
	.byte $15+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$4b,$40,$00 ; 0e aahs_4 (Pitch:11)
	.byte $1f+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$4b,$40,$00 ; 0f aahs_5 (Pitch:11)
	.byte $29+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$4b,$40,$00 ; 10 aahs_6 (Pitch:11)
	.byte $33+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$4b,$40,$00 ; 11 aahs_7 (Pitch:11)
	.byte $68+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0d,$40,$00 ; 12 bird (Pitch:13)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$c2,$0e,$40,$02 ; 13 cymbal (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$4b,$40,$04 ; 14 elevator (Pitch:11)
	.byte $0a+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0b,$40,$04 ; 15 elevator_end (Pitch:11)
	.byte $1c+.lobyte(FAMISTUDIO_DPCM_PTR),$32,$0b,$40,$04 ; 16 elevator_start (Pitch:11)
	.byte $6d+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$45,$40,$00 ; 17 ff6_tenor_cs7 (Pitch:5)
	.byte $6d+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$47,$40,$00 ; 18 ff6_tenor_cs7 (Pitch:7)
	.byte $6d+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$48,$40,$00 ; 19 ff6_tenor_cs7 (Pitch:8)
	.byte $6d+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$49,$40,$00 ; 1a ff6_tenor_cs7 (Pitch:9)
	.byte $6d+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4a,$40,$00 ; 1b ff6_tenor_cs7 (Pitch:10)
	.byte $6d+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4b,$40,$00 ; 1c ff6_tenor_cs7 (Pitch:11)
	.byte $6d+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4d,$40,$00 ; 1d ff6_tenor_cs7 (Pitch:13)
	.byte $72+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$45,$40,$00 ; 1e ff6_tenor_gs6 (Pitch:5)
	.byte $72+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$47,$40,$00 ; 1f ff6_tenor_gs6 (Pitch:7)
	.byte $72+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$48,$40,$00 ; 20 ff6_tenor_gs6 (Pitch:8)
	.byte $72+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$49,$40,$00 ; 21 ff6_tenor_gs6 (Pitch:9)
	.byte $72+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$4a,$40,$00 ; 22 ff6_tenor_gs6 (Pitch:10)
	.byte $72+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$4c,$40,$00 ; 23 ff6_tenor_gs6 (Pitch:12)
	.byte $72+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$4d,$40,$00 ; 24 ff6_tenor_gs6 (Pitch:13)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$07,$40,$02 ; 25 impact_hit_cs6 (Pitch:7)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$08,$40,$02 ; 26 impact_hit_cs6 (Pitch:8)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$09,$40,$02 ; 27 impact_hit_cs6 (Pitch:9)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0a,$40,$02 ; 28 impact_hit_cs6 (Pitch:10)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0b,$40,$02 ; 29 impact_hit_cs6 (Pitch:11)
	.byte $31+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0c,$40,$02 ; 2a impact_hit_cs6 (Pitch:12)
	.byte $77+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0d,$40,$00 ; 2b megadrive_drumki (Pitch:13)
	.byte $77+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0e,$40,$00 ; 2c megadrive_drumki (Pitch:14)
	.byte $77+.lobyte(FAMISTUDIO_DPCM_PTR),$18,$0f,$40,$00 ; 2d megadrive_drumki (Pitch:15)
	.byte $7d+.lobyte(FAMISTUDIO_DPCM_PTR),$06,$0f,$40,$00 ; 2e megadrive_drumki 1 (Pitch:15)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$08,$40,$02 ; 2f nes_drumkit_1 (Pitch:8)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0b,$40,$02 ; 30 nes_drumkit_1 (Pitch:11)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0d,$40,$02 ; 31 nes_drumkit_1 (Pitch:13)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0f,$40,$02 ; 32 nes_drumkit_1 (Pitch:15)
	.byte $4f+.lobyte(FAMISTUDIO_DPCM_PTR),$25,$0f,$40,$02 ; 33 nes_drumkit_2 (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$32,$0f,$40,$02 ; 34 nes_drumkit_3 (Pitch:15)
	.byte $66+.lobyte(FAMISTUDIO_DPCM_PTR),$1e,$0f,$40,$02 ; 35 nes_drumkit_4 (Pitch:15)
	.byte $6e+.lobyte(FAMISTUDIO_DPCM_PTR),$1e,$0f,$40,$02 ; 36 nes_drumkit_4_re (Pitch:15)
	.byte $29+.lobyte(FAMISTUDIO_DPCM_PTR),$db,$0b,$40,$04 ; 37 photoshop_flowey (Pitch:11)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$db,$0b,$44,$05 ; 38 photoshop_flowey 1 (Pitch:11)
	.byte $37+.lobyte(FAMISTUDIO_DPCM_PTR),$da,$0b,$40,$05 ; 39 photoshop_flowey 2 (Pitch:11)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$70,$00 ; 3a triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$10,$00 ; 3b triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$40,$00 ; 3c triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$20,$00 ; 3d triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$60,$00 ; 3e triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$00,$00 ; 3f triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$7e,$00 ; 40 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$30,$00 ; 41 triangle noise (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$50,$00 ; 42 triangle noise (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ref1:
	.byte $80
@song0ref2:
	.byte $17, $c9, $16, $c9, $47, $19, $ff, $95, $47, $ff, $97, $47, $17, $c9, $16, $c9, $47, $1a, $ff, $95, $47, $ff, $97
@song0ref25:
	.byte $47, $17, $c9, $16, $c9, $47, $19, $ff, $95, $47, $ff, $97, $47, $17, $c9, $16, $c9, $47, $1a, $ff, $95, $47, $ff, $97
	.byte $47, $44, $a3, $00, $ef, $47, $ff, $97, $47, $ff, $97, $47, $ff, $97, $47, $ff, $97, $47, $ff, $97, $47
	.byte $41, $24
	.word @song0ref2
	.byte $41, $18
	.word @song0ref25
@song0ref76:
	.byte $47, $4f, $e8, $24, $28, $91, $1c, $db, $4f, $18, $28, $24, $91, $4f, $43, $24, $1c, $8f, $47, $4f, $e8, $24, $28, $91
	.byte $1c, $db, $4f, $18, $28, $24, $91, $4f, $43, $24, $1c, $8f, $47, $4f, $e8, $24, $28, $91, $1c, $db, $4f, $18, $28, $24
	.byte $91, $4f, $43, $24, $1c, $8f, $47, $4f, $e8, $24, $28, $91, $1c, $db, $4f, $18, $28, $24, $91, $4f, $43, $24, $1c, $8f
	.byte $47, $00, $ff, $95, $47, $82
@song0ref154:
	.byte $28, $87, $00, $87, $78, $28, $87, $00, $85, $7f, $2c, $87, $00, $87, $78, $2c, $87, $00, $85, $7f, $23, $87, $00, $87
	.byte $78, $23, $87, $00, $85, $7f, $2c, $87, $00, $87, $78, $2c, $87, $00, $85, $47, $7f
	.byte $41, $20
	.word @song0ref154
	.byte $47, $7f
	.byte $41, $20
	.word @song0ref154
	.byte $47, $7f
	.byte $41, $20
	.word @song0ref154
	.byte $47, $7f
	.byte $41, $20
	.word @song0ref154
	.byte $47, $7f, $2a, $87, $00, $87, $78, $2a, $87, $00, $85, $7f, $2f, $87, $00, $87, $78, $2f, $87, $00, $85, $7f, $23, $87
	.byte $00, $87, $78, $23, $87, $00, $85, $7f, $2f, $87, $00, $87, $78, $2f, $87, $00, $85, $47, $7f
	.byte $41, $20
	.word @song0ref154
	.byte $47, $7f, $21, $87, $00, $87, $78, $21, $87, $00, $85, $7f, $28, $87, $00, $87, $78, $28, $87, $00, $85, $7f, $2a, $87
	.byte $00, $87, $78, $2a, $87, $00, $85, $7f, $3b, $87, $00, $87, $78, $3b, $87, $00, $85, $47, $7f
	.byte $41, $20
	.word @song0ref154
	.byte $47, $7f, $21, $87, $00, $87, $78, $21, $87, $00, $85, $7f, $2a, $87, $00, $87, $78, $2a, $87, $00, $85, $7f, $23, $87
	.byte $00, $87, $78, $23, $87, $00, $85, $7f, $33, $87, $00, $87, $78, $33, $87, $00, $85, $47, $7f, $21, $87, $00, $87, $78
	.byte $21, $87, $00, $85, $7f, $25, $87, $00, $87, $78, $25, $87, $00, $85, $7f, $23, $87, $00, $87, $78, $23, $87, $00, $85
	.byte $7f, $27, $87, $00, $87, $78, $27, $87, $00, $85, $47, $7f, $28, $87, $00, $87, $78, $28, $87, $00, $ab, $7f, $34, $87
	.byte $00, $87, $78, $34, $87, $00, $ab, $47, $ff, $97, $47, $7f, $8c
@song0ref414:
	.byte $25, $87, $00, $87, $2a, $87, $00, $85, $30, $87, $00, $87, $31, $87, $00, $85, $25, $87, $00, $87, $2a, $87, $00, $85
	.byte $30, $87, $00, $87, $31, $87, $00, $85, $47
	.byte $41, $20
	.word @song0ref414
@song0ref450:
	.byte $47, $28, $87, $00, $87, $2d, $87, $00, $85, $33, $87, $00, $87, $34, $87, $00, $85, $28, $87, $00, $87, $2d, $87, $00
	.byte $85, $33, $87, $00, $87, $34, $87, $00, $85
	.byte $41, $20
	.word @song0ref450
	.byte $47
	.byte $41, $20
	.word @song0ref414
	.byte $47
	.byte $41, $20
	.word @song0ref414
	.byte $41, $20
	.word @song0ref450
	.byte $41, $20
	.word @song0ref450
	.byte $47
	.byte $41, $20
	.word @song0ref414
	.byte $47
	.byte $41, $20
	.word @song0ref414
	.byte $41, $20
	.word @song0ref450
	.byte $41, $20
	.word @song0ref450
	.byte $47, $ff, $97, $47, $80
@song0ref519:
	.byte $27, $c9, $50, $f9, $00, $22, $c9, $47, $7f, $00, $9b, $24, $85, $25, $a3, $20, $a3, $20, $a3, $47, $27, $c9, $50, $f9
	.byte $00, $22, $c9, $47, $7f, $00, $9b, $23, $85, $24, $a3, $25, $a3, $26, $a3, $47
	.byte $41, $1c
	.word @song0ref519
	.byte $47
	.byte $41, $1c
	.word @song0ref519
	.byte $47
	.byte $41, $1c
	.word @song0ref519
	.byte $47, $00, $ff, $95, $47, $ff, $97
	.byte $41, $23
	.word @song0ref76
	.byte $47, $88
@song0ref582:
	.byte $04, $91, $06, $8f, $08, $91, $02, $8f, $16, $91, $14, $8f, $10, $91, $12, $8f, $47, $0c, $91, $10, $8f, $0a, $91, $0e
	.byte $8f, $08, $91, $0c, $8f, $06, $91, $0a, $8f, $47
	.byte $41, $20
	.word @song0ref582
	.byte $47
	.byte $41, $20
	.word @song0ref582
	.byte $47
	.byte $41, $20
	.word @song0ref582
	.byte $47
	.byte $41, $20
	.word @song0ref582
	.byte $47
	.byte $41, $20
	.word @song0ref582
	.byte $47, $00, $ff, $95, $47, $4e, $02, $84, $0a, $87, $00
@song0ref646:
	.byte $87, $7c, $0a, $87, $78, $0a, $85, $7c, $0a, $87, $76, $0a, $87, $7c, $0a, $87, $76, $0a, $85, $7c, $0a, $87, $76, $0a
	.byte $87, $7c, $0a, $87, $76, $0a, $85, $7c, $0a, $87, $76, $0a, $87, $7c, $0a, $87, $76, $0a, $85, $47, $7f, $4e, $02, $0a
	.byte $87, $76, $0a
	.byte $41, $20
	.word @song0ref646
	.byte $41, $20
	.word @song0ref646
	.byte $41, $20
	.word @song0ref646
	.byte $41, $20
	.word @song0ref646
	.byte $41, $20
	.word @song0ref646
	.byte $41, $20
	.word @song0ref646
	.byte $41, $20
	.word @song0ref646
	.byte $41, $20
	.word @song0ref646
	.byte $41, $20
	.word @song0ref646
	.byte $41, $20
	.word @song0ref646
	.byte $41, $1d
	.word @song0ref646
	.byte $47, $00, $ff, $95, $47, $7f, $4e, $00, $80
@song0ref739:
	.byte $17, $a3, $16, $a3, $19, $c9, $47, $4e, $00, $17, $a3, $16, $a3, $19, $c9, $47, $4e, $00, $17, $a3, $16, $a3, $19, $c9
	.byte $47, $4e, $00, $17, $a3, $16, $a3, $19, $c9, $47, $18, $a3, $17, $a3, $1a, $c9, $47, $18, $a3, $17, $a3, $1a, $c9, $47
	.byte $18, $a3, $17, $a3, $1a, $c9, $47, $18, $a3, $17, $a3, $1a, $c9, $47, $4e, $00
	.byte $41, $30
	.word @song0ref739
	.byte $47, $19, $ff, $95, $47, $ff, $97, $47, $44, $a3, $00, $ef, $47, $ff, $97, $47, $ff, $97, $47, $90
@song0ref826:
	.byte $06, $91, $0c, $8f, $11, $a3, $06, $91, $0c, $8f, $11, $a3, $47, $07, $91, $0d, $8f, $11, $a3, $07, $91, $0d, $8f, $11
	.byte $a3, $47
	.byte $41, $18
	.word @song0ref826
	.byte $47
	.byte $41, $18
	.word @song0ref826
	.byte $47
	.byte $41, $18
	.word @song0ref826
	.byte $47
	.byte $41, $18
	.word @song0ref826
	.byte $47
	.byte $41, $18
	.word @song0ref826
	.byte $47, $00, $ff, $95, $47, $92
@song0ref877:
	.byte $04, $91, $0b, $8f, $09, $91, $0b, $8f, $07, $91, $0b, $8f, $06, $91, $0b, $8f, $47, $02, $91, $0b, $8f, $09, $91, $0b
	.byte $8f, $07, $91, $0b, $8f, $06, $91, $0b, $8f, $47, $40, $0c, $91, $0b, $8f, $09, $91, $0b, $8f, $07, $91, $0b, $8f, $06
	.byte $91, $0b, $8f, $47, $40, $0b, $91, $0b, $8f, $09, $91, $0b, $8f, $07, $91, $0b, $8f, $0e, $91, $0b, $8f, $47
	.byte $41, $40
	.word @song0ref877
	.byte $47
	.byte $41, $40
	.word @song0ref877
	.byte $47, $00, $ff, $95, $47
	.byte $41, $24
	.word @song0ref1
	.byte $41, $18
	.word @song0ref25
	.byte $41, $20
	.word @song0ref76
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $00, $ff, $95, $42
	.word @song0ch0loop
@song0ch1:
@song0ref978:
	.byte $80
@song0ref979:
	.byte $23, $c9, $22, $c9, $25, $ff, $95, $ff, $97, $23, $c9, $22, $c9, $26, $ff, $95, $ff, $97
@song0ref997:
	.byte $23, $c9, $22, $c9, $25, $ff, $95, $ff, $97, $23, $c9, $22, $c9, $26, $ff, $95, $ff, $97, $44, $a3, $00, $ef, $ff, $97
	.byte $ff, $97, $ff, $97, $ff, $97, $ff, $97
	.byte $41, $24
	.word @song0ref979
	.byte $41, $20
	.word @song0ref997
@song0ref1035:
	.byte $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97
	.byte $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $8c
@song0ref1072:
	.byte $3a, $91, $00, $8f, $3a, $91, $3b, $8f, $3d, $91, $00, $8f, $3a, $91, $00, $8f, $3b, $91, $00, $8f, $38, $91, $00, $8f
	.byte $34, $91, $00, $8f, $38, $91, $00, $8f, $3d, $91, $00, $8f, $3d, $91, $3e, $8f, $40, $4c, $91, $00, $8f, $40, $51, $91
	.byte $00, $8f, $40, $4e, $c9, $40, $4c, $91, $00, $b5
	.byte $41, $28
	.word @song0ref1072
	.byte $3b, $91, $00, $8f, $37, $91, $00, $8f, $39, $c9, $40, $51, $91, $00, $b5, $ff, $97, $80
@song0ref1151:
	.byte $1b, $c9, $50, $f9, $00, $16, $c9, $7f, $00, $9b, $18, $85, $19, $a3, $14, $a3, $14, $a3, $1b, $c9, $50, $f9, $00, $16
	.byte $c9, $7f, $00, $9b, $17, $85, $18, $a3, $19, $a3, $1a, $a3
	.byte $41, $1c
	.word @song0ref1151
	.byte $41, $1c
	.word @song0ref1151
	.byte $41, $1c
	.word @song0ref1151
@song0ref1196:
	.byte $00, $ff, $95, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $78
	.byte $8c
@song0ref1221:
	.byte $3a, $87, $00, $99, $3a, $87, $00, $87, $3c, $87, $00, $85, $3e, $87, $00, $99, $3a, $87, $00, $99, $3c, $87, $00, $99
	.byte $3c, $87, $00, $87, $3e, $87, $00, $85, $38, $87, $00, $99, $34, $87, $00, $99, $3a, $87, $00, $99, $3a, $87, $00, $87
	.byte $3c, $87, $00, $85, $3e, $87, $00, $99, $40, $52, $87, $00, $99, $40, $4e, $c9, $3c, $c9
	.byte $41, $34
	.word @song0ref1221
	.byte $38, $87, $00, $99, $34, $87, $00, $99, $36, $b7, $00, $8f, $40, $4e, $c9, $00, $ff, $95, $ff, $97, $ff, $97, $ff, $97
	.byte $ff, $97, $7c, $4e, $02, $84
@song0ref1320:
	.byte $20, $91, $00, $8f, $20, $91, $22, $8f, $24, $91, $00, $8f, $20, $91, $00, $8f, $22, $91, $00, $8f, $22, $91, $24, $8f
	.byte $1f, $91, $00, $8f, $1b, $91, $00, $8f, $20, $91, $00, $8f, $20, $91, $22, $8f, $24, $91, $00, $8f, $2c, $91, $00, $8f
	.byte $29, $c9, $27, $b7, $00, $8f, $4e, $02
	.byte $41, $28
	.word @song0ref1320
	.byte $1f, $91, $00, $8f, $1b, $91, $00, $8f, $1d, $c9, $29, $c9, $00, $ff, $95, $7f, $4e, $00, $80
@song0ref1398:
	.byte $23, $a3, $22, $a3, $25, $c9, $4e, $00, $23, $a3, $22, $a3, $25, $c9, $4e, $00, $23, $a3, $22, $a3, $25, $c9, $4e, $00
	.byte $23, $a3, $22, $a3, $25, $c9, $24, $a3, $23, $a3, $26, $c9, $24, $a3, $23, $a3, $26, $c9, $24, $a3, $23, $a3, $26, $c9
	.byte $24, $a3, $23, $a3, $26, $c9, $4e, $00
	.byte $41, $30
	.word @song0ref1398
	.byte $25, $ff, $95, $ff, $97, $44, $a3, $00, $ef, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $8c
@song0ref1479:
	.byte $24, $91, $00, $8f, $24, $91, $25, $8f, $27, $91, $00, $8f, $24, $91, $00, $8f, $25, $91, $00, $8f, $25, $91, $27, $8f
	.byte $22, $91, $00, $8f, $1b, $91, $00, $8f, $24, $91, $00, $8f, $24, $91, $25, $8f, $27, $91, $00, $8f, $2c, $91, $00, $8f
	.byte $29, $c9, $27, $b7, $00, $8f
	.byte $41, $28
	.word @song0ref1479
	.byte $24, $91, $00, $8f, $20, $91, $00, $8f, $22, $c9, $2e, $c9, $00, $ff, $95, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $82
@song0ref1560:
	.byte $1f, $91, $00, $87, $78, $1f, $85, $7f, $1f, $91, $21, $87, $78, $1f, $85, $7f, $23, $87, $78, $21, $87, $00, $87, $23
	.byte $85, $7f, $1f, $91, $00, $87, $78, $1f, $85, $7f, $21, $91, $00, $87, $78, $21, $85, $7f, $21, $91, $23, $87, $78, $21
	.byte $85, $7f, $1e, $87, $78, $23, $87, $00, $87, $1e, $85, $7f, $1a, $91, $00, $87, $78, $1a, $85, $7f, $1f, $91, $00, $87
	.byte $78, $1f, $85, $7f, $1f, $91, $21, $87, $78, $1f, $85, $7f, $23, $87, $78, $21, $87, $00, $87, $23, $85, $7f, $2b, $91
	.byte $00, $87, $78, $2b, $85, $7f, $2a, $91, $00, $87, $78, $2a, $85, $00, $a3, $7f, $26, $91, $00, $87, $78, $26, $85, $00
	.byte $a3, $7f
	.byte $41, $40
	.word @song0ref1560
	.byte $7f, $1e, $87, $78, $21, $87, $00, $87, $1e, $85, $7f, $1a, $91, $00, $87, $78, $1a, $85, $7f, $1c, $91, $00, $87, $78
	.byte $1c, $85, $00, $a3, $7f, $28, $91, $00, $87, $78, $28, $85, $00, $a3, $ff, $97, $7f
	.byte $41, $24
	.word @song0ref978
	.byte $41, $20
	.word @song0ref997
@song0ch1loop:
	.byte $ff, $97, $42
	.word @song0ch1loop
@song0ch2:
	.byte $41, $24
	.word @song0ref1035
	.byte $84
@song0ref1742:
	.byte $0b, $91, $09, $8f, $07, $91, $0d, $8f, $0a, $91, $08, $8f, $04, $91, $02, $8f, $0d, $91, $05, $8f, $06, $91, $07, $8f
	.byte $0c, $91, $04, $8f, $05, $91, $06, $8f
@song0ref1774:
	.byte $0b, $91, $09, $8f, $07, $91, $0d, $8f, $0a, $91, $08, $8f, $04, $91, $02, $8f, $0b, $91, $09, $8f, $07, $91, $0d, $8f
	.byte $0a, $91, $08, $8f, $04, $91, $02, $8f, $0e, $91, $05, $8f, $06, $91, $07, $8f, $0d, $91, $04, $8f, $05, $91, $06, $8f
	.byte $0c, $91, $0a, $8f, $08, $91, $0e, $8f, $0b, $91, $09, $8f, $05, $91, $03, $8f
	.byte $41, $60
	.word @song0ref1742
	.byte $41, $60
	.word @song0ref1742
	.byte $41, $60
	.word @song0ref1742
	.byte $00, $ff, $95, $ff, $97, $ff, $97, $ff, $97, $ff, $97
@song0ref1858:
	.byte $40, $50, $91, $00, $8f, $40, $50, $91, $40, $51, $8f, $40, $53, $91, $00, $8f, $40, $50, $91, $00, $8f, $40, $51, $91
	.byte $00, $8f, $40, $51, $91, $40, $53, $8f, $40, $4e, $91, $00, $8f, $3b, $91, $00, $8f, $40, $50, $91, $00, $8f, $40, $50
	.byte $91, $40, $51, $8f, $40, $53, $91, $00, $8f, $40, $58, $91, $00, $8f, $40, $55, $c1, $4f, $fe, $51, $53, $85, $40, $53
	.byte $91, $00, $b5
	.byte $41, $28
	.word @song0ref1858
	.byte $40, $4e, $91, $00, $8f, $3f, $91, $00, $8f, $40, $4c, $c1, $4f, $fe, $56, $58, $85, $40, $58, $91, $00, $b5
	.byte $41, $1c
	.word @song0ref1035
@song0ref1961:
	.byte $0f, $91, $03, $8f, $09, $91, $0f, $8f, $0d, $91, $07, $8f, $0b, $91, $05, $8f, $05, $91, $01, $8f, $08, $91, $0e, $8f
	.byte $08, $91, $01, $8f, $08, $91, $0e, $8f
	.byte $41, $18
	.word @song0ref1961
	.byte $09, $91, $0f, $8f, $0a, $91, $10, $8f
	.byte $41, $20
	.word @song0ref1961
	.byte $41, $18
	.word @song0ref1961
	.byte $09, $91, $0f, $8f, $0a, $91, $10, $8f
	.byte $41, $20
	.word @song0ref1961
	.byte $41, $18
	.word @song0ref1961
	.byte $09, $91, $0f, $8f, $0a, $91, $10, $8f
	.byte $41, $20
	.word @song0ref1961
	.byte $41, $18
	.word @song0ref1961
	.byte $09, $91, $0f, $8f, $0a, $91, $10, $8f
	.byte $41, $20
	.word @song0ref1961
	.byte $41, $20
	.word @song0ref1961
	.byte $41, $18
	.word @song0ref1961
	.byte $09, $91, $0f, $8f, $0a, $91, $10, $8f, $00, $ff, $95, $ff, $97, $ff, $97, $ff, $97, $ff, $97
@song0ref2074:
	.byte $2e, $87, $00, $99, $2e, $87, $00, $87, $30, $87, $00, $85, $32, $87, $00, $99, $2e, $87, $00, $99, $30, $87, $00, $99
	.byte $30, $87, $00, $87, $32, $87, $00, $85, $2c, $87, $00, $99, $28, $87, $00, $99, $2e, $87, $00, $99, $2e, $87, $00, $87
	.byte $30, $87, $00, $85, $32, $87, $00, $99, $3a, $87, $00, $99, $36, $c9, $30, $c9
	.byte $41, $34
	.word @song0ref2074
	.byte $2c, $87, $00, $99, $28, $87, $00, $99, $2a, $b7, $00, $8f, $36, $c9
	.byte $41, $17
	.word @song0ref1196
	.byte $ff, $97, $ff, $97, $ff, $97
	.byte $41, $20
	.word @song0ref1774
	.byte $41, $20
	.word @song0ref1774
@song0ref2170:
	.byte $0c, $91, $0a, $8f, $08, $91, $0e, $8f, $0b, $91, $09, $8f, $05, $91, $03, $8f, $0c, $91, $0a, $8f, $08, $91, $0e, $8f
	.byte $0b, $91, $09, $8f, $05, $91, $03, $8f
	.byte $41, $20
	.word @song0ref2170
	.byte $41, $20
	.word @song0ref1774
	.byte $41, $20
	.word @song0ref1774
	.byte $41, $20
	.word @song0ref2170
	.byte $41, $20
	.word @song0ref2170
	.byte $41, $17
	.word @song0ref1196
	.byte $41, $24
	.word @song0ref1035
	.byte $ff, $97, $ff, $97
	.byte $41, $60
	.word @song0ref1742
	.byte $41, $60
	.word @song0ref1742
	.byte $41, $60
	.word @song0ref1742
	.byte $41, $60
	.word @song0ref1742
@song0ch2loop:
	.byte $00, $ff, $95, $42
	.word @song0ch2loop
@song0ch3:
	.byte $41, $24
	.word @song0ref1035
@song0ref2249:
	.byte $86, $04, $91, $01, $8f, $88, $40, $05, $87, $00, $87, $86, $01, $8f, $04, $91, $88, $40, $05, $87, $00, $85, $86, $01
	.byte $91, $88, $40, $03
@song0ref2277:
	.byte $87, $00, $85, $86, $04, $91, $01, $8f, $88, $40, $05, $87, $00, $87, $86, $01, $8f, $04, $91, $88, $40, $05, $87, $00
	.byte $85, $86, $01, $91, $88, $40, $03, $87, $00, $85
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $26
	.word @song0ref2249
	.byte $40, $05, $87, $00, $87, $40, $05
	.byte $41, $19
	.word @song0ref2277
@song0ref2348:
	.byte $86, $04, $91, $01, $8f, $88, $40, $09, $87, $00, $87, $86, $01, $8f, $04, $91, $88, $40, $05, $87, $00, $85, $40, $05
	.byte $87, $40, $05, $87, $40, $05, $87, $40, $05, $85, $86, $04, $91, $01, $8f, $88, $40, $05, $87, $00, $87, $86, $01, $8f
	.byte $04, $91, $88, $40, $05, $87, $00, $85, $86, $01, $91, $04, $8f, $04, $91, $01, $8f, $88, $40, $05, $87, $00, $87, $86
	.byte $01, $8f, $04, $91, $01, $8f, $04, $91, $01, $8f
@song0ref2430:
	.byte $84, $01, $ff, $95, $8a
@song0ref2435:
	.byte $40, $0b, $87, $00, $87, $40, $0c, $87, $00, $85, $01, $87, $00, $87, $40, $0c, $87, $40, $0b, $85, $40, $0b, $87, $00
	.byte $87, $40, $0c, $87, $40, $0b, $85, $40, $0b, $87, $40, $0b, $87, $40, $0c, $87, $40, $0b, $85
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $23
	.word @song0ref2430
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $84, $01, $ff, $95
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $26
	.word @song0ref2249
	.byte $40, $05, $87, $00, $87, $40, $05
	.byte $41, $19
	.word @song0ref2277
	.byte $41, $61
	.word @song0ref2348
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $23
	.word @song0ref2430
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $84, $01, $ff, $95
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $ff, $97, $ff, $97, $ff, $97, $ff, $97
	.byte $41, $23
	.word @song0ref2430
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $23
	.word @song0ref2430
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $41, $20
	.word @song0ref2435
	.byte $84, $01, $ff, $95
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $2c
	.word @song0ref2249
	.byte $41, $26
	.word @song0ref2249
	.byte $40, $05, $87, $00, $87, $40, $05
	.byte $41, $19
	.word @song0ref2277
	.byte $41, $3e
	.word @song0ref2348
@song0ch3loop:
	.byte $84, $01, $ff, $95, $42
	.word @song0ch3loop
@song0ch4:
	.byte $41, $19
	.word @song0ref1035
	.byte $85, $51, $00, $38, $8f, $ff, $97, $c3, $39, $d1, $ff, $97, $3a, $ff, $95, $d5, $00, $bf, $51, $80
	.byte $41, $24
	.word @song0ref1035
	.byte $ff, $97, $ff, $97
@song0ref2853:
	.byte $ff, $97, $ff, $97
@song0ref2857:
	.byte $ff, $97, $ff, $97
@song0ref2861:
	.byte $ff, $97
@song0ref2863:
	.byte $33, $9b, $00, $ab, $32, $9b, $00, $85, $32, $9b, $00, $85, $33, $9b, $00, $ab, $32, $9b, $00, $85, $32, $9b, $00, $85
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $1a
	.word @song0ref2861
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $ff, $97, $51, $80
	.byte $41, $24
	.word @song0ref1035
	.byte $41, $22
	.word @song0ref2853
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $1a
	.word @song0ref2861
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $ff, $97, $51, $80
	.byte $41, $24
	.word @song0ref1035
	.byte $41, $1e
	.word @song0ref2857
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $1a
	.word @song0ref2861
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $18
	.word @song0ref2863
	.byte $41, $24
	.word @song0ref1035
	.byte $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97
@song0ch4loop:
	.byte $ff, $97, $42
	.word @song0ch4loop
@song0ch5:
@song0ref3029:
	.byte $80
@song0ref3030:
	.byte $1e, $c9, $1d, $c9, $20, $ff, $95, $ff, $97, $1e, $c9, $1d, $c9, $21, $ff, $95, $ff, $97
@song0ref3048:
	.byte $1e, $c9, $1d, $c9, $20, $ff, $95, $ff, $97, $1e, $c9, $1d, $c9, $21, $ff, $95, $ff, $97, $44, $a3, $00, $ef, $ff, $97
	.byte $ff, $97, $ff, $97, $ff, $97, $ff, $97
	.byte $41, $24
	.word @song0ref3030
	.byte $41, $20
	.word @song0ref3048
	.byte $41, $1c
	.word @song0ref1035
	.byte $9d, $78, $8c
@song0ref3092:
	.byte $25, $85, $00, $87, $2a, $87, $00, $87, $30, $85, $00, $87, $31, $87, $00, $87, $25, $85, $00, $87, $2a, $87, $00, $87
	.byte $30, $85, $00, $87, $31, $87, $00, $87
	.byte $41, $20
	.word @song0ref3092
@song0ref3127:
	.byte $28, $85, $00, $87, $2d, $87, $00, $87, $33, $85, $00, $87, $34, $87, $00, $87, $28, $85, $00, $87, $2d, $87, $00, $87
	.byte $33, $85, $00, $87, $34, $87, $00, $87
	.byte $41, $20
	.word @song0ref3127
	.byte $41, $20
	.word @song0ref3092
	.byte $41, $20
	.word @song0ref3092
	.byte $41, $20
	.word @song0ref3127
	.byte $41, $20
	.word @song0ref3127
	.byte $41, $20
	.word @song0ref3092
	.byte $41, $20
	.word @song0ref3092
	.byte $41, $20
	.word @song0ref3127
	.byte $41, $1b
	.word @song0ref3127
	.byte $ff, $95, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $4e, $02, $80, $36, $ff, $95
	.byte $ff, $97, $00, $ff, $95, $ff, $97, $4e, $02, $36, $ff, $95, $ff, $97
	.byte $41, $17
	.word @song0ref1196
	.byte $41, $1e
	.word @song0ref1035
	.byte $7c, $84
@song0ref3232:
	.byte $19, $91, $00, $8f, $19, $91, $1b, $8f, $1d, $91, $00, $8f, $19, $91, $00, $8f, $1b, $91, $00, $8f, $1b, $91, $1d, $8f
	.byte $18, $91, $00, $8f, $14, $91, $00, $8f, $19, $91, $00, $8f, $19, $91, $1b, $8f, $1d, $91, $00, $8f, $25, $91, $00, $8f
	.byte $22, $c9, $20, $b7, $00, $8f
	.byte $41, $28
	.word @song0ref3232
	.byte $18, $91, $00, $8f, $14, $91, $00, $8f, $16, $c9, $22, $c9, $00, $ff, $95, $7f, $4e, $00, $80
@song0ref3308:
	.byte $1e, $a3, $1d, $a3, $20, $c9, $4e, $00, $1e, $a3, $1d, $a3, $20, $c9, $4e, $00, $1e, $a3, $1d, $a3, $20, $c9, $4e, $00
	.byte $1e, $a3, $1d, $a3, $20, $c9, $1f, $a3, $1e, $a3, $21, $c9, $1f, $a3, $1e, $a3, $21, $c9, $1f, $a3, $1e, $a3, $21, $c9
	.byte $1f, $a3, $1e, $a3, $21, $c9, $4e, $00
	.byte $41, $30
	.word @song0ref3308
	.byte $20, $ff, $95, $ff, $97, $44, $a3, $00, $ef, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $8c
@song0ref3389:
	.byte $20, $91, $00, $8f, $20, $91, $22, $8f, $24, $91, $00, $8f, $20, $91, $00, $8f, $1e, $91, $00, $8f, $1e, $91, $20, $8f
	.byte $1b, $91, $00, $8f, $11, $91, $00, $8f, $20, $91, $00, $8f, $20, $91, $22, $8f, $24, $91, $00, $8f, $27, $91, $00, $8f
	.byte $22, $c9, $20, $b7, $00, $8f
	.byte $41, $28
	.word @song0ref3389
	.byte $20, $91, $00, $8f, $1b, $91, $00, $8f, $1d, $c9, $25, $c9, $00, $ff, $95, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $82
@song0ref3470:
	.byte $1c, $91, $00, $87, $78, $1c, $85, $7f, $1c, $91, $1e, $87, $78, $1c, $85, $7f, $1f, $87, $78, $1e, $87, $00, $87, $1f
	.byte $85, $7f, $1c, $91, $00, $87, $78, $1c, $85, $7f, $1e, $91, $00, $87, $78, $1e, $85, $7f, $1e, $91, $1f, $87, $78, $1e
	.byte $85, $7f, $1a, $87, $78, $1f, $87, $00, $87, $1a, $85, $7f, $15, $91, $00, $87, $78, $15, $85, $7f
	.byte $41, $1a
	.word @song0ref3470
	.byte $7f, $21, $91, $00, $87, $78, $21, $85, $00, $a3, $7f, $1e, $91, $00, $87, $78, $1e, $85, $00, $a3, $7f
	.byte $41, $34
	.word @song0ref3470
	.byte $7f, $1c, $91, $00, $87, $78, $1c, $85, $7f, $1c, $91, $1e, $87, $78, $1c, $85, $7f, $1a, $87, $78, $1e, $87, $00, $87
	.byte $1a, $85, $7f, $15, $91, $00, $87, $78, $15, $85, $7f, $13, $91, $00, $87, $78, $13, $85, $00, $a3, $7f, $1f, $91, $00
	.byte $87, $78, $1f, $85, $00, $a3, $ff, $97, $7f
	.byte $41, $24
	.word @song0ref3029
	.byte $41, $20
	.word @song0ref3048
@song0ch5loop:
	.byte $ff, $97, $42
	.word @song0ch5loop
@song0ch6:
@song0ref3634:
	.byte $4e, $02, $80
@song0ref3637:
	.byte $40, $0b, $c9, $40, $0a, $c9, $01, $ff, $95, $ff, $97, $40, $0b, $c9, $40, $0a, $c9, $02, $ff, $95, $ff, $97
@song0ref3659:
	.byte $4e, $02, $40, $0b, $c9, $40, $0a, $c9, $01, $ff, $95, $ff, $97, $40, $0b, $c9, $40, $0a, $c9, $02, $ff, $95, $ff, $97
	.byte $44, $a3, $00, $ef, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $4e, $02
	.byte $41, $24
	.word @song0ref3637
	.byte $41, $20
	.word @song0ref3659
	.byte $41, $24
	.word @song0ref1035
	.byte $93, $78, $8c
@song0ref3711:
	.byte $3a, $8f, $00, $91, $3a, $8f, $3b, $91, $3d, $8f, $00, $91, $3a, $8f, $00, $91, $3b, $8f, $00, $91, $38, $8f, $00, $91
	.byte $34, $8f, $00, $91, $38, $8f, $00, $91, $3d, $8f, $00, $91, $3d, $8f, $3e, $91, $40, $4c, $8f, $00, $91, $40, $51, $8f
	.byte $00, $91, $40, $4e, $c9, $40, $4c, $8f, $00, $a3, $93
	.byte $41, $28
	.word @song0ref3711
	.byte $3b, $8f, $00, $91, $37, $8f, $00, $91, $39, $c9, $40, $51, $8f, $00, $a3, $ff, $97, $7f, $80
@song0ref3792:
	.byte $03, $c9, $50, $f9, $00, $40, $0a, $c9, $7f, $00, $9b, $40, $0c, $85, $01, $a3, $8e, $40, $08, $a3, $40, $08, $a3, $80
	.byte $03, $c9, $50, $f9, $00, $40, $0a, $c9, $7f, $00, $9b, $40, $0b, $85, $40, $0c, $a3, $01, $a3, $02, $a3
	.byte $41, $1c
	.word @song0ref3792
	.byte $41, $1c
	.word @song0ref3792
	.byte $41, $1c
	.word @song0ref3792
	.byte $41, $17
	.word @song0ref1196
	.byte $41, $1a
	.word @song0ref1035
	.byte $89, $00, $91, $76, $4e, $02, $84
@song0ref3859:
	.byte $20, $8f, $00, $91, $20, $8f, $22, $91, $24, $8f, $00, $91, $20, $85, $89, $00, $91, $22, $8f, $00, $91, $22, $8f, $24
	.byte $91, $1f, $8f, $00, $91, $1b, $85, $89, $00, $91, $20, $8f, $00, $91, $20, $8f, $22, $91, $24, $8f, $00, $91, $2c, $85
	.byte $89, $00, $91, $29, $c9, $27, $ab, $89, $00, $91, $4e, $02
	.byte $41, $2a
	.word @song0ref3859
	.byte $1f, $8f, $00, $91, $1b, $85, $89, $00, $91, $1d, $c9, $29, $ab, $00, $ff, $95, $7f, $80
@song0ref3940:
	.byte $40, $0b, $a3, $40, $0a, $a3, $01, $c9, $40, $0b, $a3, $40, $0a, $a3, $01, $c9, $40, $0b, $a3, $40, $0a, $a3, $01, $c9
	.byte $40, $0b, $a3, $40, $0a, $a3, $01, $c9, $40, $0c, $a3, $40, $0b, $a3, $02, $c9, $40, $0c, $a3, $40, $0b, $a3, $02, $c9
	.byte $40, $0c, $a3, $40, $0b, $a3, $02, $c9, $40, $0c, $a3, $40, $0b, $a3, $02, $c9
	.byte $41, $30
	.word @song0ref3940
	.byte $01, $ff, $95, $ff, $97, $44, $a3, $00, $ef, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $ff, $97, $89, $00, $91
	.byte $78, $8c
@song0ref4033:
	.byte $24, $8f, $00, $91, $24, $8f, $25, $91, $27, $8f, $00, $91, $24, $85, $89, $00, $91, $25, $8f, $00, $91, $25, $8f, $27
	.byte $91, $22, $8f, $00, $91, $1b, $85, $89, $00, $91, $24, $8f, $00, $91, $24, $8f, $25, $91, $27, $8f, $00, $91, $2c, $85
	.byte $89, $00, $91, $29, $c9, $27, $ab, $89, $00, $91
	.byte $41, $2a
	.word @song0ref4033
	.byte $24, $8f, $00, $91, $20, $85, $89, $00, $91, $22, $c9, $2e, $ab, $00, $ff, $95, $ff, $97, $ff, $97, $ff, $97, $ff, $97
	.byte $94
@song0ref4119:
	.byte $37, $a3, $37, $91, $39, $8f, $3b, $a3, $37, $a3, $39, $a3, $39, $91, $3b, $8f, $36, $a3, $32, $a3, $37, $a3, $37, $91
	.byte $39, $8f, $3b, $a3, $40, $4f, $a3, $40, $4e, $c9, $3e, $c9
	.byte $41, $1a
	.word @song0ref4119
	.byte $36, $a3, $32, $a3, $34, $c9, $40, $4c, $c9, $00, $ff, $95, $7f
	.byte $41, $24
	.word @song0ref3634
	.byte $41, $20
	.word @song0ref3659
@song0ch6loop:
	.byte $ff, $97, $42
	.word @song0ch6loop
@song1ch0:
@song1ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $78, $4e, $02, $96
@song1ref9:
	.byte $34, $a1, $36, $a1, $2f, $a1, $31, $a1, $2d, $95, $2a, $95, $47, $32, $a1, $2d, $a1, $34, $a1, $2d, $a1, $2c, $95, $28
	.byte $95, $47, $34, $a1, $36, $a1, $2f, $a1, $31, $a1, $2d, $95, $2a, $95, $47, $32, $a1, $2d, $a1, $34, $a1, $39, $a1, $38
	.byte $ad, $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47, $76
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
	.byte $47
	.byte $41, $2e
	.word @song1ref9
@song1ref115:
	.byte $47
@song1ref116:
	.byte $2a, $85, $00, $81, $2a, $85, $00, $81, $31, $85, $00, $81, $31, $85, $00, $81, $2f, $85, $00, $81, $2f, $85, $00, $81
	.byte $31, $85, $00, $81, $31, $85, $00, $81, $2d, $85, $00, $81, $2d, $85, $00, $81, $31, $85, $00, $81, $31, $85, $00, $81
	.byte $2c, $91, $00, $99, $47, $2c, $85, $00, $81, $2c, $85, $00, $81, $2d, $85, $00, $81, $2d, $85, $00, $81, $2c, $85, $00
	.byte $81, $2c, $85, $00, $81, $2d, $85, $00, $81, $2d, $85, $00, $81, $2c, $c5, $31, $95, $47, $af, $2a, $c5, $28, $c5
	.byte $41, $55
	.word @song1ref115
	.byte $ad, $2f, $ad, $47, $34, $a1, $33, $83, $32, $83, $31, $ff, $8d
	.byte $41, $5d
	.word @song1ref115
	.byte $41, $55
	.word @song1ref115
	.byte $ad, $2f, $ad, $47, $34, $a1, $33, $83, $32, $83, $31, $ff, $8d, $47, $7a, $4e, $01
	.byte $41, $5d
	.word @song1ref116
	.byte $41, $55
	.word @song1ref115
	.byte $ad, $2f, $ad, $47, $34, $a1, $33, $83, $32, $83, $31, $ff, $8d
	.byte $41, $5d
	.word @song1ref115
@song1ref272:
	.byte $47, $2a, $c5, $25, $95, $28, $95, $2a, $95, $2d, $ad, $47, $2c, $ad, $28, $ad, $2a, $dd, $47, $af, $2a, $ff, $89, $00
	.byte $81, $47, $7e, $4e, $01
	.byte $41, $5d
	.word @song1ref116
	.byte $41, $55
	.word @song1ref115
	.byte $ad, $2f, $ad, $47, $34, $a1, $33, $83, $32, $83, $31, $ff, $8d
	.byte $41, $5d
	.word @song1ref115
	.byte $41, $16
	.word @song1ref272
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $8b, $78, $4e, $01, $96
@song1ref335:
	.byte $34, $a1, $36, $a1, $2f, $a1, $31, $a1, $2d, $95, $2a, $89, $8b, $32, $a1, $2d, $a1, $34, $a1, $2d, $a1, $2c, $95, $28
	.byte $89, $8b, $34, $a1, $36, $a1, $2f, $a1, $31, $a1, $2d, $95, $2a, $89, $8b, $32, $a1, $2d, $a1, $34, $a1, $39, $a1, $38
	.byte $a1, $8b
	.byte $41, $32
	.word @song1ref335
	.byte $41, $31
	.word @song1ref335
@song1ref391:
	.byte $4e, $02, $28, $a1, $2a, $a1, $23, $a1, $25, $a1, $21, $95, $1e, $95, $26, $a1, $21, $a1, $28, $a1, $21, $a1, $20, $95
	.byte $1c, $95, $4e, $02, $28, $a1, $2a, $a1, $23, $a1, $25, $a1, $21, $95, $1e, $95, $26, $a1, $21, $a1, $28, $a1, $2d, $a1
	.byte $2c, $ad
	.byte $41, $2e
	.word @song1ref391
	.byte $41, $2e
	.word @song1ref391
	.byte $41, $2e
	.word @song1ref391
	.byte $7f, $4e, $00, $80
@song1ref454:
	.byte $19, $a1, $1e, $a1, $21, $95, $1e, $dd, $ff, $8d, $00, $20, $95, $21, $95, $23, $ff, $bd, $dd, $00, $20, $95, $21, $95
	.byte $23, $95, $25, $95, $20, $ff, $bd, $df, $44, $dd, $20, $ff, $8d, $1e, $ad, $19, $ff, $bd
	.byte $41, $1c
	.word @song1ref454
	.byte $28, $ff, $bd, $ff, $8d, $00, $2a, $ad, $25, $ff, $bd, $ff, $bf
	.byte $41, $2a
	.word @song1ref454
	.byte $41, $1c
	.word @song1ref454
	.byte $28, $ff, $bd, $ff, $8d, $00, $2a, $ad, $25, $ff, $bd, $ff, $8f, $00, $a1, $7a, $86
@song1ref535:
	.byte $0e, $89, $ff, $83, $0b, $b9, $d3, $0b, $e9, $a3, $09, $ff, $8d, $0e, $89, $ff, $83, $10, $b9, $d3, $14, $e9, $a3, $10
	.byte $ff, $8d
	.byte $41, $19
	.word @song1ref535
	.byte $99, $4e, $01, $80
@song1ref568:
	.byte $1e, $85, $00, $81, $1e, $85, $00, $81, $25, $85, $00, $81, $25, $85, $00, $81, $23, $85, $00, $81, $23, $85, $00, $81
	.byte $25, $85, $00, $81, $25, $85, $00, $81, $21, $85, $00, $81, $21, $85, $00, $81, $25, $85, $00, $81, $25, $85, $00, $81
	.byte $20, $91, $00, $99, $20, $85, $00, $81, $20, $85, $00, $81, $21, $85, $00, $81, $21, $85, $00, $81, $20, $85, $00, $81
	.byte $20, $85, $00, $81, $21, $85, $00, $81, $21, $85, $00, $81, $20, $c5, $25, $95, $af, $1e, $c5, $1c, $c5
	.byte $41, $55
	.word @song1ref568
	.byte $ad, $23, $ad, $28, $a1, $27, $83, $26, $83, $25, $ff, $8d
	.byte $41, $5d
	.word @song1ref568
@song1ref679:
	.byte $1e, $c5, $19, $95, $1c, $95, $1e, $95, $21, $ad, $20, $ad, $1c, $ad, $1e, $dd, $af, $1e, $ff, $89, $00, $81, $7e, $4e
	.byte $01
	.byte $41, $5d
	.word @song1ref568
	.byte $41, $55
	.word @song1ref568
	.byte $ad, $23, $ad, $28, $a1, $27, $83, $26, $83, $25, $ff, $8d
	.byte $41, $5d
	.word @song1ref568
	.byte $41, $16
	.word @song1ref679
	.byte $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
@song1ref732:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $7f, $90, $06, $ff, $bd, $06, $ff, $8d, $04, $ad, $06, $ff, $bd, $06, $ff, $8d
	.byte $40, $0b, $95, $04, $95, $06, $ff, $bd, $06, $ff, $8d, $04, $ad, $06, $ff, $bd, $0e, $a1, $10, $a1, $17, $95, $00, $dd
	.byte $84
@song1ref781:
	.byte $1e, $89, $1e, $89, $19, $89, $19, $89, $1e, $89, $1e, $89, $19, $89
@song1ref795:
	.byte $1e, $89, $00, $89, $19, $89, $1c, $89, $1e, $89, $21, $89, $20, $89, $1c, $89, $19, $89, $1a, $89
@song1ref815:
	.byte $1a, $89, $15, $89, $15, $89, $1a, $89, $1a, $89, $15, $89, $1c, $89, $00, $89, $17, $89, $1c, $89, $1e, $89, $21, $89
	.byte $20, $89, $1c, $89, $17, $89
	.byte $41, $22
	.word @song1ref781
@song1ref848:
	.byte $00, $89, $1a, $89, $15, $89, $00, $89, $15, $89, $1a, $89, $1c, $89, $00, $89, $17, $89, $1c, $89, $1e, $89, $21, $89
	.byte $20, $89, $1c, $89, $17, $89
	.byte $41, $40
	.word @song1ref781
	.byte $41, $22
	.word @song1ref781
	.byte $41, $1e
	.word @song1ref848
	.byte $41, $40
	.word @song1ref781
	.byte $41, $22
	.word @song1ref781
	.byte $41, $1e
	.word @song1ref848
	.byte $41, $40
	.word @song1ref781
	.byte $41, $22
	.word @song1ref781
	.byte $41, $1e
	.word @song1ref848
	.byte $1e, $89, $1e, $85, $00, $81, $19, $89, $19, $89, $1e, $89, $1e, $85, $00, $81, $19, $85, $00, $81
	.byte $41, $32
	.word @song1ref795
@song1ref928:
	.byte $1e, $89, $1e, $85, $00, $81, $19, $89, $19, $89, $1e, $89, $1e, $85, $00, $81, $19, $85, $00, $81, $1e, $89, $00, $89
	.byte $19, $89, $1c, $89, $1e, $89, $21, $89, $20, $89, $1c, $89, $19, $89, $1a, $89
	.byte $41, $1e
	.word @song1ref848
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref815
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref848
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref815
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref848
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref815
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref848
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref815
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref848
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref815
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref848
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref815
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref848
	.byte $41, $28
	.word @song1ref928
	.byte $41, $1e
	.word @song1ref815
	.byte $41, $28
	.word @song1ref928
	.byte $00, $89, $1a, $89, $15, $89, $00, $89, $15, $89, $1a, $89, $1c, $9b, $00, $83, $1e, $9b, $00, $83, $20, $9b, $86
@song1ref1075:
	.byte $15, $83, $ff, $89, $14, $b3, $d9, $12, $e3, $a9, $12, $ff, $8d, $15, $83, $ff, $89, $17, $b3, $d9, $1c, $e3, $a9, $19
	.byte $ff, $8d
	.byte $41, $19
	.word @song1ref1075
	.byte $93, $84
@song1ref1106:
	.byte $0e, $ff, $8d, $10, $ad, $df, $0d, $dd, $af, $12, $ff, $8d, $0e, $ff, $8d, $10, $ad, $df, $0d, $dd, $af, $12, $ff, $8d
	.byte $41, $18
	.word @song1ref1106
	.byte $41, $18
	.word @song1ref1106
	.byte $41, $17
	.word @song1ref1106
	.byte $89, $00, $81, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $df, $70, $50, $02, $c0, $84
	.byte $01, $dd, $ff, $bb, $83, $00, $ff, $bd
@song1ref1178:
	.byte $7f, $86
@song1ref1180:
	.byte $40, $09, $89, $43, $40, $0a, $89, $43, $40, $0b, $89, $43, $40, $0c, $89, $7c, $88, $40, $0c, $95, $40, $03, $89, $01
	.byte $89, $40, $0c, $95, $40, $03, $89, $01, $89, $40, $0c, $95, $40, $03
@song1ref1218:
	.byte $89, $01, $89, $40, $0c, $95, $40, $02, $89, $01, $89, $40, $0c, $95, $40, $02, $89, $01, $89, $40, $0c, $95, $40, $02
	.byte $89, $01, $89, $40, $0c, $95, $40, $02
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $89, $01, $89
	.byte $41, $2f
	.word @song1ref1178
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $89, $01, $89
	.byte $41, $2f
	.word @song1ref1178
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $15
	.word @song1ref1218
	.byte $00, $ad, $86
@song1ref1391:
	.byte $40, $0c, $dd, $00, $ad, $40, $0c, $ad, $af, $00, $ad, $40, $0c, $dd, $00, $ad, $40, $0c, $dd, $00, $ad, $40, $0c, $dd
	.byte $00, $ad, $40, $0c, $ad, $af, $00, $ad, $40, $0c, $dd, $00, $ad, $40, $0c, $dd, $00, $ad
	.byte $41, $22
	.word @song1ref1391
	.byte $7f
	.byte $41, $2f
	.word @song1ref1180
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $89, $01, $89
	.byte $41, $2f
	.word @song1ref1178
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $89, $01, $89
	.byte $41, $2f
	.word @song1ref1178
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $41, $18
	.word @song1ref1218
	.byte $89, $01, $89, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $51, $00, $01, $ff, $bd, $ff, $bf, $51, $00, $01, $ff, $bd, $ff, $bf, $51, $00
	.byte $01, $ff, $bd, $ff, $bf, $51, $00, $01, $ff, $bd, $00, $ff, $bd
@song1ref1550:
	.byte $51, $00, $01, $ff, $bd
@song1ref1555:
	.byte $ff, $bf, $51, $00, $01, $ff, $bd, $ff, $bf, $51, $00, $01, $ff, $bd, $ff, $bf, $51, $00, $01, $ff, $bd, $ff, $bf, $51
	.byte $00, $01, $ff, $bd, $ff, $bf, $51, $00, $01, $ff, $bd, $ff, $bf, $51, $00, $01, $ff, $bd, $ff, $bf, $51, $00, $01, $ff
	.byte $bd, $c7, $51, $00, $14, $f5
	.byte $41, $26
	.word @song1ref1550
	.byte $41, $23
	.word @song1ref1555
	.byte $ff, $bf, $51, $00, $01, $ff, $bd, $c7, $51, $00, $14, $f5, $00, $ff, $bd, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff
	.byte $bf, $51, $00, $04, $ff, $81, $00, $89, $51, $00, $05, $ad, $d3, $00, $89, $51, $00, $05, $c5, $51, $00, $06, $95, $a3
	.byte $00, $89, $51, $00, $05, $b9, $00, $89, $51, $00, $05, $b9, $00, $89, $51, $00, $06, $ff, $81, $00, $89, $51, $00, $05
	.byte $ad, $d3, $00, $89, $51, $00, $05, $c5, $51, $00, $06, $95, $a3, $00, $89, $51, $00, $06, $ff, $81, $00, $89
@song1ref1709:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $41, $16
	.word @song1ref1709
	.byte $ff, $bf, $c7, $51, $00, $14, $f5, $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $7f, $90, $12, $ff, $bd, $ff, $bf, $12, $ff, $bd, $ff, $8f, $00, $ad, $12, $ff
	.byte $bd, $ff, $bf, $12, $ff, $bd, $02, $a1, $04, $a1, $0b, $95, $00, $dd, $78, $4e, $02, $96
@song1ref1787:
	.byte $1c, $a1, $1e, $a1, $17, $a1, $19, $a1, $15, $95, $12, $95, $1a, $a1, $15, $a1, $1c, $a1, $15, $a1, $14, $95, $10, $95
	.byte $4e, $02, $1c, $a1, $1e, $a1, $17, $a1, $19, $a1, $15, $95, $12, $95, $1a, $a1, $15, $a1, $1c, $a1, $21, $a1, $20, $ad
	.byte $4e, $02
	.byte $41, $2e
	.word @song1ref1787
	.byte $4e, $02
	.byte $41, $2e
	.word @song1ref1787
	.byte $4e, $02
	.byte $41, $2e
	.word @song1ref1787
	.byte $7f, $4e, $00, $80
@song1ref1854:
	.byte $25, $a1, $2a, $a1, $2d, $95, $2a, $dd, $ff, $8d, $00, $2c, $95, $2d, $95, $2f, $ff, $bd, $dd, $00, $2c, $95, $2d, $95
	.byte $2f, $95, $31, $95, $2c, $ff, $bd, $df, $44, $dd, $2c, $ff, $8d, $2a, $ad, $25, $ff, $bd
	.byte $41, $1c
	.word @song1ref1854
	.byte $34, $ff, $bd, $ff, $8d, $00, $36, $ad, $31, $ff, $bd, $ff, $bf
	.byte $41, $2a
	.word @song1ref1854
	.byte $41, $1c
	.word @song1ref1854
	.byte $34, $ff, $bd, $ff, $8d, $00, $36, $ad, $31, $ff, $bd, $ff, $8f, $00, $ad, $7a, $86
@song1ref1935:
	.byte $19, $ff, $8d, $17, $ad, $df, $17, $dd, $af, $15, $c5, $10, $c5, $19, $ff, $8d, $1c, $ad, $df, $20, $dd, $af, $1c, $ad
	.byte $20, $ad, $1c, $ad
	.byte $41, $1c
	.word @song1ref1935
	.byte $4e, $01, $80
@song1ref1969:
	.byte $36, $85, $00, $81, $36, $85, $00, $81, $3d, $85, $00, $81, $3d, $85, $00, $81, $3b, $85, $00, $81, $3b, $85, $00, $81
	.byte $3d, $85, $00, $81, $3d, $85, $00, $81, $39, $85, $00, $81, $39, $85, $00, $81, $3d, $85, $00, $81, $3d, $85, $00, $81
	.byte $38, $91, $00, $99, $38, $85, $00, $81, $38, $85, $00, $81, $39, $85, $00, $81, $39, $85, $00, $81, $38, $85, $00, $81
	.byte $38, $85, $00, $81, $39, $85, $00, $81, $39, $85, $00, $81, $38, $c5, $3d, $95, $af, $36, $c5, $34, $c5
	.byte $41, $55
	.word @song1ref1969
	.byte $ad, $3b, $ad, $40, $4c, $a1, $3f, $83, $3e, $83, $3d, $ff, $8d
	.byte $41, $5d
	.word @song1ref1969
@song1ref2081:
	.byte $36, $c5, $31, $95, $34, $95, $36, $95, $39, $ad, $38, $ad, $34, $ad, $36, $dd, $af, $36, $ff, $89, $00, $81, $7e
	.byte $41, $5d
	.word @song1ref1969
	.byte $41, $55
	.word @song1ref1969
	.byte $ad, $3b, $ad, $40, $4c, $a1, $3f, $83, $3e, $83, $3d, $ff, $8d
	.byte $41, $5d
	.word @song1ref1969
	.byte $41, $16
	.word @song1ref2081
	.byte $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
	.byte $41, $25
	.word @song1ref732
	.byte $02, $a1, $04, $a1, $0b, $95, $00, $dd, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $8c, $1c, $ff, $bd, $ff, $bf, $17, $ff, $bd, $ff, $bf, $1c, $ff, $bd, $ff, $bf, $17
@song1ref2177:
	.byte $ff, $bd, $ff, $bf, $19, $ff, $bd, $ff, $8f, $00, $ad, $1e, $f5, $1c, $c5, $df, $00, $dd, $19, $ff, $bd, $df, $00, $dd
	.byte $19, $ff, $bd, $ff, $bf, $19, $ff, $bd, $ff, $8f, $00, $ad, $1e, $f5, $1c, $c5, $df, $00, $dd, $1c, $ff, $bd, $ff, $8f
	.byte $00, $ad, $19
	.byte $41, $28
	.word @song1ref2177
	.byte $ff, $8f, $00, $ad, $1c, $ff, $bd, $ff, $8f, $00, $ad, $19, $ff, $bd, $ff, $b9, $7a, $86
@song1ref2249:
	.byte $12, $83, $ff, $89, $10, $b3, $d9, $0d, $e3, $a9, $0e, $ff, $8d, $12, $83, $ff, $89, $14, $b3, $d9, $19, $e3, $a9, $15
	.byte $ff, $8d
	.byte $41, $19
	.word @song1ref2249
	.byte $93, $78, $88
@song1ref2281:
	.byte $1e, $89, $1a, $89, $17, $89, $00, $89, $1e, $89, $1a, $89, $17, $89, $00, $89, $1e, $89, $1a, $89, $17, $89, $00, $89
	.byte $20, $89, $1c, $89, $17, $89, $00, $89, $20, $89, $1c, $89, $17, $89, $00, $89, $20, $89, $1c, $89, $17, $89, $00, $89
	.byte $1e, $89, $1c, $89, $17, $89, $00, $89, $1e, $89, $1c, $89, $17, $89, $00, $89, $1e, $89, $1c, $89, $17, $89, $00, $89
	.byte $21, $89, $1e, $89, $19, $89, $00, $89, $21, $89, $1e, $89, $19, $89, $00, $89, $17, $89, $15, $89, $14, $89, $00, $89
	.byte $41, $48
	.word @song1ref2281
@song1ref2380:
	.byte $25, $89, $21, $89, $1e, $89, $00, $89, $25, $89, $21, $89, $1e, $89, $00, $89, $19, $89, $17, $89, $15, $89, $00, $89
	.byte $41, $60
	.word @song1ref2281
	.byte $41, $48
	.word @song1ref2281
	.byte $41, $18
	.word @song1ref2380
	.byte $41, $60
	.word @song1ref2281
	.byte $41, $48
	.word @song1ref2281
	.byte $41, $18
	.word @song1ref2380
	.byte $41, $60
	.word @song1ref2281
	.byte $41, $48
	.word @song1ref2281
	.byte $41, $18
	.word @song1ref2380
	.byte $42
	.word @song1ch6loop
@song2ch0:
@song2ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $4e, $01, $84, $2d, $91, $2b, $91, $2a, $91, $00, $91, $26
	.byte $91, $28, $91, $2a, $91, $00, $91, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $4e, $01, $84, $15, $91, $00, $b9, $78, $1a, $91, $7f, $00, $b9, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $ff, $9f, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $ff, $9f, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $ff, $9f, $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $cf, $78, $84, $17, $91, $00, $b9, $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $ff, $9f, $42
	.word @song2ch6loop
