; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_undertale_ost_1=music_data_undertale_ost_1
.endif

music_data_undertale_ost_1:
	.byte 4
	.word @instruments
	.word @samples-5
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6 ; 00 : Enemy Approching
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,@song1ch5,@song1ch6 ; 01 : Ghost Fight
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,@song2ch5,@song2ch6 ; 02 : Determination
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,@song3ch5,@song3ch6 ; 03 : Home
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_undertale_ost_1
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env15,@env11,@env12,@env0 ; 00 : Echo
	.word @env1,@env18,@env12,@env10 ; 01 : Fade vibrate
	.word @env7,@env11,@env12,@env0 ; 02 : Basic
	.word @env4,@env11,@env12,@env0 ; 03 : Kicks
	.word @env9,@env11,@env12,@env13 ; 04 : Fade
	.word @env7,@env11,@env14,@env17 ; 05 : Vibrate
	.word @env5,@env11,@env16,@env0 ; 06 : Lead
	.word @env6,@env11,@env14,@env0 ; 07 : Lead 2

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $04,$cf,$00,$01,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$12
@env2:
	.byte $00,$cc,$ce,$cf,$cf,$ce,$cd,$cc,$cc,$cd,$00,$02
@env3:
	.byte $00,$c2,$bf,$c1,$be,$00,$01
@env4:
	.byte $00,$c8,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env5:
	.byte $0e,$cf,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$00,$0b,$c3,$05,$c2,$06,$c1,$06,$c1,$00,$14
@env6:
	.byte $0c,$c6,$c7,$c8,$c8,$c8,$c9,$ca,$02,$c9,$00,$05,$c7,$c5,$c4,$c3,$c2,$00,$10
@env7:
	.byte $00,$cf,$7f,$00,$02
@env8:
	.byte $00,$c0,$bf,$be,$bf,$c0,$c1,$c2,$c1,$00,$01
@env9:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env10:
	.byte $00,$c4,$c2,$c0,$00,$03
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $7f,$00,$00
@env13:
	.byte $00,$bd,$be,$bf,$be,$bf,$c0,$00,$06
@env14:
	.byte $c2,$7f,$00,$00
@env15:
	.byte $00,$cf,$06,$c0,$c0,$c8,$05,$c0,$c0,$c4,$05,$c0,$c0,$c2,$04,$c0,$c1,$00,$10
@env16:
	.byte $c1,$7f,$00,$00
@env17:
	.byte $00,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$00,$01
@env18:
	.byte $c0,$c1,$00,$00
@env19:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env20:
	.byte $c0,$cc,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$69,$0d,$40,$01 ; 00 napsta_ds5 (Pitch:13)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$69,$0f,$40,$01 ; 01 napsta_ds5 (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$5c,$0b,$40,$01 ; 02 napsta_f5 (Pitch:11)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$5c,$0c,$40,$01 ; 03 napsta_f5 (Pitch:12)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$5c,$0d,$40,$01 ; 04 napsta_f5 (Pitch:13)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$5c,$0e,$40,$01 ; 05 napsta_f5 (Pitch:14)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$57,$0b,$40,$01 ; 06 napsta_fs5 (Pitch:11)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$57,$0c,$40,$01 ; 07 napsta_fs5 (Pitch:12)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$57,$0d,$40,$01 ; 08 napsta_fs5 (Pitch:13)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$57,$0e,$40,$01 ; 09 napsta_fs5 (Pitch:14)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$57,$0f,$40,$01 ; 0a napsta_fs5 (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$52,$0e,$40,$01 ; 0b napsta_g5 (Pitch:14)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$52,$0f,$40,$01 ; 0c napsta_g5 (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $9d, $78, $80, $1c, $83, $7c, $1d, $81, $7f
@song0ref14:
	.byte $1e, $a3, $00, $91, $1e, $a5, $00, $8f, $47, $48, .lobyte(@env19), .hibyte(@env19), $1c, $a5, $00, $91, $84, $1c, $8f
	.byte $00, $91, $1c, $a5, $48, .lobyte(@env0), .hibyte(@env0), $49, $00, $8f, $47
	.byte $41, $0d
	.word @song0ref5
	.byte $47, $84, $1d, $83, $1e, $b3, $1c, $83, $1d, $9d, $1b, $91, $19, $a3, $47, $4e, $02, $00, $9b, $80, $1c, $83, $1d, $81
	.byte $41, $08
	.word @song0ref14
	.byte $47, $1c, $a5, $00, $91, $1c, $8f, $00, $91, $1c, $a5, $00, $8f, $47, $9d, $1c, $83, $1d, $81, $1e, $a3, $00, $4e, $01
	.byte $87, $1e, $83, $1f, $81, $20, $a5, $00, $87, $4e, $00, $87, $47, $84, $22, $a5, $23, $87, $00, $87, $25, $b7, $00, $a3
@song0ref122:
	.byte $47, $00, $9b
@song0ref125:
	.byte $80, $25, $83, $26, $81, $27, $a3, $00, $91, $23, $b7, $47, $84, $1d, $a5, $1e, $91, $1d, $a3, $1b, $91, $1d, $91, $20
	.byte $8f, $47, $00, $9b, $80, $20, $83, $21, $81, $22, $a3, $00, $91, $23, $b7, $47, $7c, $48, .lobyte(@env19), .hibyte(@env19)
	.byte $4e, $02, $84, $20, $a5, $27, $91, $25, $cb, $48, .lobyte(@env0), .hibyte(@env0), $49, $00, $8d, $7f, $81, $47, $4e
	.byte $00, $9d
	.byte $41, $14
	.word @song0ref125
@song0ref193:
	.byte $1e, $8f, $47, $20, $91, $1e, $91, $1d, $91, $00
@song0ref203:
	.byte $8f, $1d, $91, $1b, $91, $19, $91, $00, $8f, $47, $17, $91, $00, $91, $1b, $91, $00, $8f, $1d, $a5, $19, $91, $16, $8f
	.byte $41, $2e
	.word @song0ref122
	.byte $41, $14
	.word @song0ref125
	.byte $41, $20
	.word @song0ref193
	.byte $47
@song0ref237:
	.byte $00, $9b, $80
@song0ref240:
	.byte $1f, $83, $20, $81, $21, $a3, $00, $87, $1a, $83, $1b, $81, $1c, $b7, $47, $84
@song0ref256:
	.byte $21, $a5, $25, $91, $23, $a3, $21, $91, $20, $91, $21, $8f, $47, $00, $a5, $4e, $02, $1e, $91, $1d, $8f, $1b, $91, $1e
	.byte $91, $1d, $91, $1b, $8f, $47, $48, .lobyte(@env8), .hibyte(@env8), $1d, $a5, $1e, $91, $20, $db, $48, .lobyte(@env0)
	.byte .hibyte(@env0), $49, $81, $47, $4e, $00
	.byte $41, $10
	.word @song0ref237
	.byte $47
	.byte $41, $0d
	.word @song0ref256
@song0ref310:
	.byte $9b, $21, $83, $22, $81, $23, $a3, $00, $91, $1e, $b3, $22, $81, $47, $23, $a5, $27, $91, $25, $b7, $00, $a3, $47, $00
	.byte $9b
	.byte $41, $2f
	.word @song0ref240
	.byte $47, $4e, $00
	.byte $41, $10
	.word @song0ref237
	.byte $47
	.byte $41, $0d
	.word @song0ref256
	.byte $41, $12
	.word @song0ref310
	.byte $a3, $23, $91, $25, $91, $27, $8f, $47, $28, $a5, $2c, $91, $2a, $dd, $47, $00, $91, $2a, $91, $2a, $91, $2a, $8f, $27
	.byte $91, $27, $91, $23, $91, $00, $8f, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $4d, $0e, $4e, $01, $a7, $82
@song0ref392:
	.byte $16, $44, $8f, $00, $a3, $16, $44, $8f, $00, $a3, $14, $44, $8f, $00, $a5, $14, $44, $85, $00, $99, $14, $87, $44, $9b
	.byte $00, $8f, $4d, $0e, $4e, $01, $a7
	.byte $41, $0a
	.word @song0ref392
	.byte $16, $44, $a3, $00, $91, $14, $44, $a1, $00, $b7, $4d, $0e, $4e, $01, $a7
	.byte $41, $1a
	.word @song0ref392
	.byte $4d, $00, $4e, $02, $9d, $84, $13, $14, $81, $15, $16, $17, $87, $16, $15, $81, $14, $13, $00, $8f, $4e, $01, $89, $17
	.byte $18, $81, $19, $1a, $1b, $87, $1a, $19, $81, $18, $17, $00, $93, $17, $81, $18, $19, $1a, $1b, $1c, $1d, $1e, $b9, $20
	.byte $b7, $00, $a3
@song0ref495:
	.byte $00, $a5, $80, $23, $a3, $00, $91, $20, $b7, $84, $19, $a5, $1b, $91, $19, $a3, $17, $91, $19, $91, $1d, $8f, $00, $a5
	.byte $80, $1e, $a3, $00, $91, $20, $b7, $7c, $84, $1c, $a5, $23, $91, $22, $cb, $00, $8d, $7f, $81
	.byte $41, $12
	.word @song0ref495
	.byte $1b
	.byte $41, $09
	.word @song0ref203
@song0ref545:
	.byte $19, $91, $17, $91, $16, $91, $00, $8f, $12, $91, $00, $91, $17, $91, $00, $8f, $19, $a5, $16, $91, $12, $8f
	.byte $41, $25
	.word @song0ref495
	.byte $41, $12
	.word @song0ref495
	.byte $1b
	.byte $41, $09
	.word @song0ref203
	.byte $41, $16
	.word @song0ref545
@song0ref580:
	.byte $00, $a5, $80
@song0ref583:
	.byte $1c, $a3, $00, $91, $19, $b7, $84, $1c, $a5, $00, $91, $1c, $a3, $00, $b7, $a7, $12, $91, $00, $a3, $12, $91, $00, $a3
	.byte $11, $a5, $12, $91, $14, $dd
	.byte $41, $11
	.word @song0ref580
@song0ref616:
	.byte $80, $1e, $a3, $00, $91, $19, $b7, $1e, $a5, $00, $91, $20, $b7, $00, $a3, $00, $a5
	.byte $41, $1d
	.word @song0ref583
	.byte $41, $11
	.word @song0ref580
	.byte $41, $0b
	.word @song0ref616
	.byte $a3, $00, $a5, $25, $8f, $00, $a5, $25, $91, $27, $dd, $00, $91, $27, $91, $27, $91, $27, $8f, $23, $91, $23, $91, $1e
	.byte $91, $00, $8f, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $84
@song0ref674:
	.byte $14, $85, $00, $89, $14, $83, $00, $8b
@song0ref682:
	.byte $14, $8d, $00, $81
@song0ref686:
	.byte $14, $83, $00, $89, $14, $87, $00, $87, $14
@song0ref695:
	.byte $8d, $00, $81, $14, $85, $00, $89, $14, $83, $00, $89, $81, $14, $8b, $00, $83
	.byte $41, $11
	.word @song0ref686
	.byte $41, $0a
	.word @song0ref695
@song0ref717:
	.byte $87, $81, $14, $85, $00, $89, $14, $85, $00, $89
	.byte $41, $13
	.word @song0ref682
@song0ref730:
	.byte $87, $14, $85, $00, $87, $0b, $91, $12, $91, $17, $91, $0b, $a3, $12, $91, $19, $9b, $00, $85
	.byte $41, $25
	.word @song0ref674
	.byte $41, $11
	.word @song0ref686
	.byte $41, $0a
	.word @song0ref695
	.byte $41, $0a
	.word @song0ref717
	.byte $41, $13
	.word @song0ref682
	.byte $41, $0b
	.word @song0ref730
	.byte $0d, $a3, $12, $91, $1a, $9b, $00, $85
	.byte $41, $20
	.word @song0ref674
@song0ref778:
	.byte $17, $91, $1e, $91, $23, $91, $19, $a3, $20, $91, $1d, $91, $25, $8f
	.byte $41, $20
	.word @song0ref674
@song0ref795:
	.byte $10, $91, $17, $91, $1d, $91, $12, $a3, $17, $91, $19, $91, $12, $8f
	.byte $41, $20
	.word @song0ref674
	.byte $41, $0e
	.word @song0ref778
@song0ref815:
	.byte $17, $8f, $00, $93, $23, $8f, $00, $19, $8d, $00, $93, $27, $8f, $00, $93, $19, $8d, $00, $17, $99, $00, $89, $27, $8f
	.byte $00, $91, $25, $8f, $00, $19, $8f, $00, $1b, $8f, $00, $12, $8d, $00
	.byte $41, $20
	.word @song0ref674
	.byte $41, $0e
	.word @song0ref778
	.byte $41, $20
	.word @song0ref674
	.byte $41, $0e
	.word @song0ref795
	.byte $41, $20
	.word @song0ref674
	.byte $41, $0e
	.word @song0ref778
	.byte $41, $26
	.word @song0ref815
	.byte $41, $20
	.word @song0ref674
	.byte $41, $20
	.word @song0ref674
@song0ref880:
	.byte $09, $91, $0b, $91, $0d, $91, $06, $8f, $09, $91, $12, $91, $10, $91, $0b, $8f, $0d, $91, $0b, $91, $0d, $91, $0b, $8f
	.byte $11, $91, $16, $91, $14, $91, $13, $8f
	.byte $41, $20
	.word @song0ref674
	.byte $41, $20
	.word @song0ref674
@song0ref918:
	.byte $16, $85, $00, $89, $16, $83, $00, $8b, $16, $8d, $00, $81, $16, $83, $00, $89, $16, $87, $00, $87, $16, $8d, $00, $81
	.byte $16, $85, $00, $89, $16, $83, $00, $89
	.byte $41, $0c
	.word @song0ref918
@song0ref953:
	.byte $18, $8f, $00, $91, $16, $91, $18, $91, $13, $8f
	.byte $41, $20
	.word @song0ref674
	.byte $41, $20
	.word @song0ref674
	.byte $41, $20
	.word @song0ref880
	.byte $41, $20
	.word @song0ref674
	.byte $41, $20
	.word @song0ref674
	.byte $41, $20
	.word @song0ref918
	.byte $41, $08
	.word @song0ref918
	.byte $1a, $91
	.byte $41, $08
	.word @song0ref953
	.byte $1a, $8f, $14, $91, $00, $91, $14, $91, $00, $dd, $93, $80
@song0ref1001:
	.byte $12, $91, $12, $91, $12, $8f, $0f, $91, $0f, $91, $0b, $91, $00, $8f, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $86
@song0ref1020:
	.byte $14, $87, $00, $87, $21, $87, $00, $87, $14, $87, $00, $87, $21, $87, $00, $85
	.byte $41, $10
	.word @song0ref1020
	.byte $41, $10
	.word @song0ref1020
	.byte $41, $10
	.word @song0ref1020
	.byte $41, $10
	.word @song0ref1020
	.byte $41, $10
	.word @song0ref1020
@song0ref1051:
	.byte $18, $8d, $00, $81
@song0ref1055:
	.byte $15, $83, $00, $81, $15, $83, $00, $81, $15, $83, $00, $8b, $18, $8f, $00, $91
	.byte $41, $08
	.word @song0ref1055
	.byte $18, $91, $21, $87, $00, $85
	.byte $41, $10
	.word @song0ref1020
	.byte $41, $10
	.word @song0ref1020
	.byte $41, $10
	.word @song0ref1020
	.byte $41, $10
	.word @song0ref1020
	.byte $41, $10
	.word @song0ref1020
	.byte $41, $10
	.word @song0ref1020
	.byte $41, $14
	.word @song0ref1051
@song0ref1101:
	.byte $16, $83, $00, $81, $16, $83, $00, $81
	.byte $41, $08
	.word @song0ref1101
	.byte $16, $83, $00, $81, $16, $81, $00, $81
@song0ref1120:
	.byte $88, $1f, $87, $20, $87, $21, $87, $22, $87, $23, $91, $86
@song0ref1132:
	.byte $14, $83, $21, $81, $00, $85, $14, $83, $21, $81, $00, $87, $14, $83, $21, $81, $00, $87, $1a, $43, $19, $83, $43, $18
	.byte $85, $00, $81
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
@song0ref1189:
	.byte $14, $83, $21, $81, $00, $85
@song0ref1195:
	.byte $16, $1f, $85, $00, $87, $16, $1f, $85, $00, $87
@song0ref1205:
	.byte $19
@song0ref1206:
	.byte $43, $1e, $81, $43, $1f, $81, $43, $20, $85, $00, $16, $00, $8d
	.byte $41, $15
	.word @song0ref1195
	.byte $41, $15
	.word @song0ref1195
	.byte $16
	.byte $41, $09
	.word @song0ref1206
	.byte $8f
	.byte $41, $0b
	.word @song0ref1205
	.byte $41, $23
	.word @song0ref1120
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $1b
	.word @song0ref1189
	.byte $41, $15
	.word @song0ref1195
	.byte $41, $15
	.word @song0ref1195
	.byte $16
	.byte $41, $09
	.word @song0ref1206
	.byte $8f
	.byte $41, $0b
	.word @song0ref1205
	.byte $41, $23
	.word @song0ref1120
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $14, $83, $21, $81, $00, $85
	.byte $41, $23
	.word @song0ref1120
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $14, $83, $21, $81, $00, $85
	.byte $41, $23
	.word @song0ref1120
	.byte $41, $19
	.word @song0ref1132
	.byte $41, $19
	.word @song0ref1132
	.byte $14, $83, $21, $81, $00, $85
@song0ref1388:
	.byte $14, $87, $00, $9b, $14, $87, $00, $99
	.byte $41, $08
	.word @song0ref1388
@song0ref1399:
	.byte $14, $87, $00, $87, $14, $87, $00, $87, $14, $87, $00, $87, $14, $87, $00, $85
	.byte $41, $0b
	.word @song0ref1399
	.byte $99, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1423:
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $ff, $9b, $ff, $9b, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $a7, $80
@song0ref1468:
	.byte $17, $91, $00, $a3, $17, $91, $00, $a3, $15, $a5, $00, $91, $15, $8f, $00, $91, $15, $a5, $00, $8d, $4e, $00, $81, $a7
	.byte $41, $08
	.word @song0ref1468
	.byte $17, $a5, $00, $91, $16, $a3, $00, $b5, $4e, $02, $81, $a7
	.byte $41, $15
	.word @song0ref1468
	.byte $ff, $9b, $bb, $84, $1c, $b7, $00, $a3
@song0ref1518:
	.byte $00, $a5, $80
@song0ref1521:
	.byte $20, $a3, $00, $91, $1b, $b7, $00, $ff, $99, $a7, $1b, $a3, $00, $91, $1b, $b7, $78, $4e, $02, $84, $16, $91, $15, $91
	.byte $13, $91, $11, $8f, $16, $91, $15, $91, $13, $91, $11, $8b, $4e, $00, $81, $7f, $81
	.byte $41, $0b
	.word @song0ref1518
	.byte $ff, $9b, $ff, $9b, $00, $a5
	.byte $41, $22
	.word @song0ref1521
	.byte $41, $0b
	.word @song0ref1518
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $ff, $9b, $e1, $17, $91, $00, $91, $1b, $8f, $00, $a5, $20, $91, $1e, $dd, $78, $4e, $02, $00, $91
	.byte $41, $0c
	.word @song0ref1001
	.byte $4e, $00, $00, $8d, $7f, $81, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $74, $84
@song0ref1636:
	.byte $38, $91, $3a, $91, $3b, $91, $3d, $8f, $3a, $91, $3b, $91, $3d, $91, $38, $8f, $3d, $91, $3b, $91, $3a, $91, $3f, $8f
	.byte $3d, $91, $40, $4e, $91, $40, $4d, $91, $3d, $8f
	.byte $41, $0e
	.word @song0ref1636
	.byte $3f, $8f, $40, $50, $91, $40, $4e, $91, $3f, $91, $40, $4e, $8f, $3f, $91, $3d, $91, $3b, $91, $3a, $8f
	.byte $41, $0e
	.word @song0ref1636
	.byte $3f, $8f, $3d, $91, $3b, $91, $38, $91, $3b, $8f, $3a, $91, $38, $91, $35, $91, $31, $8d, $7f, $81, $00, $ff, $99
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $41, $08
	.word @song0ref1423
	.byte $ff, $9b, $ff, $9b, $78, $93, $80, $0f, $91, $0f, $91, $0f, $8f, $0b, $91, $0b, $91, $06, $91, $00, $8d, $7f, $81, $42
	.word @song0ch6loop
@song1ch0:
@song1ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $73, $8a
@song1ref7:
	.byte $14, $8b, $00, $91, $17, $89, $00, $91, $19, $89, $00, $91, $14, $89, $00, $91, $17, $8b, $00, $8b, $19, $8b, $47, $1a
	.byte $93, $00, $89, $1b, $87, $1e, $a7, $14, $8b, $00, $91, $17, $89, $00, $91, $19, $89, $00, $85, $47, $8b, $14, $89, $00
	.byte $91, $17, $8b, $00, $8b, $1a, $8b, $1b, $93, $00, $89, $1e, $87, $22, $a7, $47
	.byte $41, $2f
	.word @song1ref7
	.byte $12, $8b, $13, $8b, $00, $8b, $14, $a9, $00, $a7, $47
	.byte $41, $3d
	.word @song1ref7
	.byte $47
	.byte $41, $2b
	.word @song1ref7
@song1ref92:
	.byte $1c, $89, $00, $91, $1b, $8b, $1c, $8b, $00, $8b, $1b, $89, $1e, $9d, $00, $a7, $47
	.byte $41, $3d
	.word @song1ref7
	.byte $47
	.byte $41, $2b
	.word @song1ref7
	.byte $41, $10
	.word @song1ref92
	.byte $47
	.byte $41, $3d
	.word @song1ref7
	.byte $47
	.byte $41, $2b
	.word @song1ref7
	.byte $41, $10
	.word @song1ref92
	.byte $47, $76, $8c
@song1ref133:
	.byte $1c, $9f, $23, $93, $22, $87, $00, $91, $23, $89, $22, $87, $00, $93, $1c, $9d, $23, $87, $47, $8b, $22, $87, $00, $93
	.byte $23, $89, $22, $87, $00, $91, $1e, $9f, $1b, $87, $00, $93, $19, $87, $00, $87, $47, $17, $89, $00, $93, $1b, $ff, $87
	.byte $47
	.byte $41, $1e
	.word @song1ref133
@song1ref185:
	.byte $89, $00, $93, $1f, $87, $00, $93, $20, $87, $00, $87, $47, $1b, $89, $00, $83, $17, $89, $00, $8b, $14, $fb, $00, $47
	.byte $41, $27
	.word @song1ref133
	.byte $47, $0b, $89, $00, $93, $1b, $ff, $87, $47
	.byte $41, $1e
	.word @song1ref133
	.byte $41, $16
	.word @song1ref185
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
@song1ref231:
	.byte $ff, $ab, $ff, $ab, $ff, $ab, $ff, $ab, $ff, $ab, $ff, $ab
	.byte $41, $0c
	.word @song1ref231
	.byte $74, $8c
@song1ref248:
	.byte $2c, $89, $00, $87, $33, $89, $00, $93, $2a, $87, $2c, $87, $00, $93
@song1ref262:
	.byte $29, $87, $00, $89, $2c, $87, $00, $93, $28, $87, $2c, $87, $00, $93, $36, $89, $00, $93, $33, $87, $00, $91
	.byte $41, $0d
	.word @song1ref248
	.byte $87, $8b
	.byte $41, $0e
	.word @song1ref262
	.byte $33, $89, $00, $93, $32, $87, $00, $91
	.byte $41, $24
	.word @song1ref248
	.byte $2a, $89, $00, $87, $2c, $89, $00, $93, $25, $87, $2a, $87, $00, $87, $8b, $2c, $87, $00, $93, $2f, $89, $31, $87, $00
	.byte $91, $2e, $83, $2f, $83, $2e, $81, $2f, $83, $2e, $83, $2f, $83, $2e, $81, $2f, $83, $2e, $83, $2f, $83, $2e, $81, $2f
	.byte $83, $2e, $81, $2f, $83, $2e, $81, $2f, $83
	.byte $41, $24
	.word @song1ref248
	.byte $41, $0d
	.word @song1ref248
	.byte $87, $8b
	.byte $41, $0e
	.word @song1ref262
	.byte $33, $89, $00, $93, $32, $87, $00, $91
	.byte $41, $23
	.word @song1ref248
	.byte $87, $2e, $87, $2f, $89, $00, $83, $2c, $89, $00, $81, $28, $87, $00, $93, $27, $87, $00, $87, $8b, $28, $87, $00, $93
	.byte $2e, $89, $00, $87, $2b, $87, $00, $93, $2c, $87, $00, $bd
	.byte $41, $0c
	.word @song1ref231
	.byte $41, $0c
	.word @song1ref231
	.byte $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $41, $0c
	.word @song1ref231
	.byte $84
@song1ref432:
	.byte $14, $89, $00, $87, $14, $89, $13, $87, $00, $93, $12, $87, $00, $93, $11, $87, $00, $93, $10, $89, $00, $91, $0b, $87
	.byte $00, $93, $0a, $89, $00, $93, $07, $87, $00, $91
	.byte $41, $0d
	.word @song1ref432
@song1ref469:
	.byte $87, $8b, $11, $87, $00, $93, $10, $89, $00, $91, $14, $87, $00, $93, $13, $89, $00, $93, $0f, $87, $00, $91
	.byte $41, $22
	.word @song1ref432
@song1ref494:
	.byte $0d, $89, $00, $87, $0d, $89, $0b, $87, $00, $93, $0d, $87, $00, $87, $8b, $0e, $87, $00, $93, $0f, $89, $00, $91, $11
	.byte $87, $00, $93, $13, $89, $00, $93, $0f, $87, $00, $91
	.byte $41, $22
	.word @song1ref432
	.byte $41, $0d
	.word @song1ref432
	.byte $41, $16
	.word @song1ref469
	.byte $41, $22
	.word @song1ref432
	.byte $41, $23
	.word @song1ref494
	.byte $41, $22
	.word @song1ref432
	.byte $41, $0d
	.word @song1ref432
	.byte $41, $16
	.word @song1ref469
	.byte $41, $22
	.word @song1ref432
	.byte $41, $16
	.word @song1ref494
	.byte $87, $0f, $87, $13, $87, $00, $89, $14, $c7
@song1ref568:
	.byte $10, $89, $00, $87, $10, $89, $0e, $87, $00, $93, $0b, $87, $00, $93, $07, $87, $00, $93, $04, $89, $00, $91, $07, $87
	.byte $00, $93, $0a, $89, $00, $93, $10, $87, $00, $91, $14, $89, $00, $87, $14, $89, $08, $87, $00, $93, $12, $87, $00, $87
	.byte $0f, $89, $00, $93, $0d, $87, $14, $89, $00, $87, $14, $87, $08, $87, $00, $93, $12, $89, $00, $87, $0f, $89, $00, $91
	.byte $0d, $87
	.byte $41, $4a
	.word @song1ref568
	.byte $41, $4a
	.word @song1ref568
	.byte $41, $47
	.word @song1ref568
	.byte $9b, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $41, $0c
	.word @song1ref231
	.byte $76, $86
@song1ref661:
	.byte $06, $83, $43, $05, $81, $43, $04, $85, $00, $ad, $06, $81, $43, $05, $81, $43, $04, $85, $00, $ad, $06, $83, $43, $05
	.byte $81, $43, $04, $85, $00, $95, $95, $06, $83, $43, $05, $81, $43, $04, $85, $00, $ab
	.byte $41, $0f
	.word @song1ref661
@song1ref705:
	.byte $81, $ab, $06, $83, $43, $05, $81, $43, $04, $85, $00, $ab, $06, $83, $43, $05, $81, $43, $04, $85, $00, $ab
	.byte $41, $21
	.word @song1ref661
	.byte $41, $0f
	.word @song1ref661
	.byte $41, $12
	.word @song1ref705
@song1ref736:
	.byte $05
@song1ref737:
	.byte $89
@song1ref738:
	.byte $00, $87, $05, $89, $09, $87, $00, $8b, $0d, $83, $00
@song1ref749:
	.byte $05
@song1ref750:
	.byte $87, $00, $87, $05, $89, $0d, $81, $00, $91
@song1ref759:
	.byte $0d, $83, $00, $05, $89, $00, $87, $05, $87, $0d, $81, $00, $83, $8d, $05, $85
@song1ref775:
	.byte $0d, $89, $00, $87, $05, $85, $0d, $81, $09, $87, $00, $91
	.byte $41, $0d
	.word @song1ref736
	.byte $0d
	.byte $41, $15
	.word @song1ref750
	.byte $91, $0d, $83, $00
	.byte $41, $0c
	.word @song1ref775
	.byte $41, $0d
	.word @song1ref736
	.byte $0d, $87
	.byte $41, $0c
	.word @song1ref738
@song1ref809:
	.byte $89, $00, $87, $05, $87, $09, $87, $00, $89, $05, $0d, $83, $00
	.byte $41, $0c
	.word @song1ref775
	.byte $0d
	.byte $41, $12
	.word @song1ref737
@song1ref829:
	.byte $09, $87, $00, $8b, $0d, $83, $00
@song1ref836:
	.byte $0d, $89, $00, $87, $05, $87, $0d, $81, $00
@song1ref845:
	.byte $8f
@song1ref846:
	.byte $05, $0d, $83, $00
@song1ref850:
	.byte $0d, $89, $00, $87, $0d, $83, $00
@song1ref857:
	.byte $0d, $81, $09, $87, $00, $91
@song1ref863:
	.byte $0d
@song1ref864:
	.byte $89, $00, $87, $05, $89, $0d, $81, $00, $91, $0d, $83, $00, $0d
	.byte $41, $12
	.word @song1ref750
	.byte $09, $87, $00, $89
	.byte $41, $17
	.word @song1ref846
@song1ref887:
	.byte $09, $87, $00, $8b, $0d, $83, $00, $0d, $87, $00, $87, $05, $89
	.byte $41, $0d
	.word @song1ref829
	.byte $09, $87, $00, $89, $05, $0d, $83, $00
	.byte $41, $0c
	.word @song1ref775
	.byte $41, $0d
	.word @song1ref863
	.byte $41, $0d
	.word @song1ref749
	.byte $0d
	.byte $41, $0d
	.word @song1ref809
	.byte $41, $0d
	.word @song1ref850
	.byte $41, $0d
	.word @song1ref736
	.byte $0d, $87, $00, $87, $05, $89
	.byte $41, $22
	.word @song1ref829
	.byte $05
	.byte $41, $0d
	.word @song1ref864
	.byte $87, $00, $87, $05, $89
	.byte $41, $10
	.word @song1ref829
	.byte $83, $00, $89, $05, $0d, $83, $00
	.byte $41, $0c
	.word @song1ref775
	.byte $0d
	.byte $41, $19
	.word @song1ref737
	.byte $0d
	.byte $41, $0d
	.word @song1ref809
	.byte $41, $1a
	.word @song1ref850
	.byte $05, $87, $00, $87, $05, $89
	.byte $41, $10
	.word @song1ref829
	.byte $83, $00, $89, $05, $0d, $83, $00
	.byte $41, $0c
	.word @song1ref775
	.byte $0d
	.byte $41, $12
	.word @song1ref737
	.byte $09, $87, $00, $8b
	.byte $41, $0c
	.word @song1ref759
	.byte $41, $1f
	.word @song1ref845
	.byte $05, $87, $00, $87, $05, $89
	.byte $41, $10
	.word @song1ref829
	.byte $83, $8b, $05, $0d, $83, $00
	.byte $41, $0c
	.word @song1ref775
	.byte $05
	.byte $41, $0c
	.word @song1ref864
	.byte $41, $0d
	.word @song1ref749
	.byte $41, $12
	.word @song1ref836
	.byte $05, $85
	.byte $41, $13
	.word @song1ref857
	.byte $05, $87
	.byte $41, $0c
	.word @song1ref738
	.byte $41, $0d
	.word @song1ref809
	.byte $41, $13
	.word @song1ref850
	.byte $41, $0d
	.word @song1ref887
	.byte $0d, $81, $00, $91, $0d, $83, $00, $0d
	.byte $41, $0d
	.word @song1ref809
	.byte $41, $0d
	.word @song1ref850
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $41, $0c
	.word @song1ref231
	.byte $41, $0c
	.word @song1ref231
	.byte $0d, $d3, $00, $bf, $0a, $91, $00, $93, $06, $93, $09, $89, $01, $b1, $00, $bd, $ff, $ab, $09, $bf, $06, $bd, $0c, $a7
	.byte $95, $02, $bd, $0c, $93, $00, $89, $01, $93, $00, $87, $0d, $91, $00, $89, $01, $93, $00, $87, $0b, $93, $02, $87, $00
	.byte $8f, $0c, $a1, $02, $89, $0c, $91, $02, $87, $0c, $93, $00
@song1ref1136:
	.byte $89, $09, $93, $00, $87, $01, $91, $00, $89, $07, $93, $00, $87, $09, $93, $00, $87, $01, $87, $8b, $05, $93, $00, $87
	.byte $02, $89, $0c, $91, $02, $87, $0c, $89, $00, $87, $0c
	.byte $41, $11
	.word @song1ref1136
	.byte $06, $93, $05, $9d, $02, $89, $0c, $91, $02, $87, $0c, $93, $00, $89, $0d, $93, $00, $87, $06, $91, $00, $89, $09, $93
	.byte $00, $87, $06, $93, $09, $87, $00, $87, $8b, $06, $9d, $00, $89, $09, $87, $00, $87, $06, $87, $0a, $93, $06, $89, $09
	.byte $93, $00, $87, $01, $91, $00, $89, $03, $93, $00, $87, $04, $89, $00, $87, $08, $87, $00, $93, $01, $bd, $00, $87
	.byte $41, $0c
	.word @song1ref231
	.byte $41, $0c
	.word @song1ref231
	.byte $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $41, $0c
	.word @song1ref231
	.byte $41, $0c
	.word @song1ref231
	.byte $76, $4e, $02, $8c, $2c, $b5, $00, $f1, $eb, $26, $89, $25, $87, $00, $89, $23, $87, $25, $91, $27, $89, $1e, $93, $20
	.byte $87, $23, $93, $20, $87, $1e, $87, $00, $89, $2c, $9d, $28, $83, $27, $83, $26, $87, $25, $87, $23, $87, $20, $bf, $22
	.byte $bd, $23, $a7, $95, $22, $bd, $23, $93, $00, $89, $19, $93, $00, $87, $1b, $91, $00, $89, $1c, $93, $00, $87, $20, $93
	.byte $22, $87, $00, $93, $1f, $c7, $00, $ff, $a9, $ab, $28, $89, $27, $91, $28, $87, $27, $89, $00, $87, $27, $89, $23, $93
	.byte $00, $87, $20, $91, $00, $89, $1c, $93, $00, $87, $23, $93, $00, $87, $25, $93, $22, $c7, $00, $ff, $a9, $b7, $23, $87
	.byte $00, $87, $25, $87, $26, $93, $25, $89, $23, $93, $00, $87, $20, $91, $00, $89, $1b, $93, $00, $87, $1e, $93, $1f, $87
	.byte $00, $93, $1b, $c7, $74
@song1ref1410:
	.byte $1c, $9f, $26, $93, $25, $87, $00, $91, $26, $89, $25, $87, $00, $93, $1c, $9d, $26, $87, $8b, $25, $87, $00, $93, $26
	.byte $89, $25, $87, $00, $91, $23, $9f, $20, $87, $00, $93, $20, $87, $00, $87, $1e, $89, $00, $93, $20, $ff, $87
	.byte $41, $1e
	.word @song1ref1410
@song1ref1459:
	.byte $89, $00, $93, $25, $87, $00, $93, $26, $87, $00, $87, $27, $89, $00, $87, $2a, $89, $00, $87, $2c, $fb, $00
	.byte $41, $2e
	.word @song1ref1410
	.byte $41, $1e
	.word @song1ref1410
	.byte $41, $16
	.word @song1ref1459
	.byte $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
	.byte $41, $0c
	.word @song1ref231
	.byte $41, $0c
	.word @song1ref231
	.byte $41, $0c
	.word @song1ref231
	.byte $ff, $ab, $ab, $76, $8c, $31, $89, $2f, $87, $00, $87, $31, $87, $2f, $89, $00, $87, $2f, $89, $2c, $93, $00, $87, $27
	.byte $91, $00, $89, $23, $93, $00, $87, $2c, $93, $00, $87, $2e, $93, $2b, $9d, $00, $a7, $ff, $ab, $b7, $2f, $87, $00, $87
	.byte $31, $87, $32, $93, $31, $89, $2f, $93, $00, $87, $2c, $91, $00, $89, $28, $93, $00, $87, $2b, $93, $2e, $9d, $2c, $9d
	.byte $00, $a7, $28, $9f, $2f, $93, $25, $87, $00, $91, $26, $89, $2e, $87, $00, $93, $28, $9d, $26, $87, $8b, $25, $87, $00
	.byte $93, $26, $89, $2e, $87, $00, $91, $23, $9f, $27, $87, $00, $93, $25, $87, $00, $87, $1b, $89, $00, $93, $27, $ff, $87
	.byte $23, $9f, $26
@song1ref1626:
	.byte $93, $25, $87, $00, $91, $2f, $89, $25, $87, $00, $93, $28, $9d, $26
@song1ref1640:
	.byte $87, $8b, $2e, $87, $00, $93, $2f, $89, $2e, $87, $00, $91, $27, $89, $00, $93, $2a, $87, $00, $93, $2c, $87, $00, $87
	.byte $2f, $89, $00, $87, $31, $89, $00, $87, $33, $fb, $00, $23, $9f, $2f, $93, $2e, $87, $00, $91, $2f, $89, $2e, $87, $00
	.byte $93, $23, $9d, $26, $87, $8b, $25, $87, $00, $93, $2f, $89, $2e, $87, $00, $91, $23, $9f, $20, $87, $00, $93, $1e, $87
	.byte $00, $87, $1b, $89, $00, $93, $27, $ff, $87, $28, $9f, $2f
	.byte $41, $0d
	.word @song1ref1626
	.byte $2f
	.byte $41, $23
	.word @song1ref1640
	.byte $42
	.word @song1ch6loop
@song2ch0:
@song2ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $8e
@song2ref6:
	.byte $2b, $9d, $2a, $9b, $28, $9d, $26, $9b, $28, $9d, $23, $9b, $47, $25, $9d, $00, $9b, $21, $9d, $00, $9b, $28, $9d, $2a
	.byte $9b, $47, $2b, $9d, $00, $9b, $2d, $9d, $00, $9b, $32, $9d, $00, $9b, $47, $2f, $ff, $a9, $00, $8b, $47
	.byte $41, $14
	.word @song2ref6
@song2ref54:
	.byte $1c, $9d, $1e, $9b, $47, $1f, $9d, $00, $9b
@song2ref63:
	.byte $1e, $9d, $00, $9b, $1a, $9d, $00, $9b, $47, $1c, $ff, $a9, $00, $8b, $47
	.byte $41, $29
	.word @song2ref6
	.byte $47
	.byte $41, $14
	.word @song2ref6
	.byte $41, $15
	.word @song2ref54
@song2ref88:
	.byte $47, $2d, $9d, $2b, $9b, $29, $9d, $28, $9b, $26, $9d, $29, $9b, $47, $28, $9d, $00, $9b, $23, $9d, $00, $9b, $23, $9d
	.byte $28, $9b
	.byte $41, $0d
	.word @song2ref88
@song2ref117:
	.byte $db, $00, $9b, $1c, $9d, $21, $9b, $47, $26, $9d, $25, $9b, $23, $9d, $21, $9b, $23, $9d, $25, $9b, $47, $23, $9d, $00
	.byte $9b, $1c, $9d, $00, $9b, $1c, $9d, $1e, $9b, $47, $1f, $9d, $00, $9b, $24, $9d, $00, $9b, $28, $bb, $47, $27, $ff, $a9
	.byte $00, $8b
	.byte $41, $18
	.word @song2ref88
	.byte $41, $0d
	.word @song2ref88
	.byte $41, $23
	.word @song2ref117
	.byte $41, $0d
	.word @song2ref63
	.byte $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $78, $4e, $02, $00, $9d, $84, $10, $9b, $13, $9d, $15, $9b, $17, $9d, $13, $9b, $00, $9d
@song2ref201:
	.byte $15, $9b, $19, $9d, $1c, $9b, $19, $9d, $15, $9b, $00, $9d, $10, $9b, $12, $9d, $13, $9b, $15, $9d, $12, $9b, $13, $9d
	.byte $12, $9b, $10, $9d, $0e, $9b, $10, $9d, $0b
@song2ref234:
	.byte $9b, $4e, $02, $00, $9d, $10, $9b, $13, $9d, $15, $9b, $17, $9d, $13, $9b, $00, $9d, $0d, $9b, $10, $9d, $13, $9b, $17
	.byte $9d, $15, $9b, $00, $9d, $10, $9b, $15, $9d, $17, $9b, $12, $9d, $0e, $9b, $13, $9d, $12, $9b, $10, $9d, $0e, $9b, $10
	.byte $9d, $12
	.byte $41, $0f
	.word @song2ref234
	.byte $41, $50
	.word @song2ref201
	.byte $0b
@song2ref291:
	.byte $9b, $00, $9d, $0c, $9b, $15, $9d, $13, $9b, $17, $9d, $15, $9b, $13, $9d, $15, $9b, $10, $9d, $12, $9b, $0e, $9d, $10
	.byte $41, $0e
	.word @song2ref291
	.byte $f9, $00, $bb, $9f, $04, $9b, $0d, $9d, $0b, $9b, $15, $9d, $13, $9b, $10, $9d, $12, $9b, $13, $9d, $12, $9b, $13, $9d
	.byte $15, $9b, $17, $bb, $1c, $bb, $17, $bb, $15, $9d, $13, $9b, $12, $9d, $10, $9b, $0f, $9d, $12
	.byte $41, $18
	.word @song2ref291
	.byte $41, $0e
	.word @song2ref291
	.byte $f9, $00, $bb, $ff, $b9, $ff, $b9, $ff, $b9, $ff, $b9, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $84, $10, $f9, $13, $bb, $15, $ff, $b7, $0c, $bb, $0e, $bb, $12
@song2ref395:
	.byte $bb, $10, $f9, $0b, $bb, $10, $f9, $13, $bb, $15, $ff, $b7, $0c, $bb, $0e, $bb, $0b
	.byte $41, $10
	.word @song2ref395
	.byte $12, $bb, $10, $f9, $0b, $bb, $10, $f9, $13, $bb, $15, $f9, $15, $bb, $0c, $bb, $0e, $bb, $0b, $bb, $10, $ff, $b7
@song2ref438:
	.byte $11, $f9, $13, $bb, $10, $ff, $b7, $11, $f9, $1a, $bb, $10, $f9, $00, $bb, $15, $f9, $15, $bb, $10, $f9, $0e, $bb, $0c
	.byte $f9, $16, $bb, $17, $bb, $15, $bb, $0b, $bb
	.byte $41, $11
	.word @song2ref438
	.byte $00, $bb, $10, $f9, $00, $bb, $0c, $bb, $0e, $bb, $0b, $bb, $10, $ff, $a9, $00, $8b, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
@song2ref495:
	.byte $ff, $b9, $ff, $b9, $ff, $b9, $ff, $b9, $ff, $b9, $ff, $b9, $ff, $b9
	.byte $41, $0e
	.word @song2ref495
	.byte $41, $0e
	.word @song2ref495
	.byte $41, $0e
	.word @song2ref495
	.byte $ff, $b9, $ff, $b9, $ff, $b9, $ff, $b9, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $41, $0e
	.word @song2ref495
	.byte $41, $0e
	.word @song2ref495
	.byte $41, $0e
	.word @song2ref495
	.byte $41, $0e
	.word @song2ref495
	.byte $ff, $b9, $ff, $b9, $ff, $b9, $ff, $b9, $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $41, $0e
	.word @song2ref495
	.byte $41, $0e
	.word @song2ref495
	.byte $ff, $b9, $ff, $b9, $00, $9d, $8e, $28, $9b, $26, $9d, $24, $9b, $23, $9d, $26, $9b, $23
@song2ref578:
	.byte $9d, $00, $9b, $1f, $9d, $00, $9b, $1f, $9d, $23, $9b
@song2ref589:
	.byte $00, $9d, $28, $9b, $26, $9d, $24, $9b, $23, $9d, $26, $9b, $23, $db, $00, $9b, $17, $9d, $1c, $9b, $23, $9d, $21, $9b
	.byte $1f, $9d, $1e, $9b, $1f, $9d, $21, $9b, $1f, $9d, $00, $9b, $17, $9d, $00, $9b, $17, $9d, $1a, $9b, $1c, $9d, $00, $9b
	.byte $1f, $9d, $00, $9b, $24, $bb, $23, $ff, $a9, $00, $8b
	.byte $41, $0d
	.word @song2ref589
	.byte $41, $3b
	.word @song2ref578
	.byte $1a, $9d, $00, $9b, $15, $9d, $00, $9b, $17, $ff, $a9, $00, $8b, $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $7a, $00, $8d, $8e
@song2ref675:
	.byte $2b, $9d, $2a, $9b, $28, $9d, $26, $9b, $28, $9d, $23, $8b, $8f, $25, $9d, $00, $9b, $21, $9d, $00, $9b, $28, $9d, $2a
	.byte $8b, $8f, $2b, $9d, $00, $9b, $2d, $9d, $00, $9b, $32, $9d, $00, $8b, $8f, $2f, $ff, $a7, $00, $8d
	.byte $41, $15
	.word @song2ref675
@song2ref722:
	.byte $1c, $9d, $1e, $8b, $8f, $1f, $9d, $00, $9b
@song2ref731:
	.byte $1e, $9d, $00, $9b, $1a, $9d, $00, $8b, $8f, $1c, $ff, $99, $00, $8b, $00, $8d
	.byte $41, $2c
	.word @song2ref675
	.byte $41, $15
	.word @song2ref675
	.byte $41, $17
	.word @song2ref722
@song2ref756:
	.byte $8f
@song2ref757:
	.byte $2d, $9d, $2b, $9b, $29, $9d, $28, $9b, $26, $9d, $29, $8b, $8f, $28, $9d, $00, $9b, $23, $9d, $00, $9b, $23, $9d, $28
	.byte $8b
	.byte $41, $0f
	.word @song2ref756
@song2ref785:
	.byte $db, $00, $9b, $1c, $9d, $21, $8b, $8f, $26, $9d, $25, $9b, $23, $9d, $21, $9b, $23, $9d, $25, $8b, $8f, $23, $9d, $00
	.byte $9b, $1c, $9d, $00, $9b, $1c, $9d, $1e, $8b, $8f, $1f, $9d, $00, $9b, $24, $9d, $00, $9b, $28, $ab, $8f, $27, $ff, $a7
	.byte $00, $8d
	.byte $41, $19
	.word @song2ref757
	.byte $41, $0f
	.word @song2ref756
	.byte $41, $26
	.word @song2ref785
	.byte $41, $0e
	.word @song2ref731
	.byte $42
	.word @song2ch6loop
@song3ch0:
@song3ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $00, $a7, $8c
@song3ref8:
	.byte $11, $93, $16, $a7
@song3ref12:
	.byte $18
@song3ref13:
	.byte $bb, $11, $93, $16, $a7, $18, $91, $47, $00, $a7, $11, $93, $16, $a7, $1d
	.byte $41, $0d
	.word @song3ref13
	.byte $41, $0e
	.word @song3ref12
	.byte $7f, $50, $fd, $00, $1d, $ff, $db, $83, $7f, $00, $8d, $47, $00, $a7
	.byte $41, $12
	.word @song3ref8
	.byte $18, $bb, $11, $93, $16, $a7, $18, $91, $47, $00, $a7, $13, $93, $16, $a7, $1d, $bb, $13, $93, $16, $a7, $18, $91, $47
	.byte $00, $a7, $22, $93, $21, $a7, $1d, $bb, $16, $93, $18, $a7, $16, $91, $47, $00, $a7
	.byte $41, $12
	.word @song3ref8
	.byte $41, $0e
	.word @song3ref12
	.byte $18, $bb, $1d, $93, $18, $a7, $16, $91, $47, $00, $a7, $11, $93, $16, $a7, $18, $bb, $1d, $93, $11
@song3ref118:
	.byte $a7, $16, $91, $47, $00, $a7, $11, $93, $16, $a7, $18, $bb, $11, $93, $16, $a7, $1d, $91, $47, $00, $a7, $11, $93, $16
	.byte $a7, $1d, $bb, $1b, $93, $1a
	.byte $41, $0f
	.word @song3ref118
	.byte $18, $91, $47, $00, $a7, $16, $93, $18, $a7, $00, $1d, $8f, $50, $fe, $00, $ff, $ff, $97, $00, $9d, $7f, $83
@song3ref173:
	.byte $47, $ab, $11, $8f, $00, $16, $a7, $00, $18, $b9, $00, $16, $8f, $00, $11, $b9, $00, $47, $ab, $15, $8f, $00, $18, $a7
	.byte $00, $1d, $b9, $00, $18, $8f, $00, $15, $b9, $00, $47, $bf, $14, $a7, $00, $19, $b9, $00, $14, $8f, $00, $0d, $bb, $47
	.byte $00, $a9, $13, $8f, $00, $16, $a7, $00, $18, $8d, $00, $11, $a7, $00, $05, $8f, $00, $0c, $a7, $11, $8f, $00, $47, $ab
	.byte $11, $8f, $00, $16, $bb, $18, $bd, $11, $b9, $00, $47, $bf, $16, $a7, $00, $18, $b9, $00, $16, $8f, $00, $18, $b9, $00
	.byte $47, $bf, $14, $bb, $13, $bd, $18, $bb
@song3ref277:
	.byte $47, $00, $a9, $11, $8f, $00, $16, $a7, $00, $1a, $8d, $00, $18, $a7, $00, $16, $8f, $00, $11, $b9, $00
	.byte $41, $1e
	.word @song3ref173
	.byte $a5, $00, $0e, $91, $47, $00, $a7, $14, $91, $00, $19, $e7, $19, $91, $14, $b7, $00, $81, $47, $ab, $13, $8f, $00, $18
	.byte $a7, $00, $1d, $b9, $00, $05, $8f, $00, $11, $b9, $00, $47, $ab, $11, $8f, $00, $16, $e5, $00, $11, $8f, $00, $0a, $bb
	.byte $47, $00, $bd, $0e, $bb, $00, $c7, $02, $b1, $47, $00, $fb, $0f, $f9, $00
	.byte $41, $14
	.word @song3ref277
	.byte $47, $ff, $fb, $47, $ff, $ef, $47, $ff, $fb, $47, $ff, $fb, $47, $ff, $fb, $47, $ff, $ef, $47, $ff, $fb, $47, $07, $fb
	.byte $05, $fb, $47, $00, $ff, $f9, $47, $ff, $fb, $47, $ff, $fb, $47, $ff, $fb, $47, $50, $fe, $00, $40, $0c, $ff, $f9, $47
	.byte $7f, $50, $fe, $00, $05, $ff, $f9, $47, $7f, $50, $fe, $00, $06, $ff, $f9, $47, $7f, $07, $fb, $05, $fb, $47, $50, $fe
	.byte $00, $03, $ff, $f9, $47, $fd, $7f, $05, $fb, $47, $50, $fe, $00, $03, $ff, $f9, $47, $fd, $7f, $05, $fb, $47, $50, $fe
	.byte $00, $03, $ff, $f9, $47, $7f, $50, $fe, $00, $02, $ff, $f9, $47, $7f, $50, $fd, $00, $01, $ff, $bb, $7f, $40, $0c, $bb
	.byte $47, $bf, $50, $fe, $00, $40, $05, $ff, $b9, $47, $fd, $00, $ed, $7f, $8d, $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $7f, $50, $fe, $00, $8c, $0a, $ff, $f5, $83, $7f, $50, $fe, $00, $0e, $ff, $f5, $83, $7f, $50, $ff, $00, $0d, $ff, $f9
	.byte $ff, $ff, $db, $7f, $50, $fe, $00, $0a, $ff, $f9, $7f, $50, $fe, $00, $0e, $ff, $f9, $7f, $50, $ff, $00, $0f, $ff, $f9
	.byte $ff, $fb, $7f, $50, $fe, $00, $0a, $ff, $f9, $7f, $50, $fe, $00, $0e, $ff, $f9, $7f, $50, $fe, $00, $0d, $ff, $f9, $7f
	.byte $0d, $e1, $85, $0c, $ff, $8f, $50, $fe, $00, $0a, $ff, $f9, $7f, $50, $fe, $00, $0e, $ff, $f9, $7f, $50, $fe, $00, $0d
	.byte $ff, $f9, $7f, $0c, $e1, $50, $fe, $00, $85, $05, $ff, $ff, $cd, $7f, $50, $fe, $00, $0a, $ff, $f9, $7f, $50, $fe, $00
	.byte $0e, $ff, $f9, $7f, $50, $fe, $00, $0d, $ff, $f7, $00, $7f, $50, $fe, $00, $0c, $ff, $db, $00, $9b, $7f, $50, $fe, $00
	.byte $0a, $ff, $f9, $7f, $50, $fe, $00, $0e, $ff, $f9, $7f, $0d, $fb, $0c, $e7, $50, $fe, $00, $0a, $91, $ff, $fb, $7f, $50
	.byte $fe, $00, $0a, $ff, $f9, $7f, $50, $fe, $00, $0e, $ff, $f9, $7f, $50, $fd, $00, $0d, $ff, $e5, $7f, $50, $fe, $00, $0c
	.byte $91, $ff, $dd, $00, $9b, $7f, $50, $fe, $00, $0a, $ff, $f9, $7f, $50, $fe, $00, $02, $ff, $f9, $7f, $03, $fb, $05, $e1
	.byte $50, $fe, $00, $85, $0a, $91, $ff, $fb, $7f, $0f, $bd, $16, $bb, $0f, $bd, $16, $bb, $0f, $b9, $16, $b9, $0f, $a5, $16
	.byte $cd, $0e, $bd, $16, $bb, $0e, $bd, $16, $bb, $0d, $bd, $14, $bb, $0d, $a7, $14, $d1, $0c, $bd, $13, $bb, $0c, $bd, $13
	.byte $bb, $11, $b9, $18, $b9, $11, $a5, $18, $cd, $12, $bd, $50, $fd, $00, $18, $ff, $b9, $7f, $50, $fc, $00, $1a, $fb, $7f
	.byte $50, $fc, $00, $18, $fb, $7f, $0f, $bd, $16, $bb, $0f, $bd, $16, $bb, $0f, $bd, $16, $bb, $0f, $bd, $16, $bb, $0e, $bd
	.byte $16, $bb, $0e, $bd, $16, $bb, $0d, $bd, $16, $bb, $0d, $a7, $16, $d1, $50, $fe, $00, $16, $ff, $f9, $7f, $50, $fe, $00
	.byte $18, $ff, $f9, $7f, $50, $fe, $00, $1a, $ff, $f9, $7f, $1a, $fb, $18, $fb, $50, $fe, $00, $16, $ff, $f9, $fd, $7f, $18
	.byte $fb, $50, $fe, $00, $16, $ff, $f9, $fd, $7f, $15, $fb, $50, $fe, $00, $13, $ff, $f9, $7f, $50, $fe, $00, $11, $ff, $f9
	.byte $7f, $14, $ff, $bb, $13, $bb, $bf, $50, $fe, $00, $11, $ff, $b9, $fd, $00, $ed, $7f, $8d, $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
@song3ref912:
	.byte $ff, $fb, $ff, $fb, $ff, $fb, $ff, $ff, $db
@song3ref921:
	.byte $ff
@song3ref922:
	.byte $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $ff, $ff
	.byte $b9
	.byte $41, $17
	.word @song3ref921
	.byte $41, $0c
	.word @song3ref922
	.byte $ef, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $ef
	.byte $41, $17
	.word @song3ref921
	.byte $41, $0f
	.word @song3ref922
	.byte $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $41, $23
	.word @song3ref912
	.byte $41, $17
	.word @song3ref921
	.byte $41, $0c
	.word @song3ref922
	.byte $ef, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $ef
	.byte $41, $17
	.word @song3ref921
	.byte $41, $0f
	.word @song3ref922
	.byte $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $41, $23
	.word @song3ref912
	.byte $41, $17
	.word @song3ref921
	.byte $41, $0c
	.word @song3ref922
	.byte $ef, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $ef
	.byte $41, $17
	.word @song3ref921
	.byte $41, $0f
	.word @song3ref922
	.byte $42
	.word @song3ch4loop
@song3ch5:
@song3ch5loop:
	.byte $41, $1f
	.word @song3ref912
	.byte $e9, $8c, $1b, $91, $7f, $50, $fe, $00, $ff, $ff, $97, $00, $9d, $7f, $83
@song3ref1046:
	.byte $1d, $e9, $29, $ff, $8d, $24, $ff, $f1, $00, $85, $22, $e9, $29, $ff, $8d, $1d, $ff, $f9, $1d, $ff, $22, $f7, $1d, $81
	.byte $29, $e3, $2b, $ff, $8b, $00, $81, $29, $fb, $24, $e7, $22, $91, $ff, $f3, $00, $85
	.byte $41, $29
	.word @song3ref1046
	.byte $1d, $fb, $29, $bd, $26, $bb, $24, $b9, $22, $b9, $21, $a5, $22, $cd
@song3ref1104:
	.byte $24, $f9, $00, $2d, $b5, $2c, $9d, $2b, $a3, $29, $ff, $f5, $00, $81, $1f, $fb, $29, $bd, $26, $bb, $24, $b9, $22, $cb
	.byte $24, $9f, $26, $c1
@song3ref1132:
	.byte $21, $fb, $24, $fb, $24, $bd, $22, $bb, $21, $bd, $22, $bb, $1d, $fb, $29, $bd, $26, $bb, $24, $bd, $22, $bb, $21, $a7
	.byte $22, $d1
	.byte $41, $15
	.word @song3ref1104
	.byte $bd, $22, $cd, $24, $a3, $26, $c3
	.byte $41, $0c
	.word @song3ref1132
	.byte $50, $fe, $00, $1d, $ff, $f9, $fd, $7f, $1b, $bd, $1d, $bb, $50, $fe, $00, $1a, $ff, $f9, $fd, $7f, $18, $bd, $1a, $bb
	.byte $50, $fe, $00, $16, $ff, $f9, $7f, $50, $fe, $00, $16, $ff, $f9, $7f, $50, $fd, $00, $16, $ff, $bb, $7f, $16, $bb, $bf
	.byte $50, $fe, $00, $16, $ff, $b9, $fd, $00, $ed, $7f, $8d, $42
	.word @song3ch5loop
@song3ch6:
@song3ch6loop:
	.byte $41, $1f
	.word @song3ref912
	.byte $e3, $8c, $16, $97, $7f, $50, $fe, $00, $ff, $ff, $97, $00, $9d, $7f, $83
@song3ref1252:
	.byte $11, $e9, $1d, $ff, $8d, $18, $ff, $f1, $00, $85, $16, $e9, $1d, $ff, $8d, $11, $ff, $f9, $11, $ff, $16, $f7, $11, $81
	.byte $1d, $e3, $1f, $ff, $8b, $00, $81, $1d, $fb, $18, $e7, $16, $91, $ff, $f3, $00, $85
	.byte $41, $29
	.word @song3ref1252
	.byte $11, $fb, $1d, $bd, $1a, $bb, $18, $b9, $16, $b9, $15, $a5, $16, $cd
@song3ref1310:
	.byte $18, $f9, $00, $21, $b5, $20, $9d, $1f, $a3, $1d, $ff, $f5, $00, $81, $13, $fb, $1d, $bd, $1a, $bb, $18, $b9, $16, $cb
	.byte $18, $9f, $1a, $c1
@song3ref1338:
	.byte $15, $fb, $18, $fb, $18, $bd, $16, $bb, $15, $bd, $16, $bb, $11, $fb, $1d, $bd, $1a, $bb, $18, $bd, $16, $bb, $15, $a7
	.byte $16, $d1
	.byte $41, $15
	.word @song3ref1310
	.byte $bd, $16, $cd, $18, $a3, $1a, $c3
	.byte $41, $0c
	.word @song3ref1338
	.byte $50, $fe, $00, $11, $ff, $f9, $fd, $7f, $0f, $bd, $11, $bb, $50, $fe, $00, $0e, $ff, $f9, $fd, $7f, $0c, $bd, $0e, $bb
	.byte $50, $fe, $00, $0a, $ff, $f9, $7f, $50, $fe, $00, $0a, $ff, $f9, $7f, $50, $fd, $00, $0a, $ff, $bb, $7f, $0a, $bb, $bf
	.byte $50, $fe, $00, $0a, $ff, $b9, $fd, $00, $ed, $7f, $8d, $42
	.word @song3ch6loop
